 .DC.B $0F,$FB,$B0
 .DC.B $00,$02,$00
;
 .DC.B $0F,$FB,$B0
 .DC.B $02,$40,$00
;
 .DC.B $01,$AB,$B0
 .DC.B $00,$A0,$00
;
 .DC.B $01,$AB,$B0
 .DC.B $00,$14,$00
;
 .DC.B $0A,$AA,$B8
 .DC.B $00,$28,$00
;
 .DC.B $0A,$AA,$B8
 .DC.B $00,$14,$00
;
 .DC.B $0E,$FB,$B8
 .DC.B $00,$80,$00
;
 .DC.B $0E,$FB,$B8
 .DC.B $00,$02,$00
;
 .DC.B $0E,$FB,$B0
 .DC.B $00,$09,$00
;
 .DC.B $0E,$FB,$B0
 .DC.B $00,$00,$00
;
 .DC.B $2E,$EF,$B0
 .DC.B $00,$02,$00
;
 .DC.B $2E,$EF,$B0
 .DC.B $00,$80,$00
;
 .DC.B $2E,$AA,$A0
 .DC.B $00,$28,$00
;
 .DC.B $2E,$AA,$A0
 .DC.B $00,$14,$00
;
 .DC.B $0E,$EA,$40
 .DC.B $00,$0A,$00
;
 .DC.B $0E,$EA,$40
 .DC.B $00,$14,$00
;
 .DC.B $00
;
 .DC.B $00
