 .DC.B $0F,$FE,$F0
 .DC.B $00,$09,$00
;
 .DC.B $0F,$FE,$F0
 .DC.B $03,$80,$00
;
 .DC.B $00,$AB,$B0
 .DC.B $00,$26,$80
;
 .DC.B $00,$AB,$B0
 .DC.B $00,$29,$24
;
 .DC.B $2A,$AA,$B8
 .DC.B $00,$09,$A0
;
 .DC.B $2A,$AA,$B8
 .DC.B $00,$29,$24
;
 .DC.B $0F,$FB,$B8
 .DC.B $00,$90,$00
;
 .DC.B $0F,$FB,$B8
 .DC.B $00,$02,$40
;
 .DC.B $0E,$FE,$B0
 .DC.B $00,$0A,$00
;
 .DC.B $0E,$FE,$B0
 .DC.B $02,$40,$00
;
 .DC.B $2E,$EF,$F0
 .DC.B $00,$06,$00
;
 .DC.B $2E,$EF,$F0
 .DC.B $01,$80,$00
;
 .DC.B $2E,$AA,$A8
 .DC.B $0A,$60,$00
;
 .DC.B $2E,$AA,$A8
 .DC.B $18,$68,$00
;
 .DC.B $0E,$EA,$00
 .DC.B $02,$98,$00
;
 .DC.B $0E,$EA,$00
 .DC.B $18,$68,$00
;
 .DC.B $00
;
 .DC.B $00
