 .DC.B $0F,$FE,$F0
 .DC.B $00,$0F,$00
;
 .DC.B $0F,$FE,$F0
 .DC.B $03,$C0,$00
;
 .DC.B $08,$EB,$B0
 .DC.B $00,$28,$90
;
 .DC.B $08,$EB,$B0
 .DC.B $00,$0A,$28
;
 .DC.B $03,$EE,$F8
 .DC.B $00,$0A,$24
;
 .DC.B $03,$EE,$F8
 .DC.B $00,$0A,$28
;
 .DC.B $0F,$FE,$D0
 .DC.B $00,$A0,$00
;
 .DC.B $0F,$FE,$D0
 .DC.B $00,$02,$80
;
 .DC.B $0F,$DE,$F0
 .DC.B $00,$0E,$00
;
 .DC.B $0F,$DE,$F0
 .DC.B $02,$80,$00
;
 .DC.B $07,$BF,$F0
 .DC.B $00,$0A,$00
;
 .DC.B $07,$BF,$F0
 .DC.B $02,$80,$00
;
 .DC.B $2F,$BB,$C0
 .DC.B $18,$A0,$00
;
 .DC.B $2F,$BB,$C0
 .DC.B $28,$A0,$00
;
 .DC.B $0E,$EB,$20
 .DC.B $06,$28,$00
;
 .DC.B $0E,$EB,$20
 .DC.B $28,$A0,$00
;
 .DC.B $00
;
 .DC.B $00
