 .DC.B $0F,$FF,$B0
 .DC.B $00,$0F,$00
;
 .DC.B $0F,$FF,$B0
 .DC.B $03,$C0,$00
;
 .DC.B $08,$AF,$B0
 .DC.B $00,$18,$A0
;
 .DC.B $08,$AF,$B0
 .DC.B $00,$0A,$09
;
 .DC.B $03,$FB,$F8
 .DC.B $00,$06,$28
;
 .DC.B $03,$FB,$F8
 .DC.B $00,$0A,$09
;
 .DC.B $0F,$5E,$E0
 .DC.B $00,$E0,$00
;
 .DC.B $0F,$5E,$E0
 .DC.B $00,$03,$80
;
 .DC.B $0F,$57,$B0
 .DC.B $00,$0F,$00
;
 .DC.B $0F,$57,$B0
 .DC.B $03,$80,$00
;
 .DC.B $0B,$B5,$F0
 .DC.B $00,$0B,$00
;
 .DC.B $0B,$B5,$F0
 .DC.B $02,$C0,$00
;
 .DC.B $2F,$EF,$C0
 .DC.B $28,$90,$00
;
 .DC.B $2F,$EF,$C0
 .DC.B $60,$A0,$00
;
 .DC.B $0E,$FA,$20
 .DC.B $0A,$24,$00
;
 .DC.B $0E,$FA,$20
 .DC.B $60,$A0,$00
;
 .DC.B $00
;
 .DC.B $00
