 .DC.B $0F,$FF,$B0
 .DC.B $00,$0F,$00
;
 .DC.B $0F,$FF,$B0
 .DC.B $03,$C0,$00
;
 .DC.B $06,$BF,$E0
 .DC.B $00,$BE,$E0
;
 .DC.B $06,$BF,$E0
 .DC.B $00,$2D,$0A
;
 .DC.B $03,$FB,$E0
 .DC.B $00,$2F,$B8
;
 .DC.B $03,$FB,$E0
 .DC.B $00,$2D,$0A
;
 .DC.B $0B,$AF,$80
 .DC.B $00,$D0,$00
;
 .DC.B $0B,$AF,$80
 .DC.B $00,$03,$C0
;
 .DC.B $0F,$AB,$B0
 .DC.B $00,$0F,$00
;
 .DC.B $0F,$AB,$B0
 .DC.B $03,$C0,$00
;
 .DC.B $02,$FA,$E0
 .DC.B $00,$07,$00
;
 .DC.B $02,$FA,$E0
 .DC.B $03,$C0,$00
;
 .DC.B $0B,$EF,$C0
 .DC.B $2E,$F8,$00
;
 .DC.B $0B,$EF,$C0
 .DC.B $A0,$78,$00
;
 .DC.B $0B,$FE,$90
 .DC.B $0B,$BE,$00
;
 .DC.B $0B,$FE,$90
 .DC.B $A0,$78,$00
;
 .DC.B $00
;
 .DC.B $00
