 .DC.B $0B,$EB,$E0
 .DC.B $00,$07,$00
;
 .DC.B $0B,$EB,$E0
 .DC.B $03,$C0,$00
;
 .DC.B $0A,$FF,$E0
 .DC.B $00,$7B,$D0
;
 .DC.B $0A,$FF,$E0
 .DC.B $00,$3F,$0E
;
 .DC.B $03,$7E,$E0
 .DC.B $00,$1E,$F4
;
 .DC.B $03,$7E,$E0
 .DC.B $00,$3F,$0E
;
 .DC.B $02,$FB,$80
 .DC.B $00,$F2,$40
;
 .DC.B $02,$FB,$80
 .DC.B $00,$93,$40
;
 .DC.B $06,$FE,$E0
 .DC.B $02,$4F,$00
;
 .DC.B $06,$FE,$E0
 .DC.B $03,$C0,$00
;
 .DC.B $02,$EF,$80
 .DC.B $01,$8F,$00
;
 .DC.B $02,$EF,$80
 .DC.B $01,$C6,$00
;
 .DC.B $0B,$BD,$C0
 .DC.B $1F,$B4,$00
;
 .DC.B $0B,$BD,$C0
 .DC.B $B0,$FC,$00
;
 .DC.B $0B,$FF,$A0
 .DC.B $07,$ED,$00
;
 .DC.B $0B,$FF,$A0
 .DC.B $B0,$FC,$00
;
 .DC.B $00
;
 .DC.B $00
