
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	GAME EQUATES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
ROMDATA1	=	$C000
ROMDATA		=	$E000
ROMCODE		=	$F000

ZONESIZE	=	64	

MAPMAX		=	89
MANMAX		=	6

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	OBJECT EQUATES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

SAND		=	0
TREN		=	1
SHELLL		=	2
SHELLR		=	3
TREE		=	4
MTANL		=	5
HAY		=	6
CANNL		=	7
TUNNL		=	8
MTANR		=	9
CANNR		=	10
UJOA		=	11
UJOB		=	12
LUJOA		=	13
LUJOB		=	14
LJOA		=	15
LJOB		=	16
LDJOA		=	17
LDJOB		=	18
DJOA		=	19
DJOB		=	20
RDJOA		=	21
RDJOB		=	22
RJOA		=	23
RJOB		=	24
RUJOA		=	25
RUJOB		=	26
GREN		=	27
BULL		=	28
