; FRAME # 1  ALI   /SPR

	ORG	RBMA + $0000

	DC.B	$00,$FF,$00

	ORG	RBMA + $0100

	DC.B	$03,$00,$C0

	ORG	RBMA + $0200

	DC.B	$03,$00,$C0

	ORG	RBMA + $0300

	DC.B	$00,$FF,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  ALI   /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$05,$55,$50

	ORG	RBMA + $0300 + $03

	DC.B	$01,$55,$40

	ORG	RBMA + $0400 + $03

	DC.B	$00,$11,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  ALI   /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$55,$55,$55

	ORG	RBMA + $0300 + $06

	DC.B	$05,$55,$D5

	ORG	RBMA + $0400 + $06

	DC.B	$05,$55,$54

	ORG	RBMA + $0500 + $06

	DC.B	$00,$55,$54

	ORG	RBMA + $0600 + $06

	DC.B	$00,$04,$10

	ORG	RBMA + $0700 + $06

	DC.B	$00,$04,$10

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  ALI   /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$0D,$54

	ORG	RBMA + $0300 + $09

	DC.B	$00,$35,$54

	ORG	RBMA + $0400 + $09

	DC.B	$00,$D5,$74

	ORG	RBMA + $0500 + $09

	DC.B	$0C,$55,$54

	ORG	RBMA + $0600 + $09

	DC.B	$D5,$55,$54

	ORG	RBMA + $0700 + $09

	DC.B	$55,$00,$50

	ORG	RBMA + $0800 + $09

	DC.B	$10,$00,$10

	ORG	RBMA + $0900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

; FRAME # 5  ALI   /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$55,$55,$55

	ORG	RBMA + $0300 + $0C

	DC.B	$01,$55,$54

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$15,$54

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$0D,$55

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$7D,$75

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$D5,$55

	ORG	RBMA + $0800 + $0C

	DC.B	$03,$55,$54

	ORG	RBMA + $0900 + $0C

	DC.B	$0D,$54,$10

	ORG	RBMA + $0A00 + $0C

	DC.B	$D5,$50,$00

	ORG	RBMA + $0B00 + $0C

	DC.B	$55,$00,$00

	ORG	RBMA + $0C00 + $0C

	DC.B	$50,$00,$00

	ORG	RBMA + $0D00 + $0C

	DC.B	$40,$00,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$00,$00,$00

; FRAME # 6  ALI   /SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$00,$15,$55

	ORG	RBMA + $0300 + $0F

	DC.B	$00,$05,$54

	ORG	RBMA + $0400 + $0F

	DC.B	$00,$15,$54

	ORG	RBMA + $0500 + $0F

	DC.B	$00,$15,$55

	ORG	RBMA + $0600 + $0F

	DC.B	$00,$55,$75

	ORG	RBMA + $0700 + $0F

	DC.B	$01,$55,$55

	ORG	RBMA + $0800 + $0F

	DC.B	$05,$55,$54

	ORG	RBMA + $0900 + $0F

	DC.B	$15,$54,$10

	ORG	RBMA + $0A00 + $0F

	DC.B	$15,$50,$00

	ORG	RBMA + $0B00 + $0F

	DC.B	$55,$00,$00

	ORG	RBMA + $0C00 + $0F

	DC.B	$50,$00,$00

	ORG	RBMA + $0D00 + $0F

	DC.B	$40,$00,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $0F

	DC.B	$00,$00,$00

	.END
