; FRAME # 1  ANTL2 /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$82,$00

	ORG	RBMA + $0300

	DC.B	$00,$81,$00

	ORG	RBMA + $0400

	DC.B	$00,$48,$00

	ORG	RBMA + $0500

	DC.B	$00,$49,$54

	ORG	RBMA + $0600

	DC.B	$20,$45,$50

	ORG	RBMA + $0700

	DC.B	$25,$55,$50

	ORG	RBMA + $0800

	DC.B	$15,$55,$50

	ORG	RBMA + $0900

	DC.B	$15,$55,$50

	ORG	RBMA + $0A00

	DC.B	$15,$25,$50

	ORG	RBMA + $0B00

	DC.B	$25,$05,$40

	ORG	RBMA + $0C00

	DC.B	$24,$09,$40

	ORG	RBMA + $0D00

	DC.B	$21,$00,$00

	ORG	RBMA + $0E00

	DC.B	$22,$40,$00

	ORG	RBMA + $0F00

	DC.B	$04,$00,$00

; FRAME # 2  ANTL2 /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$10

	ORG	RBMA + $0200 + $03

	DC.B	$00,$10,$90

	ORG	RBMA + $0300 + $03

	DC.B	$00,$90,$80

	ORG	RBMA + $0400 + $03

	DC.B	$04,$81,$80

	ORG	RBMA + $0500 + $03

	DC.B	$06,$81,$50

	ORG	RBMA + $0600 + $03

	DC.B	$24,$55,$50

	ORG	RBMA + $0700 + $03

	DC.B	$15,$55,$50

	ORG	RBMA + $0800 + $03

	DC.B	$95,$55,$50

	ORG	RBMA + $0900 + $03

	DC.B	$15,$55,$50

	ORG	RBMA + $0A00 + $03

	DC.B	$15,$65,$50

	ORG	RBMA + $0B00 + $03

	DC.B	$24,$45,$40

	ORG	RBMA + $0C00 + $03

	DC.B	$24,$09,$40

	ORG	RBMA + $0D00 + $03

	DC.B	$04,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$04,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$20,$00,$00

; FRAME # 3  ANTL2 /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$10,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$11,$10,$20

	ORG	RBMA + $0400 + $06

	DC.B	$21,$98,$20

	ORG	RBMA + $0500 + $06

	DC.B	$45,$89,$50

	ORG	RBMA + $0600 + $06

	DC.B	$94,$55,$50

	ORG	RBMA + $0700 + $06

	DC.B	$95,$55,$50

	ORG	RBMA + $0800 + $06

	DC.B	$95,$55,$50

	ORG	RBMA + $0900 + $06

	DC.B	$95,$55,$50

	ORG	RBMA + $0A00 + $06

	DC.B	$25,$25,$50

	ORG	RBMA + $0B00 + $06

	DC.B	$24,$09,$40

	ORG	RBMA + $0C00 + $06

	DC.B	$18,$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$81,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  ANTL2 /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$10,$00,$20

	ORG	RBMA + $0300 + $09

	DC.B	$11,$00,$10

	ORG	RBMA + $0400 + $09

	DC.B	$21,$04,$80

	ORG	RBMA + $0500 + $09

	DC.B	$61,$05,$50

	ORG	RBMA + $0600 + $09

	DC.B	$95,$15,$50

	ORG	RBMA + $0700 + $09

	DC.B	$95,$55,$54

	ORG	RBMA + $0800 + $09

	DC.B	$95,$55,$54

	ORG	RBMA + $0900 + $09

	DC.B	$95,$55,$50

	ORG	RBMA + $0A00 + $09

	DC.B	$25,$25,$50

	ORG	RBMA + $0B00 + $09

	DC.B	$24,$09,$40

	ORG	RBMA + $0C00 + $09

	DC.B	$18,$00,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$81,$00,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

	.END
