; FRAME # 1  ANTR2 /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$02,$08,$00

	ORG	RBMA + $0300

	DC.B	$01,$08,$00

	ORG	RBMA + $0400

	DC.B	$00,$84,$00

	ORG	RBMA + $0500

	DC.B	$55,$84,$00

	ORG	RBMA + $0600

	DC.B	$15,$44,$20

	ORG	RBMA + $0700

	DC.B	$15,$55,$60

	ORG	RBMA + $0800

	DC.B	$15,$55,$50

	ORG	RBMA + $0900

	DC.B	$15,$55,$50

	ORG	RBMA + $0A00

	DC.B	$15,$61,$50

	ORG	RBMA + $0B00

	DC.B	$05,$41,$60

	ORG	RBMA + $0C00

	DC.B	$05,$80,$60

	ORG	RBMA + $0D00

	DC.B	$00,$01,$20

	ORG	RBMA + $0E00

	DC.B	$00,$06,$20

	ORG	RBMA + $0F00

	DC.B	$00,$00,$40

; FRAME # 2  ANTR2 /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$10,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$18,$10,$00

	ORG	RBMA + $0300 + $03

	DC.B	$08,$18,$00

	ORG	RBMA + $0400 + $03

	DC.B	$09,$08,$40

	ORG	RBMA + $0500 + $03

	DC.B	$15,$0A,$40

	ORG	RBMA + $0600 + $03

	DC.B	$15,$54,$60

	ORG	RBMA + $0700 + $03

	DC.B	$15,$55,$50

	ORG	RBMA + $0800 + $03

	DC.B	$15,$55,$58

	ORG	RBMA + $0900 + $03

	DC.B	$15,$55,$50

	ORG	RBMA + $0A00 + $03

	DC.B	$15,$65,$50

	ORG	RBMA + $0B00 + $03

	DC.B	$05,$44,$60

	ORG	RBMA + $0C00 + $03

	DC.B	$05,$80,$60

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$00,$40

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$40

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$20

; FRAME # 3  ANTR2 /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$10

	ORG	RBMA + $0300 + $06

	DC.B	$20,$11,$10

	ORG	RBMA + $0400 + $06

	DC.B	$20,$99,$20

	ORG	RBMA + $0500 + $06

	DC.B	$15,$89,$44

	ORG	RBMA + $0600 + $06

	DC.B	$15,$54,$58

	ORG	RBMA + $0700 + $06

	DC.B	$15,$55,$58

	ORG	RBMA + $0800 + $06

	DC.B	$15,$55,$58

	ORG	RBMA + $0900 + $06

	DC.B	$15,$55,$58

	ORG	RBMA + $0A00 + $06

	DC.B	$15,$61,$60

	ORG	RBMA + $0B00 + $06

	DC.B	$05,$80,$60

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00,$90

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$01,$08

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  ANTR2 /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$20,$00,$10

	ORG	RBMA + $0300 + $09

	DC.B	$10,$01,$10

	ORG	RBMA + $0400 + $09

	DC.B	$08,$41,$20

	ORG	RBMA + $0500 + $09

	DC.B	$15,$41,$24

	ORG	RBMA + $0600 + $09

	DC.B	$15,$51,$58

	ORG	RBMA + $0700 + $09

	DC.B	$55,$55,$58

	ORG	RBMA + $0800 + $09

	DC.B	$55,$55,$58

	ORG	RBMA + $0900 + $09

	DC.B	$15,$55,$58

	ORG	RBMA + $0A00 + $09

	DC.B	$15,$61,$60

	ORG	RBMA + $0B00 + $09

	DC.B	$05,$80,$60

	ORG	RBMA + $0C00 + $09

	DC.B	$00,$00,$90

	ORG	RBMA + $0D00 + $09

	DC.B	$00,$01,$08

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

	.END
