; FRAME # 1  ARCH2 /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$20,$00,$00

	ORG	RBMA + $0C00

	DC.B	$20,$00,$00

	ORG	RBMA + $0D00

	DC.B	$20,$00,$00

	ORG	RBMA + $0E00

	DC.B	$20,$0A,$40

	ORG	RBMA + $0F00

	DC.B	$20,$06,$A8

	ORG	RBMA + $1000

	DC.B	$20,$15,$28

	ORG	RBMA + $1100

	DC.B	$20,$A8,$80

	ORG	RBMA + $1200

	DC.B	$08,$22,$80

	ORG	RBMA + $1300

	DC.B	$08,$22,$80

	ORG	RBMA + $1400

	DC.B	$08,$8A,$80

	ORG	RBMA + $1500

	DC.B	$02,$8A,$00

	ORG	RBMA + $1600

	DC.B	$02,$00,$00

	ORG	RBMA + $1700

	DC.B	$02,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00

; FRAME # 2  ARCH2 /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$02,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$08,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$08,$02,$80

	ORG	RBMA + $0F00 + $03

	DC.B	$05,$02,$A8

	ORG	RBMA + $1000 + $03

	DC.B	$05,$82,$A8

	ORG	RBMA + $1100 + $03

	DC.B	$22,$AA,$28

	ORG	RBMA + $1200 + $03

	DC.B	$20,$AA,$28

	ORG	RBMA + $1300 + $03

	DC.B	$20,$29,$A0

	ORG	RBMA + $1400 + $03

	DC.B	$20,$01,$60

	ORG	RBMA + $1500 + $03

	DC.B	$20,$0A,$68

	ORG	RBMA + $1600 + $03

	DC.B	$20,$06,$A8

	ORG	RBMA + $1700 + $03

	DC.B	$20,$15,$28

	ORG	RBMA + $1800 + $03

	DC.B	$20,$A8,$80

	ORG	RBMA + $1900 + $03

	DC.B	$08,$22,$80

	ORG	RBMA + $1A00 + $03

	DC.B	$08,$22,$80

	ORG	RBMA + $1B00 + $03

	DC.B	$08,$8A,$80

	ORG	RBMA + $1C00 + $03

	DC.B	$02,$8A,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$02,$00,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$02,$00,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  ARCH2 /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$02,$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$08,$80,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$08,$82,$80

	ORG	RBMA + $0F00 + $06

	DC.B	$05,$02,$A8

	ORG	RBMA + $1000 + $06

	DC.B	$05,$82,$A8

	ORG	RBMA + $1100 + $06

	DC.B	$22,$AA,$A8

	ORG	RBMA + $1200 + $06

	DC.B	$20,$AA,$A8

	ORG	RBMA + $1300 + $06

	DC.B	$82,$29,$A0

	ORG	RBMA + $1400 + $06

	DC.B	$82,$01,$60

	ORG	RBMA + $1500 + $06

	DC.B	$82,$0A,$68

	ORG	RBMA + $1600 + $06

	DC.B	$88,$06,$A8

	ORG	RBMA + $1700 + $06

	DC.B	$88,$15,$28

	ORG	RBMA + $1800 + $06

	DC.B	$88,$AA,$80

	ORG	RBMA + $1900 + $06

	DC.B	$88,$2A,$80

	ORG	RBMA + $1A00 + $06

	DC.B	$28,$2A,$80

	ORG	RBMA + $1B00 + $06

	DC.B	$28,$0A,$80

	ORG	RBMA + $1C00 + $06

	DC.B	$20,$0A,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$20,$00,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  ARCH2 /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$02,$00,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$08,$80,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$08,$82,$80

	ORG	RBMA + $0F00 + $09

	DC.B	$05,$02,$A8

	ORG	RBMA + $1000 + $09

	DC.B	$05,$82,$A8

	ORG	RBMA + $1100 + $09

	DC.B	$22,$A5,$A8

	ORG	RBMA + $1200 + $09

	DC.B	$20,$A5,$A0

	ORG	RBMA + $1300 + $09

	DC.B	$82,$2A,$A8

	ORG	RBMA + $1400 + $09

	DC.B	$82,$0A,$A8

	ORG	RBMA + $1500 + $09

	DC.B	$82,$0A,$A0

	ORG	RBMA + $1600 + $09

	DC.B	$88,$06,$80

	ORG	RBMA + $1700 + $09

	DC.B	$88,$15,$00

	ORG	RBMA + $1800 + $09

	DC.B	$88,$AA,$80

	ORG	RBMA + $1900 + $09

	DC.B	$88,$2A,$80

	ORG	RBMA + $1A00 + $09

	DC.B	$28,$2A,$80

	ORG	RBMA + $1B00 + $09

	DC.B	$28,$0A,$80

	ORG	RBMA + $1C00 + $09

	DC.B	$20,$0A,$00

	ORG	RBMA + $1D00 + $09

	DC.B	$20,$00,$00

	ORG	RBMA + $1E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $09

	DC.B	$00,$00,$00

; FRAME # 5  ARCH2 /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $0C

	DC.B	$20,$00,$00

	ORG	RBMA + $0C00 + $0C

	DC.B	$20,$00,$00

	ORG	RBMA + $0D00 + $0C

	DC.B	$20,$80,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$20,$8A,$40

	ORG	RBMA + $0F00 + $0C

	DC.B	$20,$86,$A0

	ORG	RBMA + $1000 + $0C

	DC.B	$22,$15,$20

	ORG	RBMA + $1100 + $0C

	DC.B	$22,$A8,$80

	ORG	RBMA + $1200 + $0C

	DC.B	$0A,$2A,$80

	ORG	RBMA + $1300 + $0C

	DC.B	$0A,$2A,$80

	ORG	RBMA + $1400 + $0C

	DC.B	$0A,$0A,$80

	ORG	RBMA + $1500 + $0C

	DC.B	$02,$0A,$00

	ORG	RBMA + $1600 + $0C

	DC.B	$02,$00,$00

	ORG	RBMA + $1700 + $0C

	DC.B	$02,$00,$00

	ORG	RBMA + $1800 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $0C

	DC.B	$00,$00,$00

	.END
