; FRAME # 1  ARROW /SPR

	ORG	RBMA + $0000

	DC.B	$FC,$00,$00

	ORG	RBMA + $0100

	DC.B	$F0,$00,$00

	ORG	RBMA + $0200

	DC.B	$D4,$00,$00

	ORG	RBMA + $0300

	DC.B	$C4,$00,$00

	ORG	RBMA + $0400

	DC.B	$01,$00,$00

	ORG	RBMA + $0500

	DC.B	$01,$40,$00

	ORG	RBMA + $0600

	DC.B	$00,$40,$00

	ORG	RBMA + $0700

	DC.B	$00,$10,$00

	ORG	RBMA + $0800

	DC.B	$00,$14,$00

	ORG	RBMA + $0900

	DC.B	$00,$04,$00

	ORG	RBMA + $0A00

	DC.B	$00,$02,$80

	ORG	RBMA + $0B00

	DC.B	$00,$02,$A0

	ORG	RBMA + $0C00

	DC.B	$00,$02,$28

	ORG	RBMA + $0D00

	DC.B	$00,$02,$80

	ORG	RBMA + $0E00

	DC.B	$00,$00,$80

	ORG	RBMA + $0F00

	DC.B	$00,$00,$80

; FRAME # 2  ARROW /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$30,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$3C,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$D3,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$D0,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$10,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$14,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$04,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$04,$00,$00

	ORG	RBMA + $0800 + $03

	DC.B	$05,$00,$00

	ORG	RBMA + $0900 + $03

	DC.B	$01,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$01,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$01,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$02,$28,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$08,$80,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$08,$A0,$00

	.END
