; FRAME # 1  ARROW3/SPR

	ORG	RBMA + $0000

	DC.B	$A0,$00,$00

	ORG	RBMA + $0100

	DC.B	$90,$00,$00

	ORG	RBMA + $0200

	DC.B	$10,$00,$00

	ORG	RBMA + $0300

	DC.B	$04,$00,$00

	ORG	RBMA + $0400

	DC.B	$04,$00,$00

	ORG	RBMA + $0500

	DC.B	$01,$00,$00

	ORG	RBMA + $0600

	DC.B	$01,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$40,$00

	ORG	RBMA + $0800

	DC.B	$00,$40,$00

	ORG	RBMA + $0900

	DC.B	$00,$10,$00

	ORG	RBMA + $0A00

	DC.B	$00,$10,$00

	ORG	RBMA + $0B00

	DC.B	$00,$04,$00

	ORG	RBMA + $0C00

	DC.B	$00,$0F,$00

	ORG	RBMA + $0D00

	DC.B	$00,$0C,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

	.END
