; FRAME # 1  BAT1  /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$02,$9A,$00

	ORG	RBMA + $0900

	DC.B	$08,$00,$80

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  BAT1  /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$20,$00,$08

	ORG	RBMA + $0600 + $03

	DC.B	$0A,$00,$A0

	ORG	RBMA + $0700 + $03

	DC.B	$00,$AA,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$18,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$28,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  BAT1  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$AA,$00

	ORG	RBMA + $0700 + $06

	DC.B	$02,$AA,$80

	ORG	RBMA + $0800 + $06

	DC.B	$0A,$96,$A0

	ORG	RBMA + $0900 + $06

	DC.B	$28,$2A,$28

	ORG	RBMA + $0A00 + $06

	DC.B	$A0,$00,$0A

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

	.END
