; FRAME # 1  BAT2  /SPR

	ORG	RBMA + $0000

	DC.B	$0A,$00,$00

	ORG	RBMA + $0100

	DC.B	$02,$AA,$80

	ORG	RBMA + $0200

	DC.B	$02,$AA,$A0

	ORG	RBMA + $0300

	DC.B	$00,$AA,$A0

	ORG	RBMA + $0400

	DC.B	$00,$2A,$A0

	ORG	RBMA + $0500

	DC.B	$00,$2A,$A8

	ORG	RBMA + $0600

	DC.B	$00,$2A,$A8

	ORG	RBMA + $0700

	DC.B	$00,$0A,$A8

	ORG	RBMA + $0800

	DC.B	$00,$00,$20

	ORG	RBMA + $0900

	DC.B	$00,$00,$A8

	ORG	RBMA + $0A00

	DC.B	$00,$00,$A8

	ORG	RBMA + $0B00

	DC.B	$00,$00,$A0

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  BAT2  /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$02,$A8,$80

	ORG	RBMA + $0700 + $03

	DC.B	$00,$AA,$A0

	ORG	RBMA + $0800 + $03

	DC.B	$02,$AA,$A5

	ORG	RBMA + $0900 + $03

	DC.B	$02,$AA,$A5

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$AA,$A2

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$A8,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  BAT2  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$0A,$A0

	ORG	RBMA + $0700 + $06

	DC.B	$00,$2A,$A8

	ORG	RBMA + $0800 + $06

	DC.B	$00,$AA,$A9

	ORG	RBMA + $0900 + $06

	DC.B	$00,$AA,$A9

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$AA,$A8

	ORG	RBMA + $0B00 + $06

	DC.B	$02,$AA,$88

	ORG	RBMA + $0C00 + $06

	DC.B	$0A,$AA,$28

	ORG	RBMA + $0D00 + $06

	DC.B	$0A,$A8,$2A

	ORG	RBMA + $0E00 + $06

	DC.B	$2A,$A0,$28

	ORG	RBMA + $0F00 + $06

	DC.B	$28,$00,$00

	.END
