; FRAME # 1  BEAVER/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$FF,$00

	ORG	RBMA + $0F00

	DC.B	$03,$00,$C0

	ORG	RBMA + $1000

	DC.B	$03,$00,$C0

	ORG	RBMA + $1100

	DC.B	$00,$FF,$00

	ORG	RBMA + $1200

	DC.B	$00,$00,$00

	ORG	RBMA + $1300

	DC.B	$00,$00,$00

	ORG	RBMA + $1400

	DC.B	$00,$00,$00

	ORG	RBMA + $1500

	DC.B	$00,$00,$00

	ORG	RBMA + $1600

	DC.B	$00,$00,$00

	ORG	RBMA + $1700

	DC.B	$00,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00

; FRAME # 2  BEAVER/SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$FF,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$0F,$00,$F0

	ORG	RBMA + $0D00 + $03

	DC.B	$30,$00,$0C

	ORG	RBMA + $0E00 + $03

	DC.B	$30,$FF,$0C

	ORG	RBMA + $0F00 + $03

	DC.B	$C3,$00,$C3

	ORG	RBMA + $1000 + $03

	DC.B	$C3,$00,$C3

	ORG	RBMA + $1100 + $03

	DC.B	$C0,$FF,$03

	ORG	RBMA + $1200 + $03

	DC.B	$30,$00,$0C

	ORG	RBMA + $1300 + $03

	DC.B	$0F,$00,$F0

	ORG	RBMA + $1400 + $03

	DC.B	$00,$FF,$00

	ORG	RBMA + $1500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  BEAVER/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$FF,$C0

	ORG	RBMA + $0D00 + $06

	DC.B	$03,$00,$30

	ORG	RBMA + $0E00 + $06

	DC.B	$0C,$00,$0C

	ORG	RBMA + $0F00 + $06

	DC.B	$0C,$14,$0C

	ORG	RBMA + $1000 + $06

	DC.B	$03,$D5,$F0

	ORG	RBMA + $1100 + $06

	DC.B	$00,$55,$40

	ORG	RBMA + $1200 + $06

	DC.B	$01,$55,$40

	ORG	RBMA + $1300 + $06

	DC.B	$00,$55,$40

	ORG	RBMA + $1400 + $06

	DC.B	$00,$55,$00

	ORG	RBMA + $1500 + $06

	DC.B	$01,$77,$00

	ORG	RBMA + $1600 + $06

	DC.B	$01,$40,$00

	ORG	RBMA + $1700 + $06

	DC.B	$00,$55,$00

	ORG	RBMA + $1800 + $06

	DC.B	$00,$14,$00

	ORG	RBMA + $1900 + $06

	DC.B	$00,$14,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  BEAVER/SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$03,$FF,$C0

	ORG	RBMA + $0C00 + $09

	DC.B	$0C,$00,$30

	ORG	RBMA + $0D00 + $09

	DC.B	$30,$55,$0C

	ORG	RBMA + $0E00 + $09

	DC.B	$C1,$55,$43

	ORG	RBMA + $0F00 + $09

	DC.B	$C5,$55,$53

	ORG	RBMA + $1000 + $09

	DC.B	$C5,$55,$53

	ORG	RBMA + $1100 + $09

	DC.B	$C5,$55,$53

	ORG	RBMA + $1200 + $09

	DC.B	$C1,$55,$43

	ORG	RBMA + $1300 + $09

	DC.B	$30,$55,$0C

	ORG	RBMA + $1400 + $09

	DC.B	$0F,$14,$F0

	ORG	RBMA + $1500 + $09

	DC.B	$00,$14,$00

	ORG	RBMA + $1600 + $09

	DC.B	$00,$55,$00

	ORG	RBMA + $1700 + $09

	DC.B	$00,$55,$00

	ORG	RBMA + $1800 + $09

	DC.B	$00,$55,$00

	ORG	RBMA + $1900 + $09

	DC.B	$00,$55,$00

	ORG	RBMA + $1A00 + $09

	DC.B	$00,$77,$00

	ORG	RBMA + $1B00 + $09

	DC.B	$00,$77,$00

	ORG	RBMA + $1C00 + $09

	DC.B	$01,$55,$00

	ORG	RBMA + $1D00 + $09

	DC.B	$01,$55,$00

	ORG	RBMA + $1E00 + $09

	DC.B	$00,$14,$40

	ORG	RBMA + $1F00 + $09

	DC.B	$00,$14,$00

; FRAME # 5  BEAVER/SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $0C

	DC.B	$00,$55,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$01,$55,$40

	ORG	RBMA + $0F00 + $0C

	DC.B	$05,$55,$40

	ORG	RBMA + $1000 + $0C

	DC.B	$05,$55,$50

	ORG	RBMA + $1100 + $0C

	DC.B	$05,$55,$50

	ORG	RBMA + $1200 + $0C

	DC.B	$01,$55,$50

	ORG	RBMA + $1300 + $0C

	DC.B	$00,$55,$50

	ORG	RBMA + $1400 + $0C

	DC.B	$00,$14,$10

	ORG	RBMA + $1500 + $0C

	DC.B	$00,$14,$10

	ORG	RBMA + $1600 + $0C

	DC.B	$00,$14,$10

	ORG	RBMA + $1700 + $0C

	DC.B	$00,$55,$10

	ORG	RBMA + $1800 + $0C

	DC.B	$01,$55,$50

	ORG	RBMA + $1900 + $0C

	DC.B	$01,$55,$50

	ORG	RBMA + $1A00 + $0C

	DC.B	$01,$74,$40

	ORG	RBMA + $1B00 + $0C

	DC.B	$01,$43,$40

	ORG	RBMA + $1C00 + $0C

	DC.B	$01,$54,$00

	ORG	RBMA + $1D00 + $0C

	DC.B	$01,$55,$00

	ORG	RBMA + $1E00 + $0C

	DC.B	$00,$50,$00

	ORG	RBMA + $1F00 + $0C

	DC.B	$00,$00,$00

; FRAME # 6  BEAVER/SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $0F

	DC.B	$00,$55,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$01,$55,$40

	ORG	RBMA + $0F00 + $0F

	DC.B	$05,$55,$50

	ORG	RBMA + $1000 + $0F

	DC.B	$05,$55,$54

	ORG	RBMA + $1100 + $0F

	DC.B	$05,$55,$54

	ORG	RBMA + $1200 + $0F

	DC.B	$01,$55,$45

	ORG	RBMA + $1300 + $0F

	DC.B	$00,$55,$01

	ORG	RBMA + $1400 + $0F

	DC.B	$00,$14,$01

	ORG	RBMA + $1500 + $0F

	DC.B	$00,$14,$01

	ORG	RBMA + $1600 + $0F

	DC.B	$00,$55,$01

	ORG	RBMA + $1700 + $0F

	DC.B	$00,$55,$01

	ORG	RBMA + $1800 + $0F

	DC.B	$00,$55,$01

	ORG	RBMA + $1900 + $0F

	DC.B	$00,$55,$01

	ORG	RBMA + $1A00 + $0F

	DC.B	$00,$77,$01

	ORG	RBMA + $1B00 + $0F

	DC.B	$00,$77,$04

	ORG	RBMA + $1C00 + $0F

	DC.B	$01,$55,$04

	ORG	RBMA + $1D00 + $0F

	DC.B	$01,$55,$00

	ORG	RBMA + $1E00 + $0F

	DC.B	$00,$15,$00

	ORG	RBMA + $1F00 + $0F

	DC.B	$00,$00,$00

	.END
