; FRAME # 1  BIRD2R/SPR

	ORG	RBMA + $0000

	DC.B	$00,$02,$AA,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$2A,$AA,$80,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$2A,$AA,$A3,$00,$00

	ORG	RBMA + $0300

	DC.B	$2A,$AA,$AA,$AF,$C0,$40

	ORG	RBMA + $0400

	DC.B	$82,$AA,$AA,$AC,$F5,$40

	ORG	RBMA + $0500

	DC.B	$00,$0A,$AA,$A0,$35,$40

	ORG	RBMA + $0600

	DC.B	$00,$02,$AA,$AA,$05,$00

	ORG	RBMA + $0700

	DC.B	$2A,$AA,$AA,$8A,$80,$A0

	ORG	RBMA + $0800

	DC.B	$0A,$AA,$AA,$8A,$A8,$A0

	ORG	RBMA + $0900

	DC.B	$0A,$AA,$AA,$2A,$AA,$80

	ORG	RBMA + $0A00

	DC.B	$02,$AA,$A8,$AA,$AA,$80

	ORG	RBMA + $0B00

	DC.B	$02,$AA,$A8,$2A,$AA,$00

	ORG	RBMA + $0C00

	DC.B	$00,$AA,$A8,$0A,$AA,$00

	ORG	RBMA + $0D00

	DC.B	$00,$AA,$A8,$02,$A8,$00

	ORG	RBMA + $0E00

	DC.B	$00,$2A,$A8,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$02,$A0,$00,$00,$00

; FRAME # 2  BIRD2R/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$AA,$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$0A,$AA,$80,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$2A,$AA,$AA,$F0,$01

	ORG	RBMA + $0300 + $06

	DC.B	$AA,$AA,$AA,$AA,$FF,$D5

	ORG	RBMA + $0400 + $06

	DC.B	$0A,$AA,$AA,$A8,$0F,$D4

	ORG	RBMA + $0500 + $06

	DC.B	$00,$2A,$AA,$A2,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$02,$AA,$8A,$00,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$02,$AA,$2A,$80,$00

	ORG	RBMA + $0800 + $06

	DC.B	$00,$02,$A8,$AA,$80,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$0A,$A8,$AA,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$2A,$A2,$AA,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$2A,$A2,$A8,$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$AA,$8A,$A8,$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$02,$AA,$8A,$A0,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$02,$AA,$2A,$A0,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$0A,$AA,$00,$00,$00,$00

; FRAME # 3  BIRD2R/SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$80,$AA,$80,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$22,$AA,$80,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$0A,$AA,$AA,$AA,$0F,$01

	ORG	RBMA + $0300 + $0C

	DC.B	$0A,$AA,$AA,$AA,$FF,$D5

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$2A,$AA,$AA,$F0,$D5

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$AA,$AA,$AA,$00,$14

	ORG	RBMA + $0600 + $0C

	DC.B	$02,$0A,$AA,$AA,$00,$00

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$02,$AA,$A8,$00,$00

	ORG	RBMA + $0800 + $0C

	DC.B	$00,$02,$AA,$A8,$00,$00

	ORG	RBMA + $0900 + $0C

	DC.B	$00,$0A,$AA,$A0,$00,$00

	ORG	RBMA + $0A00 + $0C

	DC.B	$00,$0A,$AA,$A0,$00,$00

	ORG	RBMA + $0B00 + $0C

	DC.B	$00,$02,$00,$00,$00,$00

	ORG	RBMA + $0C00 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0D00 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

; FRAME # 4  BIRD2R/SPR

	ORG	RBMA + $0000 + $12

	DC.B	$0A,$AA,$00,$00,$00,$00

	ORG	RBMA + $0100 + $12

	DC.B	$02,$AA,$8A,$A0,$00,$00

	ORG	RBMA + $0200 + $12

	DC.B	$00,$AA,$A2,$A8,$00,$00

	ORG	RBMA + $0300 + $12

	DC.B	$00,$AA,$A2,$A8,$00,$00

	ORG	RBMA + $0400 + $12

	DC.B	$00,$2A,$A8,$A8,$00,$00

	ORG	RBMA + $0500 + $12

	DC.B	$00,$2A,$A8,$AA,$00,$00

	ORG	RBMA + $0600 + $12

	DC.B	$00,$0A,$A8,$AA,$00,$00

	ORG	RBMA + $0700 + $12

	DC.B	$00,$0A,$AA,$2A,$00,$00

	ORG	RBMA + $0800 + $12

	DC.B	$00,$02,$AA,$28,$00,$00

	ORG	RBMA + $0900 + $12

	DC.B	$00,$02,$AA,$A0,$00,$00

	ORG	RBMA + $0A00 + $12

	DC.B	$00,$2A,$AA,$A8,$00,$00

	ORG	RBMA + $0B00 + $12

	DC.B	$0A,$AA,$AA,$AA,$3C,$01

	ORG	RBMA + $0C00 + $12

	DC.B	$0A,$AA,$AA,$AA,$FF,$D5

	ORG	RBMA + $0D00 + $12

	DC.B	$00,$0A,$AA,$AA,$C3,$D5

	ORG	RBMA + $0E00 + $12

	DC.B	$00,$02,$AA,$A8,$00,$D4

	ORG	RBMA + $0F00 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	.END
