; FRAME # 1  BLDR1 /SPR

	ORG	RBMA + $0000

	DC.B	$00,$AA,$AA

	ORG	RBMA + $0100

	DC.B	$0A,$AA,$AA

	ORG	RBMA + $0200

	DC.B	$2A,$A6,$6A

	ORG	RBMA + $0300

	DC.B	$AA,$AA,$99

	ORG	RBMA + $0400

	DC.B	$99,$AA,$6A

	ORG	RBMA + $0500

	DC.B	$A6,$65,$9A

	ORG	RBMA + $0600

	DC.B	$99,$9A,$6A

	ORG	RBMA + $0700

	DC.B	$2A,$A9,$AA

	ORG	RBMA + $0800

	DC.B	$2A,$A6,$6A

	ORG	RBMA + $0900

	DC.B	$29,$99,$9A

	ORG	RBMA + $0A00

	DC.B	$06,$66,$6A

	ORG	RBMA + $0B00

	DC.B	$09,$99,$AA

	ORG	RBMA + $0C00

	DC.B	$00,$26,$99

	ORG	RBMA + $0D00

	DC.B	$00,$0A,$A6

	ORG	RBMA + $0E00

	DC.B	$00,$0A,$99

	ORG	RBMA + $0F00

	DC.B	$00,$02,$66

	ORG	RBMA + $1000

	DC.B	$00,$00,$00

	ORG	RBMA + $1100

	DC.B	$00,$00,$00

	ORG	RBMA + $1200

	DC.B	$00,$00,$00

	ORG	RBMA + $1300

	DC.B	$00,$00,$00

	ORG	RBMA + $1400

	DC.B	$00,$00,$00

	ORG	RBMA + $1500

	DC.B	$00,$00,$00

	ORG	RBMA + $1600

	DC.B	$00,$00,$00

	ORG	RBMA + $1700

	DC.B	$00,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00

	ORG	RBMA + $2000

	DC.B	$00,$00,$00

	ORG	RBMA + $2100

	DC.B	$00,$00,$00

	ORG	RBMA + $2200

	DC.B	$00,$00,$00

	ORG	RBMA + $2300

	DC.B	$00,$00,$00

	ORG	RBMA + $2400

	DC.B	$00,$00,$00

	ORG	RBMA + $2500

	DC.B	$00,$00,$00

	ORG	RBMA + $2600

	DC.B	$00,$00,$00

	ORG	RBMA + $2700

	DC.B	$00,$00,$00

	ORG	RBMA + $2800

	DC.B	$00,$00,$00

	ORG	RBMA + $2900

	DC.B	$00,$00,$00

	ORG	RBMA + $2A00

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00

	DC.B	$00,$00,$00

; FRAME # 2  BLDR1 /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$AA,$AA,$00

	ORG	RBMA + $0100 + $03

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0200 + $03

	DC.B	$AA,$AA,$AA

	ORG	RBMA + $0300 + $03

	DC.B	$9A,$AA,$AA

	ORG	RBMA + $0400 + $03

	DC.B	$66,$6A,$66

	ORG	RBMA + $0500 + $03

	DC.B	$AA,$99,$9A

	ORG	RBMA + $0600 + $03

	DC.B	$AA,$A6,$6A

	ORG	RBMA + $0700 + $03

	DC.B	$AA,$99,$9A

	ORG	RBMA + $0800 + $03

	DC.B	$A6,$6A,$A8

	ORG	RBMA + $0900 + $03

	DC.B	$A9,$9A,$A0

	ORG	RBMA + $0A00 + $03

	DC.B	$66,$A6,$80

	ORG	RBMA + $0B00 + $03

	DC.B	$9A,$99,$80

	ORG	RBMA + $0C00 + $03

	DC.B	$66,$A6,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$9A,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$64,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  BLDR1 /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$2A

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$AA

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$AA

	ORG	RBMA + $0300 + $06

	DC.B	$00,$02,$AA

	ORG	RBMA + $0400 + $06

	DC.B	$00,$02,$AA

	ORG	RBMA + $0500 + $06

	DC.B	$00,$02,$AA

	ORG	RBMA + $0600 + $06

	DC.B	$00,$02,$AA

	ORG	RBMA + $0700 + $06

	DC.B	$00,$0A,$AA

	ORG	RBMA + $0800 + $06

	DC.B	$00,$0A,$AA

	ORG	RBMA + $0900 + $06

	DC.B	$00,$0A,$AA

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$0A,$AA

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$0A,$AA

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$0A,$AA

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$2A,$AA

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$2A,$AA

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$2A,$AA

	ORG	RBMA + $1000 + $06

	DC.B	$00,$2A,$AA

	ORG	RBMA + $1100 + $06

	DC.B	$00,$2A,$AA

	ORG	RBMA + $1200 + $06

	DC.B	$00,$2A,$9A

	ORG	RBMA + $1300 + $06

	DC.B	$00,$2A,$AA

	ORG	RBMA + $1400 + $06

	DC.B	$00,$2A,$9A

	ORG	RBMA + $1500 + $06

	DC.B	$00,$2A,$6A

	ORG	RBMA + $1600 + $06

	DC.B	$00,$AA,$AA

	ORG	RBMA + $1700 + $06

	DC.B	$00,$AA,$6A

	ORG	RBMA + $1800 + $06

	DC.B	$00,$A9,$AA

	ORG	RBMA + $1900 + $06

	DC.B	$00,$AA,$6A

	ORG	RBMA + $1A00 + $06

	DC.B	$00,$A9,$AA

	ORG	RBMA + $1B00 + $06

	DC.B	$00,$AA,$6A

	ORG	RBMA + $1C00 + $06

	DC.B	$00,$AA,$AA

	ORG	RBMA + $1D00 + $06

	DC.B	$00,$AA,$6A

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$AA,$AA

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$AA,$9A

	ORG	RBMA + $2000 + $06

	DC.B	$00,$A9,$A6

	ORG	RBMA + $2100 + $06

	DC.B	$00,$2A,$A9

	ORG	RBMA + $2200 + $06

	DC.B	$00,$29,$9A

	ORG	RBMA + $2300 + $06

	DC.B	$00,$2A,$A9

	ORG	RBMA + $2400 + $06

	DC.B	$00,$2A,$9A

	ORG	RBMA + $2500 + $06

	DC.B	$00,$0A,$6A

	ORG	RBMA + $2600 + $06

	DC.B	$00,$0A,$9A

	ORG	RBMA + $2700 + $06

	DC.B	$00,$0A,$6A

	ORG	RBMA + $2800 + $06

	DC.B	$00,$02,$98

	ORG	RBMA + $2900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  BLDR1 /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$80,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$80,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$A0,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$A8,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$A8,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$AA,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$AA,$00,$00

	ORG	RBMA + $0700 + $09

	DC.B	$AA,$00,$00

	ORG	RBMA + $0800 + $09

	DC.B	$AA,$00,$00

	ORG	RBMA + $0900 + $09

	DC.B	$AA,$00,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$AA,$00,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $1000 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $1100 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $1200 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $1300 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $1400 + $09

	DC.B	$AA,$A0,$00

	ORG	RBMA + $1500 + $09

	DC.B	$AA,$A0,$00

	ORG	RBMA + $1600 + $09

	DC.B	$AA,$A0,$00

	ORG	RBMA + $1700 + $09

	DC.B	$A9,$A0,$00

	ORG	RBMA + $1800 + $09

	DC.B	$AA,$60,$00

	ORG	RBMA + $1900 + $09

	DC.B	$AA,$90,$00

	ORG	RBMA + $1A00 + $09

	DC.B	$AA,$60,$00

	ORG	RBMA + $1B00 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $1C00 + $09

	DC.B	$9A,$80,$00

	ORG	RBMA + $1D00 + $09

	DC.B	$AA,$80,$00

	ORG	RBMA + $1E00 + $09

	DC.B	$9A,$00,$00

	ORG	RBMA + $1F00 + $09

	DC.B	$66,$00,$00

	ORG	RBMA + $2000 + $09

	DC.B	$98,$00,$00

	ORG	RBMA + $2100 + $09

	DC.B	$60,$00,$00

	ORG	RBMA + $2200 + $09

	DC.B	$80,$00,$00

	ORG	RBMA + $2300 + $09

	DC.B	$80,$00,$00

	ORG	RBMA + $2400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2700 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00 + $09

	DC.B	$00,$00,$00

; FRAME # 5  BLDR1 /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$0A

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$2A

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$2A

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $0800 + $0C

	DC.B	$00,$02,$AA

	ORG	RBMA + $0900 + $0C

	DC.B	$00,$02,$AA

	ORG	RBMA + $0A00 + $0C

	DC.B	$00,$02,$AA

	ORG	RBMA + $0B00 + $0C

	DC.B	$00,$02,$AA

	ORG	RBMA + $0C00 + $0C

	DC.B	$00,$02,$AA

	ORG	RBMA + $0D00 + $0C

	DC.B	$00,$02,$AA

	ORG	RBMA + $0E00 + $0C

	DC.B	$00,$02,$AA

	ORG	RBMA + $0F00 + $0C

	DC.B	$00,$02,$AA

	ORG	RBMA + $1000 + $0C

	DC.B	$00,$02,$AA

	ORG	RBMA + $1100 + $0C

	DC.B	$00,$02,$AA

	ORG	RBMA + $1200 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $1300 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $1400 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $1500 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $1600 + $0C

	DC.B	$00,$00,$A9

	ORG	RBMA + $1700 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $1800 + $0C

	DC.B	$00,$00,$A9

	ORG	RBMA + $1900 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $1A00 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $1B00 + $0C

	DC.B	$00,$00,$AA

	ORG	RBMA + $1C00 + $0C

	DC.B	$00,$00,$2A

	ORG	RBMA + $1D00 + $0C

	DC.B	$00,$00,$2A

	ORG	RBMA + $1E00 + $0C

	DC.B	$00,$00,$2A

	ORG	RBMA + $1F00 + $0C

	DC.B	$00,$00,$2A

	ORG	RBMA + $2000 + $0C

	DC.B	$00,$00,$29

	ORG	RBMA + $2100 + $0C

	DC.B	$00,$00,$0A

	ORG	RBMA + $2200 + $0C

	DC.B	$00,$00,$09

	ORG	RBMA + $2300 + $0C

	DC.B	$00,$00,$0A

	ORG	RBMA + $2400 + $0C

	DC.B	$00,$00,$0A

	ORG	RBMA + $2500 + $0C

	DC.B	$00,$00,$02

	ORG	RBMA + $2600 + $0C

	DC.B	$00,$00,$02

	ORG	RBMA + $2700 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2800 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2900 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2A00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00 + $0C

	DC.B	$00,$00,$00

; FRAME # 6  BLDR1 /SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$A0,$00,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$A8,$00,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$A8,$00,$00

	ORG	RBMA + $0300 + $0F

	DC.B	$AA,$00,$00

	ORG	RBMA + $0400 + $0F

	DC.B	$AA,$80,$00

	ORG	RBMA + $0500 + $0F

	DC.B	$AA,$80,$00

	ORG	RBMA + $0600 + $0F

	DC.B	$AA,$A0,$00

	ORG	RBMA + $0700 + $0F

	DC.B	$AA,$A0,$00

	ORG	RBMA + $0800 + $0F

	DC.B	$AA,$A0,$00

	ORG	RBMA + $0900 + $0F

	DC.B	$AA,$A0,$00

	ORG	RBMA + $0A00 + $0F

	DC.B	$AA,$A8,$00

	ORG	RBMA + $0B00 + $0F

	DC.B	$AA,$A8,$00

	ORG	RBMA + $0C00 + $0F

	DC.B	$AA,$A8,$00

	ORG	RBMA + $0D00 + $0F

	DC.B	$AA,$A8,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$AA,$AA,$00

	ORG	RBMA + $0F00 + $0F

	DC.B	$9A,$AA,$00

	ORG	RBMA + $1000 + $0F

	DC.B	$AA,$AA,$00

	ORG	RBMA + $1100 + $0F

	DC.B	$9A,$AA,$80

	ORG	RBMA + $1200 + $0F

	DC.B	$AA,$AA,$80

	ORG	RBMA + $1300 + $0F

	DC.B	$AA,$AA,$80

	ORG	RBMA + $1400 + $0F

	DC.B	$6A,$AA,$80

	ORG	RBMA + $1500 + $0F

	DC.B	$AA,$A9,$80

	ORG	RBMA + $1600 + $0F

	DC.B	$6A,$AA,$40

	ORG	RBMA + $1700 + $0F

	DC.B	$AA,$A9,$80

	ORG	RBMA + $1800 + $0F

	DC.B	$6A,$AA,$80

	ORG	RBMA + $1900 + $0F

	DC.B	$AA,$6A,$00

	ORG	RBMA + $1A00 + $0F

	DC.B	$6A,$AA,$00

	ORG	RBMA + $1B00 + $0F

	DC.B	$AA,$66,$00

	ORG	RBMA + $1C00 + $0F

	DC.B	$6A,$9A,$00

	ORG	RBMA + $1D00 + $0F

	DC.B	$9A,$6A,$00

	ORG	RBMA + $1E00 + $0F

	DC.B	$AA,$98,$00

	ORG	RBMA + $1F00 + $0F

	DC.B	$9A,$68,$00

	ORG	RBMA + $2000 + $0F

	DC.B	$A9,$A0,$00

	ORG	RBMA + $2100 + $0F

	DC.B	$9A,$80,$00

	ORG	RBMA + $2200 + $0F

	DC.B	$AA,$80,$00

	ORG	RBMA + $2300 + $0F

	DC.B	$9A,$80,$00

	ORG	RBMA + $2400 + $0F

	DC.B	$A6,$80,$00

	ORG	RBMA + $2500 + $0F

	DC.B	$9A,$00,$00

	ORG	RBMA + $2600 + $0F

	DC.B	$A6,$00,$00

	ORG	RBMA + $2700 + $0F

	DC.B	$28,$00,$00

	ORG	RBMA + $2800 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2900 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2A00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00 + $0F

	DC.B	$00,$00,$00

	.END
