; FRAME # 1  BOLTS /SPR

	ORG	RBMA + $0000

	DC.B	$01,$00

	ORG	RBMA + $0100

	DC.B	$01,$00

	ORG	RBMA + $0200

	DC.B	$04,$00

	ORG	RBMA + $0300

	DC.B	$04,$00

	ORG	RBMA + $0400

	DC.B	$04,$00

	ORG	RBMA + $0500

	DC.B	$04,$00

	ORG	RBMA + $0600

	DC.B	$10,$00

	ORG	RBMA + $0700

	DC.B	$50,$00

	ORG	RBMA + $0800

	DC.B	$50,$00

	ORG	RBMA + $0900

	DC.B	$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00

; FRAME # 2  BOLTS /SPR

	ORG	RBMA + $0000 + $02

	DC.B	$40,$00

	ORG	RBMA + $0100 + $02

	DC.B	$40,$00

	ORG	RBMA + $0200 + $02

	DC.B	$10,$00

	ORG	RBMA + $0300 + $02

	DC.B	$10,$00

	ORG	RBMA + $0400 + $02

	DC.B	$14,$00

	ORG	RBMA + $0500 + $02

	DC.B	$04,$00

	ORG	RBMA + $0600 + $02

	DC.B	$04,$00

	ORG	RBMA + $0700 + $02

	DC.B	$04,$00

	ORG	RBMA + $0800 + $02

	DC.B	$04,$00

	ORG	RBMA + $0900 + $02

	DC.B	$01,$00

	ORG	RBMA + $0A00 + $02

	DC.B	$01,$40

	ORG	RBMA + $0B00 + $02

	DC.B	$01,$40

	ORG	RBMA + $0C00 + $02

	DC.B	$00,$40

	ORG	RBMA + $0D00 + $02

	DC.B	$00,$40

	ORG	RBMA + $0E00 + $02

	DC.B	$00,$50

	ORG	RBMA + $0F00 + $02

	DC.B	$00,$10

; FRAME # 3  BOLTS /SPR

	ORG	RBMA + $0000 + $04

	DC.B	$10,$00

	ORG	RBMA + $0100 + $04

	DC.B	$10,$00

	ORG	RBMA + $0200 + $04

	DC.B	$10,$00

	ORG	RBMA + $0300 + $04

	DC.B	$40,$00

	ORG	RBMA + $0400 + $04

	DC.B	$40,$00

	ORG	RBMA + $0500 + $04

	DC.B	$10,$00

	ORG	RBMA + $0600 + $04

	DC.B	$14,$00

	ORG	RBMA + $0700 + $04

	DC.B	$50,$00

	ORG	RBMA + $0800 + $04

	DC.B	$40,$00

	ORG	RBMA + $0900 + $04

	DC.B	$10,$00

	ORG	RBMA + $0A00 + $04

	DC.B	$14,$00

	ORG	RBMA + $0B00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $04

	DC.B	$00,$00

	.END
