	ORG	RBMA + $0000

	DC.B	$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB
	DC.B	$BB,$BB,$BB,$BB

	ORG	RBMA + $0100

	DC.B	$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE
	DC.B	$EE,$EE,$EE,$EE

	ORG	RBMA + $0200

	DC.B	$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB
	DC.B	$BB,$BB,$BB,$BB

	ORG	RBMA + $0300

	DC.B	$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE
	DC.B	$EE,$EE,$EE,$EE

	ORG	RBMA + $0400

	DC.B	$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB
	DC.B	$BB,$BB,$BB,$BB

	ORG	RBMA + $0500

	DC.B	$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE
	DC.B	$EE,$EE,$EE,$EE

	ORG	RBMA + $0600

	DC.B	$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB
	DC.B	$BB,$BB,$BB,$BB

	ORG	RBMA + $0700

	DC.B	$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE
	DC.B	$EE,$EE,$EE,$EE

	ORG	RBMA + $0800

	DC.B	$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB
	DC.B	$BB,$BB,$BB,$BB

	ORG	RBMA + $0900

	DC.B	$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE
	DC.B	$EE,$EE,$EE,$EE

	ORG	RBMA + $0A00

	DC.B	$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB
	DC.B	$BB,$BB,$BB,$BB

	ORG	RBMA + $0B00

	DC.B	$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE
	DC.B	$EE,$EE,$EE,$EE

	ORG	RBMA + $0C00

	DC.B	$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB
	DC.B	$BB,$BB,$BB,$BB

	ORG	RBMA + $0D00

	DC.B	$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE
	DC.B	$EE,$EE,$EE,$EE

	ORG	RBMA + $0E00

	DC.B	$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB,$BB
	DC.B	$BB,$BB,$BB,$BB

	ORG	RBMA + $0F00

	DC.B	$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE,$EE
	DC.B	$EE,$EE,$EE,$EE

	.END
