	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00,$0A,$BF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00,$0A,$AF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00,$0A,$AF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$0A,$AF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$02,$AF,$FF,$00,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$02,$AF,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0000 + $0A

	DC.B	$00,$00,$00,$02,$AF,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0100 + $0A

	DC.B	$00,$00,$00,$02,$AF,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0200 + $0A

	DC.B	$00,$00,$00,$02,$AF,$FF,$F0,$00,$00,$00

	ORG	RBMA + $0300 + $0A

	DC.B	$00,$00,$00,$02,$AF,$FF,$F0,$00,$00,$00

	ORG	RBMA + $0400 + $0A

	DC.B	$00,$00,$00,$02,$AF,$FF,$F0,$00,$00,$00

	ORG	RBMA + $0500 + $0A

	DC.B	$00,$00,$00,$02,$AF,$FF,$FC,$00,$00,$00

	ORG	RBMA + $0600 + $0A

	DC.B	$00,$00,$00,$02,$AF,$FF,$FF,$00,$00,$00

	ORG	RBMA + $0700 + $0A

	DC.B	$00,$00,$00,$0E,$AF,$FF,$FF,$00,$00,$00

	ORG	RBMA + $0800 + $0A

	DC.B	$00,$00,$03,$FE,$AF,$FF,$FF,$F0,$00,$00

	ORG	RBMA + $0900 + $0A

	DC.B	$00,$00,$0F,$FE,$AF,$FF,$FF,$FF,$C0,$00

	ORG	RBMA + $0A00 + $0A

	DC.B	$00,$00,$3F,$FE,$AF,$FF,$FF,$FF,$F0,$00

	ORG	RBMA + $0B00 + $0A

	DC.B	$00,$00,$FF,$FE,$AF,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $0C00 + $0A

	DC.B	$00,$03,$FF,$FE,$AF,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $0D00 + $0A

	DC.B	$00,$03,$FF,$FE,$AF,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $0E00 + $0A

	DC.B	$00,$0F,$FF,$FE,$AB,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $0F00 + $0A

	DC.B	$00,$2F,$FF,$FE,$AB,$FF,$CF,$FF,$FF,$00

	ORG	RBMA + $0000 + $14

	DC.B	$00,$2F,$FF,$FE,$AB,$FF,$C0,$FF,$FF,$00

	ORG	RBMA + $0100 + $14

	DC.B	$00,$AF,$FF,$FE,$AB,$FF,$C0,$3F,$FF,$00

	ORG	RBMA + $0200 + $14

	DC.B	$02,$AF,$FF,$FE,$AB,$FF,$C0,$0F,$FF,$00

	ORG	RBMA + $0300 + $14

	DC.B	$0A,$AF,$FF,$FE,$AB,$FF,$C0,$0F,$FF,$C0

	ORG	RBMA + $0400 + $14

	DC.B	$0A,$AF,$FF,$F0,$AB,$FF,$C0,$0F,$FF,$C0

	ORG	RBMA + $0500 + $14

	DC.B	$0A,$AF,$FF,$00,$AB,$FF,$C0,$03,$FF,$C0

	ORG	RBMA + $0600 + $14

	DC.B	$0A,$AF,$FC,$00,$AB,$FF,$C0,$03,$FF,$C0

	ORG	RBMA + $0700 + $14

	DC.B	$2A,$BF,$FC,$00,$AB,$FF,$C0,$03,$FF,$C0

	ORG	RBMA + $0800 + $14

	DC.B	$2A,$BF,$F0,$00,$AB,$FF,$C0,$00,$FF,$C0

	ORG	RBMA + $0900 + $14

	DC.B	$2A,$BF,$F0,$00,$AB,$FF,$C0,$00,$FF,$C0

	ORG	RBMA + $0A00 + $14

	DC.B	$2A,$BF,$F0,$00,$AB,$FF,$C0,$00,$FF,$C0

	ORG	RBMA + $0B00 + $14

	DC.B	$2A,$BF,$F0,$00,$AB,$FF,$C0,$00,$FF,$C0

	ORG	RBMA + $0C00 + $14

	DC.B	$2A,$BF,$C0,$00,$AB,$FF,$C0,$00,$3F,$C0

	ORG	RBMA + $0D00 + $14

	DC.B	$2A,$BF,$C0,$00,$AB,$FF,$C0,$00,$3F,$C0

	ORG	RBMA + $0E00 + $14

	DC.B	$2A,$FF,$00,$00,$AB,$FF,$C0,$00,$3F,$C0

	ORG	RBMA + $0F00 + $14

	DC.B	$AA,$FF,$00,$00,$AB,$FF,$C0,$00,$0F,$00

	ORG	RBMA + $0000 + $1E

	DC.B	$AA,$FF,$00,$00,$AB,$FF,$C0,$00,$0C,$00

	ORG	RBMA + $0100 + $1E

	DC.B	$AA,$FF,$00,$00,$AB,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0200 + $1E

	DC.B	$AA,$FC,$00,$00,$AB,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0300 + $1E

	DC.B	$AA,$FC,$00,$00,$AB,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0400 + $1E

	DC.B	$AA,$FC,$00,$00,$AB,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0500 + $1E

	DC.B	$AA,$FC,$00,$00,$AB,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0600 + $1E

	DC.B	$2A,$FC,$00,$00,$AB,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0700 + $1E

	DC.B	$2A,$FC,$00,$00,$2B,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0800 + $1E

	DC.B	$2A,$F0,$00,$00,$2A,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0900 + $1E

	DC.B	$2A,$F0,$00,$00,$2A,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0A00 + $1E

	DC.B	$2A,$F0,$00,$00,$2A,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0B00 + $1E

	DC.B	$2A,$80,$00,$00,$2A,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0C00 + $1E

	DC.B	$0A,$00,$00,$00,$2A,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0D00 + $1E

	DC.B	$00,$00,$00,$00,$2A,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0E00 + $1E

	DC.B	$00,$00,$00,$00,$2A,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0F00 + $1E

	DC.B	$00,$00,$00,$00,$2A,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0000 + $28

	DC.B	$00,$00,$00,$00,$2A,$FF,$C0,$00,$00,$00

	ORG	RBMA + $0100 + $28

	DC.B	$00,$00,$00,$00,$0A,$BF,$C0,$00,$00,$00

	ORG	RBMA + $0200 + $28

	DC.B	$00,$00,$00,$00,$0A,$BF,$C0,$00,$00,$00

	ORG	RBMA + $0300 + $28

	DC.B	$00,$00,$00,$00,$0A,$BF,$C0,$00,$00,$00

	ORG	RBMA + $0400 + $28

	DC.B	$00,$00,$00,$00,$0A,$BF,$C0,$00,$00,$00

	ORG	RBMA + $0500 + $28

	DC.B	$00,$00,$00,$00,$0A,$BF,$C0,$00,$00,$00

	ORG	RBMA + $0600 + $28

	DC.B	$00,$00,$00,$00,$02,$BF,$C0,$00,$00,$00

	ORG	RBMA + $0700 + $28

	DC.B	$00,$00,$00,$00,$02,$BF,$C0,$00,$00,$00

	ORG	RBMA + $0800 + $28

	DC.B	$00,$00,$00,$00,$02,$BF,$C0,$00,$00,$00

	ORG	RBMA + $0900 + $28

	DC.B	$00,$00,$00,$00,$02,$BF,$00,$00,$00,$00

	ORG	RBMA + $0A00 + $28

	DC.B	$00,$00,$00,$00,$02,$BF,$00,$00,$00,$00

	ORG	RBMA + $0B00 + $28

	DC.B	$00,$00,$00,$00,$02,$BF,$00,$00,$00,$00

	ORG	RBMA + $0C00 + $28

	DC.B	$00,$00,$00,$00,$02,$BF,$00,$00,$00,$00

	ORG	RBMA + $0D00 + $28

	DC.B	$00,$00,$00,$00,$02,$BC,$00,$00,$00,$00

	ORG	RBMA + $0E00 + $28

	DC.B	$00,$00,$00,$00,$02,$BC,$00,$00,$00,$00

	ORG	RBMA + $0F00 + $28

	DC.B	$00,$00,$00,$00,$00,$A0,$00,$00,$00,$00

	.END
