	ORG	RBMA + $0000

	DC.B	$0F,$EC,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$03,$EC,$00,$00
	DC.B	$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$0F,$BB,$00,$00
	DC.B	$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$3F,$EE,$C0,$00
	DC.B	$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$FF,$BB,$B0,$00
	DC.B	$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$03,$FF,$EE,$EC,$00
	DC.B	$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$0F,$FF,$BB,$BB,$00
	DC.B	$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$3F,$FF,$EE,$EE,$C0
	DC.B	$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$BB,$BB,$B0
	DC.B	$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$03,$FF,$FE,$EE,$EE,$EC
	DC.B	$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$0F,$FF,$FF,$BB,$BB,$BB
	DC.B	$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$3F,$FF,$FE,$EE,$EE,$EE
	DC.B	$C0,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$3F,$FF,$FF,$BB,$BB,$BB
	DC.B	$B0,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EC,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$03,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$0F,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$C0

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$3F,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$B0

	ORG	RBMA + $1000

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EC

	ORG	RBMA + $1100

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$03,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1200

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$0F,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1300

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$3F,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1400

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1500

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1600

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1700

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1800

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$EE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1900

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$BB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$EE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$9B,$B5,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FD,$55,$55,$6E,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$55,$55,$55,$5B,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$F5,$55,$55,$55,$56,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$57,$55,$65,$55,$55,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0000 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$D7,$FE,$56,$55,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0100 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0200 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0300 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0400 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0500 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0600 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0700 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0800 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0900 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0A00 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0B00 + $12

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0C00 + $12

	DC.B	$00,$00,$25,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0D00 + $12

	DC.B	$00,$00,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0E00 + $12

	DC.B	$00,$03,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0F00 + $12

	DC.B	$00,$0F,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1000 + $12

	DC.B	$00,$0F,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1100 + $12

	DC.B	$00,$3F,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1200 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1300 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1400 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1500 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1600 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1700 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1800 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1900 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1A00 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1B00 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1C00 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1D00 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1E00 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1F00 + $12

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0000 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0100 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0200 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$D6,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0300 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$57,$FF,$55,$7B,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0400 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$55,$55,$55,$55,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0500 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FD,$55,$55,$55,$55,$7B
	DC.B	$BB,$BB

	ORG	RBMA + $0600 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$57,$F5,$7D,$56,$55,$6E
	DC.B	$EE,$EE

	ORG	RBMA + $0700 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FD,$BB,$97,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0800 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0900 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0A00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0B00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0C00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0D00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0E00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0F00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1000 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1100 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1200 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1300 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1400 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1500 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1600 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1700 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1800 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1900 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1A00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1B00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1C00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1D00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1E00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1F00 + $24

	DC.B	$00,$FF,$E5,$55,$55,$55,$55,$55,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0000 + $36

	DC.B	$00,$FF,$FF,$FF,$FF,$FD,$55,$55,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0100 + $36

	DC.B	$00,$FF,$FF,$FF,$FF,$FF,$FF,$F5,$FF,$FF,$FF,$FF,$FB,$97,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0200 + $36

	DC.B	$00,$FF,$D5,$EF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$D5,$56,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0300 + $36

	DC.B	$00,$FF,$F5,$E5,$79,$5E,$FF,$FF,$FF,$FF,$FF,$FF,$D5,$55,$B9,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0400 + $36

	DC.B	$00,$FF,$F5,$E5,$79,$5E,$57,$FF,$FF,$FF,$F7,$FD,$55,$55,$56,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0500 + $36

	DC.B	$00,$FF,$F5,$E5,$79,$5E,$57,$97,$FF,$FF,$F5,$55,$59,$97,$5B,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0600 + $36

	DC.B	$00,$FF,$FD,$E5,$79,$5E,$57,$97,$FF,$FF,$FF,$55,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0700 + $36

	DC.B	$00,$FF,$FD,$E5,$79,$5E,$57,$97,$FF,$FF,$FF,$D7,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0800 + $36

	DC.B	$00,$FF,$FF,$E5,$79,$5E,$57,$97,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0900 + $36

	DC.B	$00,$FF,$FF,$E5,$79,$5E,$57,$9F,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0A00 + $36

	DC.B	$00,$FF,$FF,$E5,$79,$5E,$57,$9F,$FF,$FF,$FF,$FF,$FF,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0B00 + $36

	DC.B	$00,$FF,$FF,$F5,$79,$5E,$57,$BF,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0C00 + $36

	DC.B	$00,$FF,$FF,$FD,$79,$5E,$57,$FF,$FF,$FF,$FF,$FF,$FF,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0D00 + $36

	DC.B	$00,$FF,$FF,$FF,$F9,$5E,$57,$FF,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0E00 + $36

	DC.B	$00,$FF,$FF,$FF,$FD,$5E,$7F,$FF,$FF,$FF,$FF,$FF,$FF,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0F00 + $36

	DC.B	$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1000 + $36

	DC.B	$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1100 + $36

	DC.B	$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1200 + $36

	DC.B	$00,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$E5

	ORG	RBMA + $1300 + $36

	DC.B	$00,$5F,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$BB,$95

	ORG	RBMA + $1400 + $36

	DC.B	$00,$55,$7F,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$55

	ORG	RBMA + $1500 + $36

	DC.B	$00,$55,$55,$7F,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$BB
	DC.B	$B5,$56

	ORG	RBMA + $1600 + $36

	DC.B	$00,$D5,$55,$55,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$D5,$5B

	ORG	RBMA + $1700 + $36

	DC.B	$00,$FF,$55,$55,$57,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$B9
	DC.B	$55,$6E

	ORG	RBMA + $1800 + $36

	DC.B	$00,$FF,$FD,$55,$55,$5F,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$E5
	DC.B	$55,$BB

	ORG	RBMA + $1900 + $36

	DC.B	$00,$FF,$FF,$F5,$55,$55,$7F,$FF,$FF,$FF,$FF,$FF,$FB,$BB,$BB,$55
	DC.B	$5E,$EE

	ORG	RBMA + $1A00 + $36

	DC.B	$00,$FF,$FF,$FF,$D5,$55,$55,$7F,$FF,$FF,$FF,$FF,$FE,$EE,$ED,$55
	DC.B	$7B,$BB

	ORG	RBMA + $1B00 + $36

	DC.B	$00,$FF,$FF,$FF,$FF,$55,$55,$55,$FF,$FF,$FF,$FF,$FB,$BB,$95,$55
	DC.B	$EE,$EE

	ORG	RBMA + $1C00 + $36

	DC.B	$03,$FF,$FF,$FF,$FF,$FD,$55,$55,$57,$FF,$FF,$FF,$FE,$EE,$55,$5B
	DC.B	$BB,$BB

	ORG	RBMA + $1D00 + $36

	DC.B	$0F,$FF,$FF,$FF,$FF,$FF,$D5,$55,$55,$5F,$FF,$FF,$FB,$B9,$55,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $1E00 + $36

	DC.B	$3F,$FF,$FF,$FF,$FF,$FF,$FF,$55,$55,$55,$5F,$FF,$FE,$D5,$57,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $1F00 + $36

	DC.B	$3F,$FF,$FF,$FF,$FF,$FF,$FF,$FD,$55,$55,$55,$7F,$FB,$55,$6E,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0000 + $48

	DC.B	$3F,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$F5,$55,$55,$55,$FD,$55,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0100 + $48

	DC.B	$3F,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$D5,$55,$55,$55,$56,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0200 + $48

	DC.B	$3F,$DF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$55,$55,$55,$7B,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0300 + $48

	DC.B	$3F,$DF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FD,$55,$55,$EE,$EE,$EE
	DC.B	$EE,$EE

	ORG	RBMA + $0400 + $48

	DC.B	$3F,$DF,$F7,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$F5,$57,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0500 + $48

	DC.B	$3F,$DF,$F7,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FE,$EE,$EE,$EE
	DC.B	$EE,$FE

	ORG	RBMA + $0600 + $48

	DC.B	$3F,$DF,$F7,$FD,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$F5,$57,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0700 + $48

	DC.B	$3F,$DF,$F7,$FD,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$D5,$56,$EE,$EE,$EE
	DC.B	$FE,$FE

	ORG	RBMA + $0800 + $48

	DC.B	$03,$DF,$F7,$FD,$FF,$7F,$FF,$FF,$FF,$FF,$FF,$D5,$57,$BB,$BB,$BB
	DC.B	$BB,$BB

	ORG	RBMA + $0900 + $48

	DC.B	$00,$0F,$F7,$FD,$FF,$7F,$FF,$FF,$FF,$FF,$FF,$D5,$56,$EE,$EE,$EE
	DC.B	$FE,$FF

	ORG	RBMA + $0A00 + $48

	DC.B	$00,$00,$F7,$FD,$FF,$7F,$DF,$FF,$FF,$FF,$FF,$D5,$57,$BB,$BB,$BB
	DC.B	$BB,$BE

	ORG	RBMA + $0B00 + $48

	DC.B	$00,$00,$03,$FD,$FF,$7F,$DF,$FF,$FF,$FF,$FF,$77,$DD,$EE,$EE,$FE
	DC.B	$FE,$FA

	ORG	RBMA + $0C00 + $48

	DC.B	$00,$00,$00,$3D,$FF,$7F,$DF,$F7,$FF,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$BB,$EA

	ORG	RBMA + $0D00 + $48

	DC.B	$00,$00,$00,$0A,$FF,$7F,$DF,$F7,$FF,$FF,$FF,$FF,$FF,$EE,$FE,$FE
	DC.B	$FE,$AA

	ORG	RBMA + $0E00 + $48

	DC.B	$00,$00,$00,$0A,$AF,$7F,$DF,$F7,$FD,$FF,$FF,$FF,$FF,$BB,$BB,$BB
	DC.B	$FA,$AA

	ORG	RBMA + $0F00 + $48

	DC.B	$00,$00,$00,$0A,$AA,$BF,$DF,$F7,$FD,$FF,$FD,$7F,$FD,$EE,$FE,$FF
	DC.B	$EA,$AA

	ORG	RBMA + $1000 + $48

	DC.B	$00,$00,$00,$0A,$AA,$AB,$DF,$F7,$FD,$FF,$7D,$57,$F5,$BB,$BB,$BF
	DC.B	$AA,$AA

	ORG	RBMA + $1100 + $48

	DC.B	$00,$00,$00,$0A,$AA,$AA,$AF,$F7,$FD,$FF,$7D,$55,$55,$EE,$FE,$FA
	DC.B	$AA,$AA

	ORG	RBMA + $1200 + $48

	DC.B	$00,$00,$00,$0A,$AA,$AA,$AA,$F7,$FD,$FF,$7D,$55,$55,$BB,$BB,$AA
	DC.B	$AA,$AA

	ORG	RBMA + $1300 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AB,$FD,$FF,$7D,$55,$55,$EE,$FE,$AA
	DC.B	$AA,$AA

	ORG	RBMA + $1400 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$BD,$FF,$7F,$55,$55,$BB,$EA,$AA
	DC.B	$AA,$AA

	ORG	RBMA + $1500 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$FF,$7F,$55,$55,$EF,$AA,$AA
	DC.B	$AA,$AA

	ORG	RBMA + $1600 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AF,$7F,$D5,$57,$BE,$AA,$AA
	DC.B	$AA,$AA

	ORG	RBMA + $1700 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$BF,$F5,$5F,$FA,$AA,$AA
	DC.B	$AA,$AA

	ORG	RBMA + $1800 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$AB,$FF,$FF,$EA,$AA,$AA
	DC.B	$AA,$AA

	ORG	RBMA + $1900 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$A9,$FF,$FF,$6A,$AA,$AA
	DC.B	$AA,$AA

	ORG	RBMA + $1A00 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$A9,$7F,$FD,$6A,$AA,$AA
	DC.B	$AB,$EA

	ORG	RBMA + $1B00 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$A9,$5F,$F5,$6A,$AA,$AA
	DC.B	$AB,$FF

	ORG	RBMA + $1C00 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$A9,$55,$55,$6A,$AA,$AA
	DC.B	$AB,$FF

	ORG	RBMA + $1D00 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$A9,$55,$55,$6A,$AA,$AA
	DC.B	$AB,$FF

	ORG	RBMA + $1E00 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$A9,$55,$55,$6A,$AA,$AA
	DC.B	$A9,$7F

	ORG	RBMA + $1F00 + $48

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$A9,$55,$55,$6A,$AA,$BA
	DC.B	$AD,$55

	ORG	RBMA + $0000 + $5A

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$A9,$55,$55,$6A,$AA,$FA
	DC.B	$BD,$55

	ORG	RBMA + $0100 + $5A

	DC.B	$00,$00,$00,$0A,$A9,$AA,$AA,$AA,$AA,$AA,$A9,$55,$55,$6A,$AA,$FA
	DC.B	$BD,$55

	ORG	RBMA + $0200 + $5A

	DC.B	$00,$00,$00,$0A,$AA,$AA,$AA,$AA,$AA,$AA,$A9,$55,$55,$6A,$AB,$FA
	DC.B	$FD,$55

	ORG	RBMA + $0300 + $5A

	DC.B	$00,$00,$00,$0A,$AA,$AA,$BE,$BA,$AA,$AA,$A9,$55,$55,$6A,$AB,$FA
	DC.B	$F5,$55

	ORG	RBMA + $0400 + $5A

	DC.B	$00,$00,$00,$0F,$AA,$AA,$FF,$BE,$AA,$AA,$A9,$55,$55,$6A,$AB,$FB
	DC.B	$D5,$55

	ORG	RBMA + $0500 + $5A

	DC.B	$00,$00,$00,$0F,$FF,$FF,$FF,$BF,$AA,$AA,$A9,$55,$55,$6A,$AB,$FF
	DC.B	$D1,$55

	ORG	RBMA + $0600 + $5A

	DC.B	$00,$00,$00,$0F,$FF,$FF,$FF,$BF,$AA,$AA,$A9,$55,$55,$6B,$AB,$FF
	DC.B	$51,$55

	ORG	RBMA + $0700 + $5A

	DC.B	$00,$00,$00,$0F,$FF,$FF,$DF,$FF,$AB,$AA,$A9,$55,$55,$7F,$AB,$FF
	DC.B	$50,$55

	ORG	RBMA + $0800 + $5A

	DC.B	$00,$00,$00,$15,$FF,$FF,$55,$FF,$AB,$FA,$A9,$65,$59,$7F,$AB,$FD
	DC.B	$50,$55

	ORG	RBMA + $0900 + $5A

	DC.B	$00,$00,$00,$15,$55,$55,$55,$FF,$AB,$FA,$BD,$65,$59,$7F,$AB,$FD
	DC.B	$50,$55

	ORG	RBMA + $0A00 + $5A

	DC.B	$00,$00,$00,$05,$55,$55,$45,$FF,$AB,$FA,$BD,$65,$59,$7F,$AB,$F5
	DC.B	$50,$15

	ORG	RBMA + $0B00 + $5A

	DC.B	$00,$00,$00,$05,$55,$55,$45,$7F,$AB,$FA,$BD,$65,$59,$7F,$AF,$F5
	DC.B	$50,$15

	ORG	RBMA + $0C00 + $5A

	DC.B	$00,$00,$00,$05,$55,$55,$45,$7F,$EB,$FA,$BF,$65,$59,$BF,$BF,$D5
	DC.B	$40,$15

	ORG	RBMA + $0D00 + $5A

	DC.B	$00,$00,$00,$01,$55,$55,$05,$5F,$FF,$FA,$BF,$A5,$5A,$BF,$FF,$55
	DC.B	$40,$05

	ORG	RBMA + $0E00 + $5A

	DC.B	$00,$00,$00,$01,$55,$55,$05,$57,$FF,$EA,$BF,$A9,$7A,$BF,$FD,$55
	DC.B	$40,$05

	ORG	RBMA + $0F00 + $5A

	DC.B	$00,$00,$00,$01,$55,$55,$05,$55,$FF,$FE,$BF,$AB,$FB,$FF,$F5,$55
	DC.B	$00,$05

	ORG	RBMA + $1000 + $5A

	DC.B	$00,$00,$00,$01,$55,$55,$01,$55,$7F,$FF,$FF,$AB,$FF,$FF,$D5,$55
	DC.B	$00,$01

	ORG	RBMA + $1100 + $5A

	DC.B	$00,$00,$00,$00,$55,$54,$01,$55,$57,$FF,$FF,$FF,$FF,$FD,$55,$54
	DC.B	$00,$01

	ORG	RBMA + $1200 + $5A

	DC.B	$00,$00,$00,$00,$55,$54,$01,$55,$55,$7F,$FF,$FF,$FF,$D5,$55,$54
	DC.B	$00,$01

	ORG	RBMA + $1300 + $5A

	DC.B	$00,$00,$00,$00,$55,$54,$00,$55,$55,$57,$FF,$FF,$FD,$55,$55,$54
	DC.B	$00,$00

	ORG	RBMA + $1400 + $5A

	DC.B	$00,$00,$00,$00,$55,$54,$00,$55,$55,$55,$5F,$FF,$55,$55,$55,$50
	DC.B	$00,$00

	ORG	RBMA + $1500 + $5A

	DC.B	$00,$00,$00,$00,$15,$50,$00,$15,$55,$55,$55,$55,$55,$55,$55,$50
	DC.B	$00,$00

	ORG	RBMA + $1600 + $5A

	DC.B	$00,$00,$00,$00,$15,$50,$00,$15,$55,$55,$55,$55,$55,$55,$55,$40
	DC.B	$00,$00

	ORG	RBMA + $1700 + $5A

	DC.B	$00,$00,$00,$00,$15,$50,$00,$05,$55,$55,$55,$55,$55,$55,$55,$40
	DC.B	$00,$00

	ORG	RBMA + $1800 + $5A

	DC.B	$00,$00,$00,$00,$05,$40,$00,$05,$55,$55,$55,$55,$55,$55,$55,$00
	DC.B	$00,$00

	ORG	RBMA + $1900 + $5A

	DC.B	$00,$00,$00,$00,$05,$40,$00,$01,$55,$55,$55,$55,$55,$55,$54,$00
	DC.B	$00,$00

	ORG	RBMA + $1A00 + $5A

	DC.B	$00,$00,$00,$00,$05,$40,$00,$00,$55,$55,$55,$55,$55,$55,$50,$00
	DC.B	$00,$00

	ORG	RBMA + $1B00 + $5A

	DC.B	$00,$00,$00,$00,$01,$00,$00,$00,$15,$55,$55,$55,$55,$55,$40,$00
	DC.B	$00,$00

	ORG	RBMA + $1C00 + $5A

	DC.B	$00,$00,$00,$00,$01,$00,$00,$00,$05,$55,$55,$55,$55,$55,$00,$00
	DC.B	$00,$00

	ORG	RBMA + $1D00 + $5A

	DC.B	$00,$00,$00,$00,$01,$00,$00,$00,$01,$55,$55,$55,$55,$54,$00,$00
	DC.B	$00,$00

	ORG	RBMA + $1E00 + $5A

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$55,$55,$55,$55,$50,$00,$00
	DC.B	$00,$00

	ORG	RBMA + $1F00 + $5A

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$15,$55,$55,$55,$00,$00,$00
	DC.B	$00,$00

	.END
