; FRAME # 1  CAVET /SPR

	ORG	RBMA + $0000

	DC.B	$0A,$AA,$00

	ORG	RBMA + $0100

	DC.B	$1A,$AA,$00

	ORG	RBMA + $0200

	DC.B	$5A,$AA,$00

	ORG	RBMA + $0300

	DC.B	$5A,$AA,$00

	ORG	RBMA + $0400

	DC.B	$5A,$AA,$00

	ORG	RBMA + $0500

	DC.B	$55,$55,$00

	ORG	RBMA + $0600

	DC.B	$5A,$AA,$00

	ORG	RBMA + $0700

	DC.B	$2A,$A8,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

	.END
