; FRAME # 1  CHAIN /SPR

	ORG	RBMA + $0000

	DC.B	$C0,$00,$00

	ORG	RBMA + $0100

	DC.B	$F0,$00,$00

	ORG	RBMA + $0200

	DC.B	$30,$00,$00

	ORG	RBMA + $0300

	DC.B	$0C,$00,$00

	ORG	RBMA + $0400

	DC.B	$0F,$00,$00

	ORG	RBMA + $0500

	DC.B	$0F,$C0,$00

	ORG	RBMA + $0600

	DC.B	$03,$C0,$00

	ORG	RBMA + $0700

	DC.B	$00,$3C,$00

	ORG	RBMA + $0800

	DC.B	$00,$3F,$C0

	ORG	RBMA + $0900

	DC.B	$00,$0F,$C0

	ORG	RBMA + $0A00

	DC.B	$00,$00,$3F

	ORG	RBMA + $0B00

	DC.B	$00,$00,$0F

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  CHAIN /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$F0,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$FC,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$3C,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$03,$C0,$00

	ORG	RBMA + $0400 + $03

	DC.B	$03,$F0,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$F0,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$0F,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$0F,$C0

	ORG	RBMA + $0800 + $03

	DC.B	$00,$03,$C0

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$3C

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$3F

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$00,$0F

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  CHAIN /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$F0,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$FC,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$03,$F0,$00

	ORG	RBMA + $0300 + $06

	DC.B	$03,$FC,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$3C,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$03,$C0

	ORG	RBMA + $0600 + $06

	DC.B	$00,$03,$F0

	ORG	RBMA + $0700 + $06

	DC.B	$00,$00,$F0

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00,$30

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00,$0C

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00,$0F

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00,$03

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  CHAIN /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$F0,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$FC,$F0,$C0

	ORG	RBMA + $0200 + $09

	DC.B	$30,$C0,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$F0

	ORG	RBMA + $0600 + $09

	DC.B	$0C,$00,$30

	ORG	RBMA + $0700 + $09

	DC.B	$0F,$00,$00

	ORG	RBMA + $0800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $09

	DC.B	$00,$00,$0C

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$C3,$3F

	ORG	RBMA + $0B00 + $09

	DC.B	$00,$03,$CF

	ORG	RBMA + $0C00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

	.END
