; FRAME # 1  CHEST /SPR

	ORG	RBMA + $0000

	DC.B	$02,$AA,$A0

	ORG	RBMA + $0100

	DC.B	$0A,$AA,$A0

	ORG	RBMA + $0200

	DC.B	$0A,$AB,$A0

	ORG	RBMA + $0300

	DC.B	$26,$BA,$60

	ORG	RBMA + $0400

	DC.B	$2B,$A6,$F0

	ORG	RBMA + $0500

	DC.B	$1D,$B6,$E4

	ORG	RBMA + $0600

	DC.B	$27,$5D,$50

	ORG	RBMA + $0700

	DC.B	$15,$55,$14

	ORG	RBMA + $0800

	DC.B	$04,$75,$40

	ORG	RBMA + $0900

	DC.B	$11,$55,$04

	ORG	RBMA + $0A00

	DC.B	$01,$00,$40

	ORG	RBMA + $0B00

	DC.B	$04,$00,$00

	ORG	RBMA + $0C00

	DC.B	$54,$11,$10

	ORG	RBMA + $0D00

	DC.B	$45,$00,$00

	ORG	RBMA + $0E00

	DC.B	$40,$11,$00

	ORG	RBMA + $0F00

	DC.B	$10,$00,$00

; FRAME # 2  CHEST /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$02,$AA,$A0

	ORG	RBMA + $0100 + $03

	DC.B	$0A,$AA,$A0

	ORG	RBMA + $0200 + $03

	DC.B	$0A,$AB,$A0

	ORG	RBMA + $0300 + $03

	DC.B	$26,$BA,$60

	ORG	RBMA + $0400 + $03

	DC.B	$6B,$A6,$F1

	ORG	RBMA + $0500 + $03

	DC.B	$1D,$B6,$E0

	ORG	RBMA + $0600 + $03

	DC.B	$27,$5D,$50

	ORG	RBMA + $0700 + $03

	DC.B	$65,$55,$11

	ORG	RBMA + $0800 + $03

	DC.B	$04,$75,$40

	ORG	RBMA + $0900 + $03

	DC.B	$41,$55,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$01,$00,$04

	ORG	RBMA + $0B00 + $03

	DC.B	$04,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$54,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$45,$11,$04

	ORG	RBMA + $0E00 + $03

	DC.B	$40,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$10,$11,$10

	.END
