	ORG	RBMA + $0000

	DC.B	$3F,$F8,$00

	ORG	RBMA + $0100

	DC.B	$3F,$FE,$00

	ORG	RBMA + $0200

	DC.B	$3F,$FB,$80

	ORG	RBMA + $0300

	DC.B	$3F,$FE,$C0

	ORG	RBMA + $0400

	DC.B	$3F,$FB,$80

	ORG	RBMA + $0500

	DC.B	$3F,$FE,$C0

	ORG	RBMA + $0600

	DC.B	$3F,$FB,$80

	ORG	RBMA + $0700

	DC.B	$3F,$FE,$C0

	ORG	RBMA + $0800

	DC.B	$3F,$FB,$80

	ORG	RBMA + $0900

	DC.B	$3F,$FE,$C0

	ORG	RBMA + $0A00

	DC.B	$3F,$FB,$80

	ORG	RBMA + $0B00

	DC.B	$3F,$FE,$E0

	ORG	RBMA + $0C00

	DC.B	$3F,$FB,$B0

	ORG	RBMA + $0D00

	DC.B	$FF,$FF,$E0

	ORG	RBMA + $0E00

	DC.B	$FF,$FF,$C0

	ORG	RBMA + $0F00

	DC.B	$FF,$FF,$00

	.END
