	ORG	RBMA + $0000

	DC.B	$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$0C

	ORG	RBMA + $0C00

	DC.B	$00,$3C

	ORG	RBMA + $0D00

	DC.B	$00,$3F

	ORG	RBMA + $0E00

	DC.B	$00,$FF

	ORG	RBMA + $0F00

	DC.B	$03,$FF

	ORG	RBMA + $0000 + $02

	DC.B	$0F,$FC

	ORG	RBMA + $0100 + $02

	DC.B	$0F,$F0

	ORG	RBMA + $0200 + $02

	DC.B	$3F,$F0

	ORG	RBMA + $0300 + $02

	DC.B	$3F,$C0

	ORG	RBMA + $0400 + $02

	DC.B	$3F,$C0

	ORG	RBMA + $0500 + $02

	DC.B	$3F,$C0

	ORG	RBMA + $0600 + $02

	DC.B	$3F,$C0

	ORG	RBMA + $0700 + $02

	DC.B	$FF,$F0

	ORG	RBMA + $0800 + $02

	DC.B	$FF,$F0

	ORG	RBMA + $0900 + $02

	DC.B	$FF,$F0

	ORG	RBMA + $0A00 + $02

	DC.B	$3F,$C0

	ORG	RBMA + $0B00 + $02

	DC.B	$3F,$C0

	ORG	RBMA + $0C00 + $02

	DC.B	$3F,$C0

	ORG	RBMA + $0D00 + $02

	DC.B	$0F,$00

	ORG	RBMA + $0E00 + $02

	DC.B	$0F,$00

	ORG	RBMA + $0F00 + $02

	DC.B	$0F,$00

	.END
