	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00,$00,$CC,$C0,$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00,$03,$33,$30,$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00,$CC,$CC,$CC,$C0,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$0F,$FF,$FF,$F3,$33,$33,$30

	ORG	RBMA + $0600

	DC.B	$03,$FF,$FF,$FF,$FF,$FF,$FC,$CC,$CC

	ORG	RBMA + $0700

	DC.B	$3F,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF

	ORG	RBMA + $0800

	DC.B	$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF

	ORG	RBMA + $0900

	DC.B	$3F,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$FC

	ORG	RBMA + $0A00

	DC.B	$03,$FF,$FF,$FF,$FF,$FF,$FF,$FF,$F0

	ORG	RBMA + $0B00

	DC.B	$00,$00,$0F,$FF,$FF,$FF,$FF,$FF,$C0

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00,$3F,$FF,$FF,$FF,$FF,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$00,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00,$0F,$FF,$FF,$F0,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00,$00,$FC,$0F,$C0,$00

	.END
