	ORG	RBMA + $0000

	DC.B	$00,$05,$40,$00

	ORG	RBMA + $0100

	DC.B	$00,$11,$10,$00

	ORG	RBMA + $0200

	DC.B	$00,$41,$F4,$00

	ORG	RBMA + $0300

	DC.B	$01,$01,$F4,$00

	ORG	RBMA + $0400

	DC.B	$01,$01,$31,$00

	ORG	RBMA + $0500

	DC.B	$04,$01,$CD,$40

	ORG	RBMA + $0600

	DC.B	$15,$55,$55,$50

	ORG	RBMA + $0700

	DC.B	$15,$01,$AA,$90

	ORG	RBMA + $0800

	DC.B	$14,$01,$A6,$90

	ORG	RBMA + $0900

	DC.B	$54,$01,$99,$A4

	ORG	RBMA + $0A00

	DC.B	$51,$01,$A6,$A4

	ORG	RBMA + $0B00

	DC.B	$44,$01,$A6,$A4

	ORG	RBMA + $0C00

	DC.B	$40,$51,$96,$A4

	ORG	RBMA + $0D00

	DC.B	$41,$05,$41,$A4

	ORG	RBMA + $0E00

	DC.B	$44,$01,$00,$54

	ORG	RBMA + $0F00

	DC.B	$50,$00,$00,$04

	.END
