; FRAME # 1  COCO2 /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$0A,$A0,$00

	ORG	RBMA + $0200

	DC.B	$0A,$9A,$00

	ORG	RBMA + $0300

	DC.B	$2A,$56,$80

	ORG	RBMA + $0400

	DC.B	$29,$F6,$A0

	ORG	RBMA + $0500

	DC.B	$27,$FD,$A0

	ORG	RBMA + $0600

	DC.B	$27,$FD,$60

	ORG	RBMA + $0700

	DC.B	$25,$FF,$60

	ORG	RBMA + $0800

	DC.B	$25,$FD,$60

	ORG	RBMA + $0900

	DC.B	$24,$F1,$80

	ORG	RBMA + $0A00

	DC.B	$08,$31,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  COCO2 /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$33,$30,$00

	ORG	RBMA + $0100 + $03

	DC.B	$0F,$F0,$00

	ORG	RBMA + $0200 + $03

	DC.B	$0F,$C0,$C0

	ORG	RBMA + $0300 + $03

	DC.B	$3F,$03,$00

	ORG	RBMA + $0400 + $03

	DC.B	$3C,$0F,$C0

	ORG	RBMA + $0500 + $03

	DC.B	$3C,$0F,$F0

	ORG	RBMA + $0600 + $03

	DC.B	$0C,$03,$C0

	ORG	RBMA + $0700 + $03

	DC.B	$0C,$0F,$F0

	ORG	RBMA + $0800 + $03

	DC.B	$0F,$3C,$F0

	ORG	RBMA + $0900 + $03

	DC.B	$03,$03,$C0

	ORG	RBMA + $0A00 + $03

	DC.B	$0C,$0C,$03

	ORG	RBMA + $0B00 + $03

	DC.B	$0C,$03,$C0

	ORG	RBMA + $0C00 + $03

	DC.B	$30,$03,$C0

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  COCO2 /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$03,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$F0,$00

	ORG	RBMA + $0400 + $06

	DC.B	$03,$FF,$00

	ORG	RBMA + $0500 + $06

	DC.B	$03,$FF,$00

	ORG	RBMA + $0600 + $06

	DC.B	$03,$CC,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$C3,$C0

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

	.END
