; FRAME # 1  CURSOR/SPR

	ORG	RBMA + $0000

	DC.B	$00,$A0

	ORG	RBMA + $0100

	DC.B	$00,$A0

	ORG	RBMA + $0200

	DC.B	$00,$A0

	ORG	RBMA + $0300

	DC.B	$00,$00

	ORG	RBMA + $0400

	DC.B	$0A,$0A

	ORG	RBMA + $0500

	DC.B	$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$A0

	ORG	RBMA + $0700

	DC.B	$00,$A0

	ORG	RBMA + $0800

	DC.B	$00,$A0

	ORG	RBMA + $0900

	DC.B	$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00

; FRAME # 2  CURSOR/SPR

	ORG	RBMA + $0000 + $02

	DC.B	$00,$00

	ORG	RBMA + $0100 + $02

	DC.B	$00,$A0

	ORG	RBMA + $0200 + $02

	DC.B	$02,$A8

	ORG	RBMA + $0300 + $02

	DC.B	$0A,$AA

	ORG	RBMA + $0400 + $02

	DC.B	$0A,$AA

	ORG	RBMA + $0500 + $02

	DC.B	$0A,$AA

	ORG	RBMA + $0600 + $02

	DC.B	$02,$A8

	ORG	RBMA + $0700 + $02

	DC.B	$00,$A0

	ORG	RBMA + $0800 + $02

	DC.B	$00,$00

	ORG	RBMA + $0900 + $02

	DC.B	$00,$00

	ORG	RBMA + $0A00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0B00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $02

	DC.B	$00,$00

; FRAME # 3  CURSOR/SPR

	ORG	RBMA + $0000 + $04

	DC.B	$00,$00

	ORG	RBMA + $0100 + $04

	DC.B	$0A,$00

	ORG	RBMA + $0200 + $04

	DC.B	$00,$A0

	ORG	RBMA + $0300 + $04

	DC.B	$02,$A8

	ORG	RBMA + $0400 + $04

	DC.B	$02,$A8

	ORG	RBMA + $0500 + $04

	DC.B	$02,$A8

	ORG	RBMA + $0600 + $04

	DC.B	$00,$A2

	ORG	RBMA + $0700 + $04

	DC.B	$02,$08

	ORG	RBMA + $0800 + $04

	DC.B	$08,$00

	ORG	RBMA + $0900 + $04

	DC.B	$00,$00

	ORG	RBMA + $0A00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0B00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $04

	DC.B	$00,$00

; FRAME # 4  CURSOR/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$08,$28

	ORG	RBMA + $0100 + $06

	DC.B	$00,$08

	ORG	RBMA + $0200 + $06

	DC.B	$02,$80

	ORG	RBMA + $0300 + $06

	DC.B	$02,$88

	ORG	RBMA + $0400 + $06

	DC.B	$02,$80

	ORG	RBMA + $0500 + $06

	DC.B	$00,$80

	ORG	RBMA + $0600 + $06

	DC.B	$28,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$A0

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00

; FRAME # 5  CURSOR/SPR

	ORG	RBMA + $0000 + $08

	DC.B	$00,$00

	ORG	RBMA + $0100 + $08

	DC.B	$00,$00

	ORG	RBMA + $0200 + $08

	DC.B	$00,$20

	ORG	RBMA + $0300 + $08

	DC.B	$00,$00

	ORG	RBMA + $0400 + $08

	DC.B	$08,$00

	ORG	RBMA + $0500 + $08

	DC.B	$00,$00

	ORG	RBMA + $0600 + $08

	DC.B	$00,$20

	ORG	RBMA + $0700 + $08

	DC.B	$0A,$00

	ORG	RBMA + $0800 + $08

	DC.B	$00,$00

	ORG	RBMA + $0900 + $08

	DC.B	$00,$00

	ORG	RBMA + $0A00 + $08

	DC.B	$00,$00

	ORG	RBMA + $0B00 + $08

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $08

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $08

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $08

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $08

	DC.B	$00,$00

	.END
