; FRAME # 1  DAG2  /SPR

	ORG	RBMA + $0000

	DC.B	$00

	ORG	RBMA + $0100

	DC.B	$00

	ORG	RBMA + $0200

	DC.B	$20

	ORG	RBMA + $0300

	DC.B	$20

	ORG	RBMA + $0400

	DC.B	$20

	ORG	RBMA + $0500

	DC.B	$20

	ORG	RBMA + $0600

	DC.B	$20

	ORG	RBMA + $0700

	DC.B	$20

	ORG	RBMA + $0800

	DC.B	$20

	ORG	RBMA + $0900

	DC.B	$20

	ORG	RBMA + $0A00

	DC.B	$00

	ORG	RBMA + $0B00

	DC.B	$54

	ORG	RBMA + $0C00

	DC.B	$45

	ORG	RBMA + $0D00

	DC.B	$01

	ORG	RBMA + $0E00

	DC.B	$05

	ORG	RBMA + $0F00

	DC.B	$14

; FRAME # 2  DAG2  /SPR

	ORG	RBMA + $0000 + $01

	DC.B	$00

	ORG	RBMA + $0100 + $01

	DC.B	$00

	ORG	RBMA + $0200 + $01

	DC.B	$08

	ORG	RBMA + $0300 + $01

	DC.B	$08

	ORG	RBMA + $0400 + $01

	DC.B	$08

	ORG	RBMA + $0500 + $01

	DC.B	$08

	ORG	RBMA + $0600 + $01

	DC.B	$08

	ORG	RBMA + $0700 + $01

	DC.B	$08

	ORG	RBMA + $0800 + $01

	DC.B	$08

	ORG	RBMA + $0900 + $01

	DC.B	$08

	ORG	RBMA + $0A00 + $01

	DC.B	$08

	ORG	RBMA + $0B00 + $01

	DC.B	$11

	ORG	RBMA + $0C00 + $01

	DC.B	$15

	ORG	RBMA + $0D00 + $01

	DC.B	$04

	ORG	RBMA + $0E00 + $01

	DC.B	$04

	ORG	RBMA + $0F00 + $01

	DC.B	$04

; FRAME # 3  DAG2  /SPR

	ORG	RBMA + $0000 + $02

	DC.B	$00

	ORG	RBMA + $0100 + $02

	DC.B	$00

	ORG	RBMA + $0200 + $02

	DC.B	$08

	ORG	RBMA + $0300 + $02

	DC.B	$08

	ORG	RBMA + $0400 + $02

	DC.B	$08

	ORG	RBMA + $0500 + $02

	DC.B	$08

	ORG	RBMA + $0600 + $02

	DC.B	$08

	ORG	RBMA + $0700 + $02

	DC.B	$08

	ORG	RBMA + $0800 + $02

	DC.B	$08

	ORG	RBMA + $0900 + $02

	DC.B	$08

	ORG	RBMA + $0A00 + $02

	DC.B	$00

	ORG	RBMA + $0B00 + $02

	DC.B	$15

	ORG	RBMA + $0C00 + $02

	DC.B	$51

	ORG	RBMA + $0D00 + $02

	DC.B	$40

	ORG	RBMA + $0E00 + $02

	DC.B	$50

	ORG	RBMA + $0F00 + $02

	DC.B	$14

	.END
