	ORG	RBMA + $0000

	DC.B	$7D,$DD,$57,$77,$57,$D7,$F7,$D7,$DD,$D5,$7D,$F5,$F7,$75,$5D,$DD
	DC.B	$5D,$5D,$57,$D7

	ORG	RBMA + $0100

	DC.B	$F7,$75,$D5,$D5,$D5,$D5,$55,$FF,$77,$5D,$55,$7F,$DD,$D7,$57,$57
	DC.B	$5D,$5D,$5F,$57

	ORG	RBMA + $0200

	DC.B	$D5,$DD,$7D,$7D,$57,$D7,$DD,$7D,$5D,$D7,$D7,$5F,$55,$F5,$FF,$75
	DC.B	$77,$DF,$7D,$D5

	ORG	RBMA + $0300

	DC.B	$D7,$F5,$7D,$7D,$DD,$75,$F5,$7D,$7F,$57,$DD,$5F,$5D,$F5,$75,$77
	DC.B	$F5,$D5,$DD,$7D

	ORG	RBMA + $0400

	DC.B	$F7,$D7,$FD,$57,$5F,$77,$7D,$5F,$7D,$7F,$DF,$57,$D5,$55,$77,$5D
	DC.B	$D5,$5F,$75,$7D

	ORG	RBMA + $0500

	DC.B	$7F,$D7,$DF,$7F,$DD,$DD,$5F,$F7,$FD,$7D,$F7,$FD,$FD,$77,$75,$7F
	DC.B	$DF,$F7,$D5,$D5

	ORG	RBMA + $0600

	DC.B	$5D,$57,$D7,$D5,$55,$55,$55,$D5,$D5,$7F,$5D,$75,$75,$77,$75,$55
	DC.B	$F7,$D7,$F7,$F7

	ORG	RBMA + $0700

	DC.B	$5D,$5F,$57,$D5,$77,$55,$D5,$D5,$D5,$F7,$FD,$55,$75,$5F,$D7,$D5
	DC.B	$55,$DD,$D5,$75

	ORG	RBMA + $0800

	DC.B	$DF,$7D,$D5,$D5,$F5,$D5,$F7,$7D,$F7,$DF,$FD,$FF,$75,$57,$D7,$D7
	DC.B	$75,$55,$77,$55

	ORG	RBMA + $0900

	DC.B	$D5,$DD,$7D,$77,$5D,$57,$DF,$5D,$5D,$D7,$FD,$F7,$55,$FF,$77,$DD
	DC.B	$D5,$D7,$77,$DD

	ORG	RBMA + $0A00

	DC.B	$5F,$75,$7D,$7D,$57,$55,$DD,$55,$F7,$55,$DD,$F5,$7D,$F5,$7D,$75
	DC.B	$7F,$7F,$7F,$55

	ORG	RBMA + $0B00

	DC.B	$F7,$D5,$D5,$D7,$77,$DD,$DD,$FF,$7D,$5F,$7F,$FF,$D5,$D5,$5D,$5D
	DC.B	$F5,$5F,$7D,$55

	ORG	RBMA + $0C00

	DC.B	$D7,$F7,$F7,$7D,$55,$5D,$5F,$7D,$7F,$7D,$5F,$FF,$5D,$7F,$5F,$75
	DC.B	$F5,$57,$75,$FD

	ORG	RBMA + $0D00

	DC.B	$DD,$D5,$75,$D7,$DF,$7F,$55,$5D,$DD,$55,$55,$F7,$75,$55,$77,$5F
	DC.B	$5D,$FF,$7F,$F5

	ORG	RBMA + $0E00

	DC.B	$55,$77,$55,$5F,$FF,$FF,$77,$55,$57,$77,$FF,$D5,$57,$7D,$D5,$F5
	DC.B	$FF,$FD,$FD,$55

	ORG	RBMA + $0F00

	DC.B	$D7,$77,$DD,$D7,$FF,$FF,$FD,$5D,$77,$7D,$FF,$F7,$57,$75,$F5,$DD
	DC.B	$57,$7D,$7D,$DD

	ORG	RBMA + $0000 + $14

	DC.B	$7F,$7F,$55,$7D,$55,$F7,$F7,$F7,$F7,$F7,$7D,$FD,$FD,$F5,$F5,$75
	DC.B	$D5,$D7,$77,$5D

	ORG	RBMA + $0100 + $14

	DC.B	$5F,$7D,$55,$5D,$5F,$DF,$FF,$55,$F7,$D7,$5F,$F5,$75,$F7,$55,$F5
	DC.B	$FF,$F5,$DF,$5F

	ORG	RBMA + $0200 + $14

	DC.B	$57,$75,$FD,$D5,$DD,$55,$FF,$55,$77,$5F,$7F,$F5,$5D,$D5,$55,$57
	DC.B	$7F,$F7,$DF,$5D

	ORG	RBMA + $0300 + $14

	DC.B	$FF,$7F,$F5,$75,$5D,$5D,$75,$DF,$F7,$FF,$DF,$F7,$FF,$5F,$5F,$55
	DC.B	$5D,$57,$D5,$D5

	ORG	RBMA + $0400 + $14

	DC.B	$FD,$FD,$55,$57,$57,$F5,$7F,$FF,$DF,$D5,$F7,$7F,$FF,$77,$57,$5D
	DC.B	$5F,$55,$55,$5D

	ORG	RBMA + $0500 + $14

	DC.B	$7D,$7D,$DD,$D5,$55,$75,$D5,$77,$D7,$DF,$FD,$5D,$FF,$75,$75,$55
	DC.B	$FF,$FD,$7D,$F7

	ORG	RBMA + $0600 + $14

	DC.B	$D7,$77,$5D,$DF,$D7,$D7,$FD,$5D,$77,$77,$5F,$F7,$5D,$77,$77,$7F
	DC.B	$7F,$7D,$7D,$5F

	ORG	RBMA + $0700 + $14

	DC.B	$F5,$DF,$5F,$D7,$57,$FD,$5F,$FF,$5D,$F7,$FF,$FF,$D7,$F5,$F5,$5D
	DC.B	$FD,$FD,$77,$55

	ORG	RBMA + $0800 + $14

	DC.B	$F7,$DF,$5D,$F5,$F7,$FF,$77,$FF,$7D,$F7,$57,$DF,$D5,$75,$75,$D7
	DC.B	$F7,$F7,$F7,$55

	ORG	RBMA + $0900 + $14

	DC.B	$57,$D5,$D5,$F5,$F7,$57,$5D,$D5,$7D,$5D,$77,$D5,$57,$75,$75,$D7
	DC.B	$77,$F5,$FF,$FD

	ORG	RBMA + $0A00 + $14

	DC.B	$55,$55,$5D,$5D,$7D,$7F,$D5,$F5,$55,$55,$FD,$FD,$5F,$FF,$F7,$F5
	DC.B	$5F,$F7,$F5,$D5

	ORG	RBMA + $0B00 + $14

	DC.B	$FD,$7D,$F7,$55,$77,$FF,$5F,$FF,$D7,$DD,$FF,$FF,$F7,$7D,$FD,$D5
	DC.B	$5F,$FF,$FD,$5D

	ORG	RBMA + $0C00 + $14

	DC.B	$7D,$7D,$5F,$DF,$DF,$FD,$D7,$F7,$D7,$D5,$FD,$FD,$FF,$55,$5F,$5F
	DC.B	$DF,$FF,$7F,$FF

	ORG	RBMA + $0D00 + $14

	DC.B	$FD,$77,$55,$D5,$57,$F7,$DF,$DF,$D7,$75,$5D,$55,$77,$55,$5F,$5D
	DC.B	$7D,$7F,$7F,$5D

	ORG	RBMA + $0E00 + $14

	DC.B	$F7,$F7,$55,$F7,$F5,$F5,$5F,$7F,$7F,$75,$5F,$7F,$5F,$F7,$FF,$75
	DC.B	$FD,$FF,$77,$5D

	ORG	RBMA + $0F00 + $14

	DC.B	$F5,$FF,$FD,$7D,$FF,$D7,$57,$7F,$5F,$FF,$D7,$DF,$F7,$55,$DD,$55
	DC.B	$FF,$FF,$F5,$FF

	ORG	RBMA + $0000 + $28

	DC.B	$F7,$F5,$D5,$D7,$FF,$5D,$DD,$FF,$7F,$5D,$5D,$7F,$F5,$55,$77,$FD
	DC.B	$FD,$77,$7F,$FF

	ORG	RBMA + $0100 + $28

	DC.B	$FF,$FD,$5D,$57,$5D,$5F,$D5,$FF,$FF,$D5,$D5,$75,$DF,$75,$F7,$F5
	DC.B	$55,$F5,$F7,$57

	ORG	RBMA + $0200 + $28

	DC.B	$FF,$7F,$FF,$D5,$77,$7D,$FD,$FF,$F7,$FF,$FD,$57,$75,$7F,$FD,$DD
	DC.B	$7F,$FF,$FF,$5F

	ORG	RBMA + $0300 + $28

	DC.B	$7F,$7F,$5D,$7F,$7F,$F5,$D7,$D7,$F7,$F5,$D7,$F7,$F5,$55,$DD,$DF
	DC.B	$DF,$F5,$77,$DF

	ORG	RBMA + $0400 + $28

	DC.B	$FF,$77,$5D,$77,$D7,$F7,$7F,$DF,$F7,$75,$D7,$7D,$75,$55,$55,$FD
	DC.B	$D7,$F7,$FD,$D5

	ORG	RBMA + $0500 + $28

	DC.B	$FF,$F5,$FF,$F7,$D7,$F5,$5F,$FF,$FF,$5F,$FF,$7D,$75,$FF,$F7,$7D
	DC.B	$57,$FF,$FF,$D5

	ORG	RBMA + $0600 + $28

	DC.B	$77,$7F,$FF,$F7,$7F,$D7,$FF,$D7,$77,$FF,$FF,$77,$F7,$D7,$FF,$75
	DC.B	$F7,$F5,$DD,$7D

	ORG	RBMA + $0700 + $28

	DC.B	$F5,$F7,$57,$57,$57,$5F,$57,$5F,$5F,$75,$75,$75,$7F,$5D,$DF,$57
	DC.B	$D5,$57,$D7,$D5

	ORG	RBMA + $0800 + $28

	DC.B	$FF,$FF,$5F,$D7,$D5,$7D,$D7,$FF,$FF,$F5,$FD,$7D,$57,$D5,$FF,$DF
	DC.B	$75,$FF,$FF,$75

	ORG	RBMA + $0900 + $28

	DC.B	$F5,$77,$DF,$D7,$F5,$75,$FD,$FF,$57,$7D,$FD,$7F,$5D,$FD,$55,$DD
	DC.B	$7F,$7F,$D5,$5D

	ORG	RBMA + $0A00 + $28

	DC.B	$5F,$5D,$7D,$57,$77,$FF,$F5,$F5,$F5,$D7,$D5,$77,$75,$FD,$DD,$FF
	DC.B	$7D,$7D,$7D,$77

	ORG	RBMA + $0B00 + $28

	DC.B	$DF,$D5,$75,$7D,$7F,$FD,$57,$7D,$FD,$57,$57,$D7,$F5,$D5,$5F,$FF
	DC.B	$55,$5F,$7F,$F7

	ORG	RBMA + $0C00 + $28

	DC.B	$75,$7D,$FD,$FF,$77,$F7,$DF,$F7,$57,$DF,$DF,$F7,$77,$D5,$DF,$FD
	DC.B	$F7,$FD,$D5,$57

	ORG	RBMA + $0D00 + $28

	DC.B	$75,$7F,$ED,$FF,$7F,$DF,$DF,$D7,$57,$FD,$DF,$F7,$F7,$D7,$D7,$F7
	DC.B	$F7,$F5,$D7,$FF

	ORG	RBMA + $0E00 + $28

	DC.B	$FD,$F5,$A3,$75,$7F,$7F,$5D,$F7,$D7,$75,$7F,$DF,$FF,$5D,$D7,$5F
	DC.B	$D7,$7D,$F7,$F5

	ORG	RBMA + $0F00 + $28

	DC.B	$7F,$77,$A3,$D7,$D7,$7F,$F7,$75,$FF,$FD,$7D,$57,$D5,$DF,$FF,$5F
	DC.B	$FD,$DD,$7F,$D5

	ORG	RBMA + $0000 + $3C

	DC.B	$FF,$5F,$A1,$D7,$F7,$5F,$D7,$57,$FF,$DF,$DF,$DF,$57,$75,$77,$57
	DC.B	$F5,$D5,$FF,$D5

	ORG	RBMA + $0100 + $3C

	DC.B	$5F,$55,$A1,$F7,$F7,$FF,$F7,$FF,$7D,$57,$F7,$F5,$DF,$FD,$FF,$FF
	DC.B	$FD,$FF,$DF,$D5

	ORG	RBMA + $0200 + $3C

	DC.B	$D7,$D5,$A1,$5F,$7F,$FF,$5D,$FF,$57,$5F,$95,$F5,$55,$7D,$7F,$FF
	DC.B	$D7,$7F,$D7,$75

	ORG	RBMA + $0300 + $3C

	DC.B	$F5,$7D,$A1,$57,$F7,$F7,$F5,$F7,$D5,$77,$9F,$FD,$FF,$FF,$F7,$FD
	DC.B	$FD,$7D,$F7,$FD

	ORG	RBMA + $0400 + $3C

	DC.B	$F5,$7F,$A1,$5F,$F5,$FF,$FF,$FF,$DF,$FF,$9F,$D5,$F7,$7F,$D5,$FF
	DC.B	$FF,$FF,$F7,$D5

	ORG	RBMA + $0500 + $3C

	DC.B	$F5,$7D,$A1,$57,$F5,$D5,$D5,$DF,$FD,$77,$9F,$5D,$F5,$5F,$D5,$F5
	DC.B	$75,$77,$FF,$F5

	ORG	RBMA + $0600 + $3C

	DC.B	$7D,$57,$A1,$55,$FD,$77,$5F,$FF,$75,$7E,$87,$DD,$57,$D5,$7F,$5D
	DC.B	$D7,$FF,$DF,$DD

	ORG	RBMA + $0700 + $3C

	DC.B	$7D,$7F,$A1,$55,$FF,$7F,$F7,$FF,$D5,$FA,$81,$DF,$5F,$F7,$7F,$DF
	DC.B	$FD,$FF,$F7,$F7

	ORG	RBMA + $0800 + $3C

	DC.B	$FD,$FF,$A3,$D5,$5F,$F7,$F5,$7D,$FD,$FA,$81,$7D,$5F,$DD,$57,$FD
	DC.B	$FD,$5F,$7F,$F5

	ORG	RBMA + $0900 + $3C

	DC.B	$DD,$FF,$A3,$F5,$75,$F5,$FD,$57,$5F,$DB,$B1,$7D,$5D,$FD,$DD,$7D
	DC.B	$7F,$55,$D7,$F5

	ORG	RBMA + $0A00 + $3C

	DC.B	$F7,$FF,$A0,$0D,$77,$F7,$7D,$77,$DF,$FB,$B1,$FD,$FD,$7F,$5D,$FD
	DC.B	$DF,$5D,$F7,$7D

	ORG	RBMA + $0B00 + $3C

	DC.B	$FF,$FE,$A0,$01,$FF,$FF,$7F,$5D,$5F,$FB,$B3,$D5,$77,$FD,$7F,$FF
	DC.B	$DF,$D7,$57,$DD

	ORG	RBMA + $0C00 + $3C

	DC.B	$F7,$FA,$A0,$03,$7F,$5F,$75,$F5,$D7,$5B,$B3,$F7,$FF,$DD,$DF,$D7
	DC.B	$DD,$7D,$77,$D7

	ORG	RBMA + $0D00 + $3C

	DC.B	$F7,$EA,$A1,$C3,$75,$5F,$7D,$F7,$F5,$5B,$B3,$7F,$57,$55,$DD,$57
	DC.B	$DF,$7D,$FF,$FF

	ORG	RBMA + $0E00 + $3C

	DC.B	$FF,$EB,$A1,$F3,$F5,$5D,$5D,$D7,$F7,$DB,$B3,$55,$5F,$55,$FD,$57
	DC.B	$57,$75,$FF,$7D

	ORG	RBMA + $0F00 + $3C

	DC.B	$FF,$EB,$A1,$73,$5D,$FF,$7D,$F5,$75,$5F,$BF,$55,$7D,$7D,$D7,$7F
	DC.B	$DF,$7D,$5F,$7D

	ORG	RBMA + $0000 + $50

	DC.B	$5F,$EB,$A1,$73,$DD,$FF,$F5,$F7,$57,$FF,$FF,$DF,$DF,$DD,$F7,$7F
	DC.B	$FD,$7D,$D5,$75

	ORG	RBMA + $0100 + $50

	DC.B	$7F,$EB,$A1,$7F,$7F,$D7,$55,$FF,$7F,$5D,$75,$F7,$DF,$FF,$DF,$F5
	DC.B	$D5,$7F,$DF,$55

	ORG	RBMA + $0200 + $50

	DC.B	$5F,$EB,$A1,$DF,$7F,$DF,$DF,$D5,$F7,$55,$5D,$D7,$D7,$F7,$DF,$F7
	DC.B	$F7,$F5,$7F,$E5

	ORG	RBMA + $0300 + $50

	DC.B	$5D,$EF,$A3,$55,$FF,$DD,$FF,$77,$57,$7F,$5D,$F5,$F7,$DD,$7F,$77
	DC.B	$7F,$DD,$D7,$EF

	ORG	RBMA + $0400 + $50

	DC.B	$FD,$FF,$A3,$77,$D7,$DF,$7F,$7F,$75,$FF,$D7,$FF,$55,$55,$F5,$E7
	DC.B	$DF,$DF,$DF,$EF

	ORG	RBMA + $0500 + $50

	DC.B	$FD,$FF,$A3,$F5,$FD,$DF,$7D,$7F,$BF,$55,$DD,$7D,$5D,$DD,$7F,$67
	DC.B	$DF,$5F,$DD,$EF

	ORG	RBMA + $0600 + $50

	DC.B	$D5,$FF,$A3,$57,$5D,$D5,$F5,$F7,$BD,$77,$FF,$FF,$FF,$FD,$D7,$65
	DC.B	$7D,$7D,$DF,$6F

	ORG	RBMA + $0700 + $50

	DC.B	$F7,$FF,$EF,$FF,$FF,$FF,$FD,$FD,$9F,$77,$F5,$75,$77,$57,$FF,$EF
	DC.B	$FF,$7F,$57,$6F

	ORG	RBMA + $0800 + $50

	DC.B	$FF,$DF,$FF,$DF,$FF,$FF,$5F,$5D,$BF,$FF,$75,$D5,$DD,$FF,$FF,$EF
	DC.B	$D7,$D7,$7F,$AB

	ORG	RBMA + $0900 + $50

	DC.B	$5F,$5D,$FF,$77,$BF,$FD,$7F,$DA,$9F,$7F,$7F,$FF,$FF,$F5,$DF,$EF
	DC.B	$5F,$F5,$F6,$E9

	ORG	RBMA + $0A00 + $50

	DC.B	$7F,$5F,$FF,$F7,$9F,$DF,$5F,$FB,$AF,$55,$F5,$FF,$FF,$F5,$DF,$E7
	DC.B	$D7,$FF,$FB,$EE

	ORG	RBMA + $0B00 + $50

	DC.B	$7F,$FF,$FF,$7F,$9F,$DD,$FD,$DB,$AF,$D7,$77,$5F,$77,$DF,$DF,$EB
	DC.B	$7F,$77,$F9,$EF

	ORG	RBMA + $0C00 + $50

	DC.B	$7F,$FF,$FF,$FF,$9F,$DF,$DD,$FB,$9B,$FF,$FD,$5D,$5F,$5F,$DE,$AE
	DC.B	$F7,$7F,$D9,$EF

	ORG	RBMA + $0D00 + $50

	DC.B	$7D,$55,$FD,$F7,$9F,$F7,$F5,$FB,$9F,$77,$FF,$FF,$FF,$FD,$FE,$66
	DC.B	$7F,$F7,$FB,$EF

	ORG	RBMA + $0E00 + $50

	DC.B	$FF,$FF,$77,$FE,$A7,$FD,$FD,$F7,$9F,$D5,$5F,$F5,$7F,$DF,$FE,$66
	DC.B	$DD,$7F,$FB,$EF

	ORG	RBMA + $0F00 + $50

	DC.B	$FF,$FF,$FF,$FA,$AD,$FD,$FD,$57,$97,$FD,$75,$FD,$7F,$FF,$DE,$66
	DC.B	$FF,$F7,$F7,$EF

	ORG	RBMA + $0000 + $64

	DC.B	$FF,$FF,$FF,$FB,$99,$FD,$FF,$55,$DD,$7F,$FF,$5F,$7D,$5F,$DE,$6E
	DC.B	$D7,$57,$7F,$FD

	ORG	RBMA + $0100 + $64

	DC.B	$FE,$D5,$DF,$FB,$99,$DF,$5F,$FD,$DD,$57,$FF,$FF,$FF,$FF,$DE,$6E
	DC.B	$7D,$57,$7D,$FD

	ORG	RBMA + $0200 + $64

	DC.B	$FE,$FF,$F7,$7F,$9B,$DF,$FF,$FF,$DF,$F7,$7F,$7F,$D7,$FF,$FE,$6E
	DC.B	$DD,$DD,$FD,$FD

	ORG	RBMA + $0300 + $64

	DC.B	$FE,$FF,$FF,$FD,$BF,$FF,$DF,$5F,$7F,$FF,$DF,$D7,$DD,$FF,$F6,$66
	DC.B	$FD,$F5,$F7,$FF

	ORG	RBMA + $0400 + $64

	DC.B	$FE,$D5,$7D,$7F,$BF,$F7,$5F,$5F,$F5,$77,$7D,$FF,$B5,$FD,$FE,$66
	DC.B	$DD,$F7,$F7,$D7

	ORG	RBMA + $0500 + $64

	DC.B	$FA,$BF,$F7,$F7,$FD,$7F,$75,$5F,$75,$75,$F7,$FF,$9F,$FF,$FF,$66
	DC.B	$FD,$DF,$FF,$DF

	ORG	RBMA + $0600 + $64

	DC.B	$EE,$BF,$7F,$7F,$D7,$F7,$DF,$DF,$FD,$57,$FF,$FD,$BF,$FF,$FF,$E7
	DC.B	$7F,$FF,$7F,$5F

	ORG	RBMA + $0700 + $64

	DC.B	$EE,$FF,$F5,$57,$FF,$D5,$55,$7D,$FF,$DF,$7D,$7F,$5F,$5F,$FF,$67
	DC.B	$7D,$7F,$5F,$7F

	ORG	RBMA + $0800 + $64

	DC.B	$EE,$FF,$FF,$FF,$7F,$FD,$77,$DD,$7F,$FF,$B7,$FF,$FF,$DD,$5D,$5F
	DC.B	$7D,$7F,$5F,$7D

	ORG	RBMA + $0900 + $64

	DC.B	$FE,$F5,$FF,$FD,$5D,$FF,$77,$FF,$5E,$7F,$FD,$7D,$D5,$F5,$DF,$5F
	DC.B	$57,$5F,$FF,$FD

	ORG	RBMA + $0A00 + $64

	DC.B	$5F,$FF,$D7,$FD,$75,$55,$DD,$FF,$FE,$FF,$F7,$FD,$F5,$F5,$FF,$57
	DC.B	$7F,$77,$FD,$FD

	ORG	RBMA + $0B00 + $64

	DC.B	$7F,$FF,$FD,$77,$FF,$55,$FD,$D7,$55,$FF,$D7,$55,$FD,$FD,$F5,$FF
	DC.B	$FF,$FD,$F7,$F7

	ORG	RBMA + $0C00 + $64

	DC.B	$FF,$DF,$FF,$DF,$FD,$FF,$FF,$FD,$F7,$D7,$FF,$FF,$FF,$DF,$75,$7D
	DC.B	$FF,$DD,$7F,$D7

	ORG	RBMA + $0D00 + $64

	DC.B	$DF,$FD,$FF,$7F,$D7,$5B,$DF,$FD,$FD,$DF,$7D,$FD,$7F,$7F,$F7,$FD
	DC.B	$7D,$FD,$7F,$D5

	ORG	RBMA + $0E00 + $64

	DC.B	$FF,$FF,$FF,$FD,$FF,$7B,$DD,$FD,$FF,$5F,$77,$FF,$FF,$FF,$5F,$5D
	DC.B	$75,$FD,$7D,$FD

	ORG	RBMA + $0F00 + $64

	DC.B	$FF,$FF,$FF,$FF,$FF,$5B,$FF,$DF,$DD,$DF,$77,$FF,$DD,$FF,$5F,$DF
	DC.B	$FF,$7D,$FF,$FF

	ORG	RBMA + $0000 + $78

	DC.B	$FF,$FF,$57,$5F,$55,$7F,$FF,$7F,$5F,$FF,$FF,$FF,$F7,$F7,$77,$DD
	DC.B	$DD,$77,$FF,$FF

	ORG	RBMA + $0100 + $78

	DC.B	$DF,$5F,$D7,$DF,$DD,$F7,$FF,$D7,$D7,$F7,$77,$F5,$FF,$F7,$77,$7F
	DC.B	$7F,$5F,$5F,$FF

	ORG	RBMA + $0200 + $78

	DC.B	$FF,$F7,$FD,$DB,$FF,$F5,$D7,$DF,$DF,$FF,$5D,$7D,$DF,$FF,$FF,$DF
	DC.B	$FD,$7F,$FF,$F7

	ORG	RBMA + $0300 + $78

	DC.B	$FF,$DF,$DF,$F9,$F7,$FF,$FF,$FF,$FF,$D7,$FF,$FF,$FF,$77,$FF,$DF
	DC.B	$FF,$FF,$FF,$FF

	ORG	RBMA + $0400 + $78

	DC.B	$F5,$F5,$FF,$FB,$F7,$DF,$FF,$F7,$FF,$7D,$7F,$7D,$FD,$7F,$B7,$7D
	DC.B	$FF,$FF,$FF,$7F

	ORG	RBMA + $0500 + $78

	DC.B	$FF,$FF,$FF,$FD,$FF,$DF,$7D,$7D,$FF,$FF,$FF,$DF,$FF,$FF,$BF,$FF
	DC.B	$FD,$F7,$FF,$FF

	ORG	RBMA + $0600 + $78

	DC.B	$FF,$FF,$FD,$DF,$FF,$FD,$FD,$75,$D5,$FF,$FD,$FF,$5F,$7F,$FF,$DF
	DC.B	$FF,$7F,$FF,$FF

	ORG	RBMA + $0700 + $78

	DC.B	$F7,$FD,$FD,$FF,$7D,$7F,$FF,$7F,$FF,$7D,$7F,$5F,$5D,$7F,$7F,$DD
	DC.B	$FF,$FF,$D7,$F7

	ORG	RBMA + $0800 + $78

	DC.B	$77,$7D,$5F,$FF,$5F,$FF,$FF,$FF,$F7,$FF,$FD,$FF,$FF,$7F,$7F,$7F
	DC.B	$DF,$FF,$7F,$FF

	ORG	RBMA + $0900 + $78

	DC.B	$F7,$7F,$5F,$5F,$FD,$FF,$FF,$7F,$FF,$FF,$FF,$FF,$FF,$7F,$FF,$FF
	DC.B	$F5,$F7,$FF,$F7

	ORG	RBMA + $0A00 + $78

	DC.B	$F7,$7F,$DF,$DF,$FF,$F7,$5F,$7F,$FF,$FF,$7F,$7F,$FD,$FF,$FF,$FF
	DC.B	$DD,$FF,$7F,$57

	ORG	RBMA + $0B00 + $78

	DC.B	$FF,$7F,$DF,$DF,$DF,$FF,$5F,$FF,$F7,$FF,$FD,$FF,$F7,$FD,$7F,$FF
	DC.B	$FD,$FF,$F5,$7D

	ORG	RBMA + $0C00 + $78

	DC.B	$DF,$FF,$FF,$FF,$FF,$FF,$FF,$F5,$FF,$D5,$DF,$FF,$FF,$FF,$7F,$7F
	DC.B	$7F,$FF,$FF,$DD

	ORG	RBMA + $0D00 + $78

	DC.B	$F7,$F7,$FF,$FD,$DF,$DF,$FF,$FF,$FF,$FF,$FF,$F7,$FF,$FF,$FF,$DF
	DC.B	$FD,$DD,$FF,$FF

	ORG	RBMA + $0E00 + $78

	DC.B	$F7,$FF,$FF,$FF,$7F,$FF,$FF,$FF,$DF,$7F,$FF,$5F,$7F,$DF,$DF,$DF
	DC.B	$FF,$DD,$75,$DD

	ORG	RBMA + $0F00 + $78

	DC.B	$DF,$FF,$FF,$F7,$FF,$FF,$F7,$DF,$FF,$FF,$FD,$FF,$FF,$FF,$DF,$FF
	DC.B	$FF,$FF,$FF,$75

	.END
