; FRAME # 1  DEST  /SPR

	ORG	RBMA + $0000

	DC.B	$00,$C0,$00

	ORG	RBMA + $0100

	DC.B	$02,$E0,$00

	ORG	RBMA + $0200

	DC.B	$0A,$E8,$00

	ORG	RBMA + $0300

	DC.B	$0B,$EA,$00

	ORG	RBMA + $0400

	DC.B	$2B,$EA,$00

	ORG	RBMA + $0500

	DC.B	$2F,$EA,$80

	ORG	RBMA + $0600

	DC.B	$FF,$FF,$C0

	ORG	RBMA + $0700

	DC.B	$AF,$D5,$40

	ORG	RBMA + $0800

	DC.B	$AB,$D5,$40

	ORG	RBMA + $0900

	DC.B	$A2,$D1,$40

	ORG	RBMA + $0A00

	DC.B	$80,$C0,$40

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

	.END
