; FRAME # 1  DIAMND/SPR

	ORG	RBMA + $0000

	DC.B	$00,$A0,$00

	ORG	RBMA + $0100

	DC.B	$01,$A4,$00

	ORG	RBMA + $0200

	DC.B	$01,$A4,$00

	ORG	RBMA + $0300

	DC.B	$06,$A9,$00

	ORG	RBMA + $0400

	DC.B	$06,$A9,$00

	ORG	RBMA + $0500

	DC.B	$1A,$AA,$40

	ORG	RBMA + $0600

	DC.B	$1A,$AA,$40

	ORG	RBMA + $0700

	DC.B	$6A,$AA,$90

	ORG	RBMA + $0800

	DC.B	$BB,$BB,$B0

	ORG	RBMA + $0900

	DC.B	$EE,$AE,$A0

	ORG	RBMA + $0A00

	DC.B	$3B,$BB,$80

	ORG	RBMA + $0B00

	DC.B	$0A,$AA,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

	.END
