; FRAME # 1  DIE2  /SPR

	ORG	RBMA + $0000

	DC.B	$15,$59,$50

	ORG	RBMA + $0100

	DC.B	$15,$59,$50

	ORG	RBMA + $0200

	DC.B	$05,$95,$90

	ORG	RBMA + $0300

	DC.B	$05,$9A,$80

	ORG	RBMA + $0400

	DC.B	$05,$99,$90

	ORG	RBMA + $0500

	DC.B	$05,$55,$40

	ORG	RBMA + $0600

	DC.B	$05,$56,$40

	ORG	RBMA + $0700

	DC.B	$06,$59,$40

	ORG	RBMA + $0800

	DC.B	$16,$66,$60

	ORG	RBMA + $0900

	DC.B	$06,$66,$50

	ORG	RBMA + $0A00

	DC.B	$06,$66,$90

	ORG	RBMA + $0B00

	DC.B	$04,$61,$00

	ORG	RBMA + $0C00

	DC.B	$06,$64,$40

	ORG	RBMA + $0D00

	DC.B	$09,$26,$40

	ORG	RBMA + $0E00

	DC.B	$00,$62,$40

	ORG	RBMA + $0F00

	DC.B	$05,$A9,$40

	ORG	RBMA + $1000

	DC.B	$05,$11,$40

	ORG	RBMA + $1100

	DC.B	$01,$21,$40

	ORG	RBMA + $1200

	DC.B	$01,$9A,$40

	ORG	RBMA + $1300

	DC.B	$04,$82,$40

	ORG	RBMA + $1400

	DC.B	$16,$56,$50

	ORG	RBMA + $1500

	DC.B	$06,$42,$00

	ORG	RBMA + $1600

	DC.B	$04,$66,$40

	ORG	RBMA + $1700

	DC.B	$04,$46,$40

	ORG	RBMA + $1800

	DC.B	$01,$46,$50

	ORG	RBMA + $1900

	DC.B	$14,$46,$40

	ORG	RBMA + $1A00

	DC.B	$04,$40,$40

	ORG	RBMA + $1B00

	DC.B	$00,$51,$00

	ORG	RBMA + $1C00

	DC.B	$01,$11,$40

	ORG	RBMA + $1D00

	DC.B	$00,$10,$10

	ORG	RBMA + $1E00

	DC.B	$01,$01,$00

	ORG	RBMA + $1F00

	DC.B	$01,$10,$00

; FRAME # 2  DIE2  /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$05,$59,$40

	ORG	RBMA + $0100 + $03

	DC.B	$05,$59,$40

	ORG	RBMA + $0200 + $03

	DC.B	$01,$95,$00

	ORG	RBMA + $0300 + $03

	DC.B	$01,$98,$00

	ORG	RBMA + $0400 + $03

	DC.B	$01,$99,$00

	ORG	RBMA + $0500 + $03

	DC.B	$01,$59,$00

	ORG	RBMA + $0600 + $03

	DC.B	$05,$55,$00

	ORG	RBMA + $0700 + $03

	DC.B	$04,$54,$40

	ORG	RBMA + $0800 + $03

	DC.B	$14,$64,$60

	ORG	RBMA + $0900 + $03

	DC.B	$04,$64,$50

	ORG	RBMA + $0A00 + $03

	DC.B	$04,$64,$10

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$45,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$02,$55,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$01,$44,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$09,$44,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$05,$09,$00

	ORG	RBMA + $1000 + $03

	DC.B	$05,$19,$00

	ORG	RBMA + $1100 + $03

	DC.B	$01,$15,$40

	ORG	RBMA + $1200 + $03

	DC.B	$01,$14,$40

	ORG	RBMA + $1300 + $03

	DC.B	$04,$10,$00

	ORG	RBMA + $1400 + $03

	DC.B	$04,$10,$00

	ORG	RBMA + $1500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  DIE2  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$01,$59,$50

	ORG	RBMA + $0100 + $06

	DC.B	$06,$59,$40

	ORG	RBMA + $0200 + $06

	DC.B	$05,$55,$40

	ORG	RBMA + $0300 + $06

	DC.B	$01,$98,$00

	ORG	RBMA + $0400 + $06

	DC.B	$05,$59,$00

	ORG	RBMA + $0500 + $06

	DC.B	$05,$99,$00

	ORG	RBMA + $0600 + $06

	DC.B	$01,$55,$40

	ORG	RBMA + $0700 + $06

	DC.B	$04,$64,$50

	ORG	RBMA + $0800 + $06

	DC.B	$00,$58,$20

	ORG	RBMA + $0900 + $06

	DC.B	$00,$58,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$54,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$45,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$45,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$06,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$10,$80,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$01,$04,$00

	ORG	RBMA + $1000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  DIE2  /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$01,$55,$40

	ORG	RBMA + $0100 + $09

	DC.B	$06,$65,$40

	ORG	RBMA + $0200 + $09

	DC.B	$01,$55,$00

	ORG	RBMA + $0300 + $09

	DC.B	$01,$96,$00

	ORG	RBMA + $0400 + $09

	DC.B	$05,$54,$00

	ORG	RBMA + $0500 + $09

	DC.B	$06,$85,$00

	ORG	RBMA + $0600 + $09

	DC.B	$01,$59,$00

	ORG	RBMA + $0700 + $09

	DC.B	$04,$44,$00

	ORG	RBMA + $0800 + $09

	DC.B	$00,$44,$40

	ORG	RBMA + $0900 + $09

	DC.B	$01,$00,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$12,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $09

	DC.B	$00,$00,$00

	.END
