	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00,$00,$00,$00,$03

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00,$00,$00,$00,$0F

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00,$00,$00,$00,$3D

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00,$00,$00,$00,$FD

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$00,$00,$03,$FD

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00,$00,$0F,$F7

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00,$00,$3F,$F7

	ORG	RBMA + $0000 + $07

	DC.B	$00,$00,$00,$00,$00,$F7,$F7

	ORG	RBMA + $0100 + $07

	DC.B	$00,$00,$00,$00,$03,$F7,$F7

	ORG	RBMA + $0200 + $07

	DC.B	$00,$00,$00,$00,$0F,$F7,$F7

	ORG	RBMA + $0300 + $07

	DC.B	$00,$00,$00,$00,$3F,$F7,$D7

	ORG	RBMA + $0400 + $07

	DC.B	$00,$00,$00,$00,$FF,$F7,$DF

	ORG	RBMA + $0500 + $07

	DC.B	$00,$00,$00,$03,$7F,$DF,$DF

	ORG	RBMA + $0600 + $07

	DC.B	$00,$00,$00,$0F,$7F,$DF,$DC

	ORG	RBMA + $0700 + $07

	DC.B	$00,$00,$00,$3F,$7F,$DD,$5C

	ORG	RBMA + $0800 + $07

	DC.B	$00,$00,$00,$FF,$7F,$D7,$DC

	ORG	RBMA + $0900 + $07

	DC.B	$00,$00,$03,$FF,$7F,$DF,$DC

	ORG	RBMA + $0A00 + $07

	DC.B	$00,$00,$0D,$FD,$FD,$7F,$5C

	ORG	RBMA + $0B00 + $07

	DC.B	$00,$00,$3D,$FD,$F7,$FF,$7C

	ORG	RBMA + $0C00 + $07

	DC.B	$00,$00,$FD,$FD,$5F,$FF,$70

	ORG	RBMA + $0D00 + $07

	DC.B	$00,$00,$FD,$FD,$FF,$F5,$70

	ORG	RBMA + $0E00 + $07

	DC.B	$00,$00,$F7,$F7,$FF,$DF,$70

	ORG	RBMA + $0F00 + $07

	DC.B	$00,$03,$F7,$5F,$FD,$7F,$70

	ORG	RBMA + $0000 + $0E

	DC.B	$00,$03,$F5,$FF,$F5,$FF,$70

	ORG	RBMA + $0100 + $0E

	DC.B	$00,$03,$F7,$FF,$5D,$FF,$70

	ORG	RBMA + $0200 + $0E

	DC.B	$00,$03,$5F,$F5,$FD,$FD,$70

	ORG	RBMA + $0300 + $0E

	DC.B	$00,$01,$FF,$D7,$FD,$FD,$F0

	ORG	RBMA + $0400 + $0E

	DC.B	$00,$07,$FD,$57,$F5,$FD,$F0

	ORG	RBMA + $0500 + $0E

	DC.B	$00,$0F,$F7,$F7,$F7,$FD,$F0

	ORG	RBMA + $0600 + $0E

	DC.B	$00,$0F,$5F,$F7,$F7,$FD,$C0

	ORG	RBMA + $0700 + $0E

	DC.B	$00,$0D,$DF,$F7,$F7,$FD,$C0

	ORG	RBMA + $0800 + $0E

	DC.B	$00,$07,$DF,$F7,$F7,$F5,$C0

	ORG	RBMA + $0900 + $0E

	DC.B	$00,$0F,$DF,$DF,$F7,$F7,$C0

	ORG	RBMA + $0A00 + $0E

	DC.B	$00,$0F,$DF,$DF,$DF,$F7,$C0

	ORG	RBMA + $0B00 + $0E

	DC.B	$00,$3F,$DF,$DF,$DF,$F7,$C0

	ORG	RBMA + $0C00 + $0E

	DC.B	$00,$3F,$7F,$DF,$DF,$F7,$C0

	ORG	RBMA + $0D00 + $0E

	DC.B	$00,$3F,$7F,$7F,$DF,$F7,$00

	ORG	RBMA + $0E00 + $0E

	DC.B	$00,$3F,$7F,$7F,$DF,$D7,$00

	ORG	RBMA + $0F00 + $0E

	DC.B	$00,$3F,$7F,$7F,$DF,$DF,$00

	ORG	RBMA + $0000 + $15

	DC.B	$00,$3F,$7F,$7F,$7F,$DF,$00

	ORG	RBMA + $0100 + $15

	DC.B	$00,$FF,$7D,$FF,$7F,$DF,$00

	ORG	RBMA + $0200 + $15

	DC.B	$00,$FD,$FD,$FF,$7F,$DF,$00

	ORG	RBMA + $0300 + $15

	DC.B	$00,$FD,$FD,$FF,$7F,$DF,$00

	ORG	RBMA + $0400 + $15

	DC.B	$00,$FD,$FD,$FF,$7F,$5C,$00

	ORG	RBMA + $0500 + $15

	DC.B	$00,$FD,$F5,$FF,$7F,$7C,$00

	ORG	RBMA + $0600 + $15

	DC.B	$00,$FD,$F7,$FD,$FF,$7C,$00

	ORG	RBMA + $0700 + $15

	DC.B	$00,$FD,$F7,$FD,$FF,$7C,$00

	ORG	RBMA + $0800 + $15

	DC.B	$03,$FD,$F7,$FD,$FF,$7C,$00

	ORG	RBMA + $0900 + $15

	DC.B	$03,$F7,$F7,$FD,$F5,$7C,$00

	ORG	RBMA + $0A00 + $15

	DC.B	$03,$F7,$F7,$FD,$5F,$7C,$00

	ORG	RBMA + $0B00 + $15

	DC.B	$03,$F7,$F5,$57,$FD,$70,$00

	ORG	RBMA + $0C00 + $15

	DC.B	$03,$F7,$57,$FF,$FD,$F0,$00

	ORG	RBMA + $0D00 + $15

	DC.B	$03,$D5,$FF,$FF,$FD,$F0,$00

	ORG	RBMA + $0E00 + $15

	DC.B	$01,$7F,$FF,$FF,$FD,$F0,$00

	ORG	RBMA + $0F00 + $15

	DC.B	$0F,$FF,$FF,$FD,$55,$F0,$00

	ORG	RBMA + $0000 + $1C

	DC.B	$0F,$FF,$FD,$55,$FD,$F0,$00

	ORG	RBMA + $0100 + $1C

	DC.B	$0F,$FD,$57,$FD,$FD,$F0,$00

	ORG	RBMA + $0200 + $1C

	DC.B	$0F,$57,$F7,$FD,$F5,$F0,$00

	ORG	RBMA + $0300 + $1C

	DC.B	$05,$DF,$F7,$FD,$F7,$C0,$00

	ORG	RBMA + $0400 + $1C

	DC.B	$0F,$DF,$F7,$FD,$F7,$C0,$00

	ORG	RBMA + $0500 + $1C

	DC.B	$3F,$DF,$F7,$F7,$F7,$C0,$00

	ORG	RBMA + $0600 + $1C

	DC.B	$3F,$DF,$DF,$F7,$F7,$C0,$00

	ORG	RBMA + $0700 + $1C

	DC.B	$3F,$7F,$DF,$F7,$F7,$C0,$00

	ORG	RBMA + $0800 + $1C

	DC.B	$3F,$7F,$DF,$F7,$F7,$C0,$00

	ORG	RBMA + $0900 + $1C

	DC.B	$3F,$7F,$DF,$F7,$D7,$C0,$00

	ORG	RBMA + $0A00 + $1C

	DC.B	$3F,$7F,$DF,$55,$7F,$00,$00

	ORG	RBMA + $0B00 + $1C

	DC.B	$3F,$7D,$55,$7F,$FF,$00,$00

	ORG	RBMA + $0C00 + $1C

	DC.B	$F5,$55,$FF,$FF,$FF,$40,$00

	ORG	RBMA + $0D00 + $1C

	DC.B	$57,$FF,$FF,$F0,$00,$00,$00

	ORG	RBMA + $0E00 + $1C

	DC.B	$FF,$FF,$C0,$00,$00,$00,$00

	ORG	RBMA + $0F00 + $1C

	DC.B	$FC,$00,$00,$00,$00,$00,$00

	.END
