; FRAME # 1  DRAGON/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1000

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1100

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1200

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1300

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1400

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1500

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1600

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1700

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$04,$F0,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$3E,$B0,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$3F,$BC,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$3B,$EC,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$3B,$FB,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$0F,$FB,$C0

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00,$FE,$C0

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00,$3F,$F0

; FRAME # 2  DRAGON/SPR

	ORG	RBMA + $0000 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0200 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0300 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0400 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0500 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0600 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0700 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0800 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0900 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0A00 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0B00 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0C00 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0D00 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0E00 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0F00 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1000 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1100 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $1200 + $05

	DC.B	$00,$04,$F0,$00,$00

	ORG	RBMA + $1300 + $05

	DC.B	$00,$3E,$B0,$00,$00

	ORG	RBMA + $1400 + $05

	DC.B	$00,$3F,$BC,$00,$00

	ORG	RBMA + $1500 + $05

	DC.B	$00,$3B,$EF,$00,$00

	ORG	RBMA + $1600 + $05

	DC.B	$00,$3B,$FB,$00,$00

	ORG	RBMA + $1700 + $05

	DC.B	$00,$0F,$FB,$C0,$00

	ORG	RBMA + $1800 + $05

	DC.B	$00,$00,$FE,$C0,$00

	ORG	RBMA + $1900 + $05

	DC.B	$00,$00,$3F,$F0,$00

	ORG	RBMA + $1A00 + $05

	DC.B	$00,$00,$3F,$F0,$00

	ORG	RBMA + $1B00 + $05

	DC.B	$00,$00,$0F,$FF,$00

	ORG	RBMA + $1C00 + $05

	DC.B	$00,$00,$0F,$FF,$C0

	ORG	RBMA + $1D00 + $05

	DC.B	$00,$00,$0F,$FF,$F0

	ORG	RBMA + $1E00 + $05

	DC.B	$00,$00,$0F,$9F,$F0

	ORG	RBMA + $1F00 + $05

	DC.B	$00,$00,$03,$97,$FC

; FRAME # 3  DRAGON/SPR

	ORG	RBMA + $0000 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0200 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0300 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0400 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0500 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0600 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0700 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0800 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0900 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0A00 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0B00 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0C00 + $0A

	DC.B	$04,$F0,$00,$00,$00

	ORG	RBMA + $0D00 + $0A

	DC.B	$3E,$B0,$00,$00,$00

	ORG	RBMA + $0E00 + $0A

	DC.B	$3F,$BC,$00,$00,$00

	ORG	RBMA + $0F00 + $0A

	DC.B	$3B,$EF,$00,$00,$00

	ORG	RBMA + $1000 + $0A

	DC.B	$3B,$FB,$00,$00,$00

	ORG	RBMA + $1100 + $0A

	DC.B	$0F,$FB,$C0,$00,$00

	ORG	RBMA + $1200 + $0A

	DC.B	$00,$FE,$C0,$00,$00

	ORG	RBMA + $1300 + $0A

	DC.B	$00,$3F,$F0,$00,$00

	ORG	RBMA + $1400 + $0A

	DC.B	$00,$3F,$F0,$00,$00

	ORG	RBMA + $1500 + $0A

	DC.B	$00,$0F,$FF,$00,$00

	ORG	RBMA + $1600 + $0A

	DC.B	$00,$0F,$FF,$C0,$00

	ORG	RBMA + $1700 + $0A

	DC.B	$00,$0F,$FF,$F0,$00

	ORG	RBMA + $1800 + $0A

	DC.B	$00,$0F,$9F,$F0,$00

	ORG	RBMA + $1900 + $0A

	DC.B	$00,$03,$97,$FC,$00

	ORG	RBMA + $1A00 + $0A

	DC.B	$00,$03,$54,$FC,$00

	ORG	RBMA + $1B00 + $0A

	DC.B	$00,$00,$DC,$FF,$00

	ORG	RBMA + $1C00 + $0A

	DC.B	$00,$00,$3C,$FF,$00

	ORG	RBMA + $1D00 + $0A

	DC.B	$00,$00,$0F,$BF,$C0

	ORG	RBMA + $1E00 + $0A

	DC.B	$00,$00,$03,$BF,$C0

	ORG	RBMA + $1F00 + $0A

	DC.B	$00,$00,$03,$BF,$F0

; FRAME # 4  DRAGON/SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0300 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0400 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0500 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0600 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0700 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0800 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0900 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0A00 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0B00 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0C00 + $0F

	DC.B	$00,$70,$00,$00,$00

	ORG	RBMA + $0D00 + $0F

	DC.B	$10,$1C,$00,$00,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$F4,$0F,$00,$00,$00

	ORG	RBMA + $0F00 + $0F

	DC.B	$F4,$27,$00,$00,$00

	ORG	RBMA + $1000 + $0F

	DC.B	$ED,$2B,$00,$00,$00

	ORG	RBMA + $1100 + $0F

	DC.B	$EF,$9B,$C0,$00,$00

	ORG	RBMA + $1200 + $0F

	DC.B	$3F,$FA,$C0,$00,$00

	ORG	RBMA + $1300 + $0F

	DC.B	$03,$FF,$C0,$00,$00

	ORG	RBMA + $1400 + $0F

	DC.B	$00,$FF,$F0,$00,$00

	ORG	RBMA + $1500 + $0F

	DC.B	$00,$3F,$FF,$00,$00

	ORG	RBMA + $1600 + $0F

	DC.B	$00,$3F,$FF,$C0,$00

	ORG	RBMA + $1700 + $0F

	DC.B	$00,$0F,$FF,$F0,$00

	ORG	RBMA + $1800 + $0F

	DC.B	$00,$0F,$9F,$F0,$00

	ORG	RBMA + $1900 + $0F

	DC.B	$00,$03,$97,$FC,$00

	ORG	RBMA + $1A00 + $0F

	DC.B	$00,$03,$54,$FC,$00

	ORG	RBMA + $1B00 + $0F

	DC.B	$00,$00,$DC,$FF,$00

	ORG	RBMA + $1C00 + $0F

	DC.B	$00,$00,$3C,$FF,$00

	ORG	RBMA + $1D00 + $0F

	DC.B	$00,$00,$0F,$BF,$C0

	ORG	RBMA + $1E00 + $0F

	DC.B	$00,$00,$03,$BF,$C0

	ORG	RBMA + $1F00 + $0F

	DC.B	$00,$00,$03,$BF,$F0

; FRAME # 5  DRAGON/SPR

	ORG	RBMA + $0000 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0200 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0300 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0400 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0500 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0600 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0700 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0800 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0900 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0A00 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0B00 + $14

	DC.B	$00,$1C,$00,$00,$00

	ORG	RBMA + $0C00 + $14

	DC.B	$02,$07,$00,$00,$00

	ORG	RBMA + $0D00 + $14

	DC.B	$00,$8F,$00,$00,$00

	ORG	RBMA + $0E00 + $14

	DC.B	$40,$83,$00,$00,$00

	ORG	RBMA + $0F00 + $14

	DC.B	$70,$A7,$C0,$00,$00

	ORG	RBMA + $1000 + $14

	DC.B	$F4,$23,$C0,$00,$00

	ORG	RBMA + $1100 + $14

	DC.B	$FD,$AA,$C0,$00,$00

	ORG	RBMA + $1200 + $14

	DC.B	$EF,$DA,$C0,$00,$00

	ORG	RBMA + $1300 + $14

	DC.B	$EF,$FE,$F0,$00,$00

	ORG	RBMA + $1400 + $14

	DC.B	$3F,$FF,$F0,$00,$00

	ORG	RBMA + $1500 + $14

	DC.B	$00,$FF,$FF,$00,$00

	ORG	RBMA + $1600 + $14

	DC.B	$00,$3F,$FF,$C0,$00

	ORG	RBMA + $1700 + $14

	DC.B	$00,$0F,$FF,$F0,$00

	ORG	RBMA + $1800 + $14

	DC.B	$00,$0F,$9F,$F0,$00

	ORG	RBMA + $1900 + $14

	DC.B	$00,$03,$97,$FC,$00

	ORG	RBMA + $1A00 + $14

	DC.B	$00,$03,$54,$FC,$00

	ORG	RBMA + $1B00 + $14

	DC.B	$00,$00,$DC,$FF,$00

	ORG	RBMA + $1C00 + $14

	DC.B	$00,$00,$3C,$FF,$00

	ORG	RBMA + $1D00 + $14

	DC.B	$00,$00,$0F,$BF,$C0

	ORG	RBMA + $1E00 + $14

	DC.B	$00,$00,$03,$BF,$C0

	ORG	RBMA + $1F00 + $14

	DC.B	$00,$00,$03,$BF,$F0

	.END
