; FRAME # 1  EYE   /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$01,$54,$00

	ORG	RBMA + $0700

	DC.B	$07,$FD,$00

	ORG	RBMA + $0800

	DC.B	$07,$FD,$00

	ORG	RBMA + $0900

	DC.B	$1F,$5F,$40

	ORG	RBMA + $0A00

	DC.B	$1D,$77,$40

	ORG	RBMA + $0B00

	DC.B	$1D,$77,$40

	ORG	RBMA + $0C00

	DC.B	$05,$55,$00

	ORG	RBMA + $0D00

	DC.B	$05,$55,$00

	ORG	RBMA + $0E00

	DC.B	$01,$54,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  EYE   /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$01,$54,$00

	ORG	RBMA + $0500 + $03

	DC.B	$07,$FD,$00

	ORG	RBMA + $0600 + $03

	DC.B	$1F,$FF,$40

	ORG	RBMA + $0700 + $03

	DC.B	$1F,$FF,$40

	ORG	RBMA + $0800 + $03

	DC.B	$7F,$57,$D0

	ORG	RBMA + $0900 + $03

	DC.B	$7D,$5D,$D0

	ORG	RBMA + $0A00 + $03

	DC.B	$7D,$7D,$D0

	ORG	RBMA + $0B00 + $03

	DC.B	$1D,$7D,$D0

	ORG	RBMA + $0C00 + $03

	DC.B	$1D,$5D,$40

	ORG	RBMA + $0D00 + $03

	DC.B	$05,$55,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$05,$54,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$01,$54,$00

; FRAME # 3  EYE   /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$01,$54,$00

	ORG	RBMA + $0500 + $06

	DC.B	$05,$7D,$00

	ORG	RBMA + $0600 + $06

	DC.B	$15,$5F,$40

	ORG	RBMA + $0700 + $06

	DC.B	$15,$5F,$40

	ORG	RBMA + $0800 + $06

	DC.B	$77,$DF,$D0

	ORG	RBMA + $0900 + $06

	DC.B	$75,$FF,$D0

	ORG	RBMA + $0A00 + $06

	DC.B	$7D,$7F,$D0

	ORG	RBMA + $0B00 + $06

	DC.B	$1F,$FF,$D0

	ORG	RBMA + $0C00 + $06

	DC.B	$1F,$FF,$40

	ORG	RBMA + $0D00 + $06

	DC.B	$07,$FD,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$07,$FC,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$01,$54,$00

; FRAME # 4  EYE   /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$01,$54,$00

	ORG	RBMA + $0500 + $09

	DC.B	$07,$FD,$00

	ORG	RBMA + $0600 + $09

	DC.B	$1F,$F5,$40

	ORG	RBMA + $0700 + $09

	DC.B	$1F,$D5,$40

	ORG	RBMA + $0800 + $09

	DC.B	$7F,$D7,$50

	ORG	RBMA + $0900 + $09

	DC.B	$7F,$D7,$50

	ORG	RBMA + $0A00 + $09

	DC.B	$7F,$D5,$50

	ORG	RBMA + $0B00 + $09

	DC.B	$1F,$F5,$50

	ORG	RBMA + $0C00 + $09

	DC.B	$1F,$FF,$40

	ORG	RBMA + $0D00 + $09

	DC.B	$07,$FD,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$07,$F4,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$01,$54,$00

; FRAME # 5  EYE   /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$01,$54,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$07,$55,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$1F,$55,$40

	ORG	RBMA + $0700 + $0C

	DC.B	$1F,$5D,$40

	ORG	RBMA + $0800 + $0C

	DC.B	$7F,$5F,$D0

	ORG	RBMA + $0900 + $0C

	DC.B	$7F,$5F,$D0

	ORG	RBMA + $0A00 + $0C

	DC.B	$5F,$5F,$D0

	ORG	RBMA + $0B00 + $0C

	DC.B	$17,$57,$50

	ORG	RBMA + $0C00 + $0C

	DC.B	$15,$55,$40

	ORG	RBMA + $0D00 + $0C

	DC.B	$05,$55,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$05,$54,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$01,$54,$00

; FRAME # 6  EYE   /SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0F

	DC.B	$01,$54,$00

	ORG	RBMA + $0500 + $0F

	DC.B	$05,$55,$00

	ORG	RBMA + $0600 + $0F

	DC.B	$1D,$57,$40

	ORG	RBMA + $0700 + $0F

	DC.B	$1D,$57,$40

	ORG	RBMA + $0800 + $0F

	DC.B	$55,$55,$50

	ORG	RBMA + $0900 + $0F

	DC.B	$55,$55,$50

	ORG	RBMA + $0A00 + $0F

	DC.B	$55,$55,$50

	ORG	RBMA + $0B00 + $0F

	DC.B	$15,$55,$50

	ORG	RBMA + $0C00 + $0F

	DC.B	$15,$55,$40

	ORG	RBMA + $0D00 + $0F

	DC.B	$05,$55,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$05,$54,$00

	ORG	RBMA + $0F00 + $0F

	DC.B	$01,$54,$00

; FRAME # 7  EYE   /SPR

	ORG	RBMA + $0000 + $12

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $12

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $12

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $12

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $12

	DC.B	$01,$54,$00

	ORG	RBMA + $0500 + $12

	DC.B	$07,$55,$00

	ORG	RBMA + $0600 + $12

	DC.B	$1F,$55,$40

	ORG	RBMA + $0700 + $12

	DC.B	$1F,$5D,$40

	ORG	RBMA + $0800 + $12

	DC.B	$7F,$5F,$D0

	ORG	RBMA + $0900 + $12

	DC.B	$7F,$5F,$D0

	ORG	RBMA + $0A00 + $12

	DC.B	$5F,$5F,$D0

	ORG	RBMA + $0B00 + $12

	DC.B	$17,$57,$50

	ORG	RBMA + $0C00 + $12

	DC.B	$15,$55,$40

	ORG	RBMA + $0D00 + $12

	DC.B	$05,$55,$00

	ORG	RBMA + $0E00 + $12

	DC.B	$05,$54,$00

	ORG	RBMA + $0F00 + $12

	DC.B	$01,$54,$00

	.END
