; FRAME # 1  FACE2 /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$28,$00

	ORG	RBMA + $0300

	DC.B	$00,$28,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$01,$00,$10

	ORG	RBMA + $0800

	DC.B	$05,$80,$58

	ORG	RBMA + $0900

	DC.B	$01,$00,$10

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  FACE2 /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$AA,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$28,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$28,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$01,$82,$40

	ORG	RBMA + $0800 + $03

	DC.B	$05,$82,$50

	ORG	RBMA + $0900 + $03

	DC.B	$05,$00,$50

	ORG	RBMA + $0A00 + $03

	DC.B	$04,$00,$14

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  FACE2 /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$02,$00,$80

	ORG	RBMA + $0100 + $06

	DC.B	$00,$82,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$28,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$20,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $06

	DC.B	$01,$42,$50

	ORG	RBMA + $0800 + $06

	DC.B	$09,$42,$50

	ORG	RBMA + $0900 + $06

	DC.B	$09,$41,$50

	ORG	RBMA + $0A00 + $06

	DC.B	$15,$00,$54

	ORG	RBMA + $0B00 + $06

	DC.B	$14,$00,$14

	ORG	RBMA + $0C00 + $06

	DC.B	$10,$00,$04

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  FACE2 /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$59,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$59,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$19,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $09

	DC.B	$01,$41,$40

	ORG	RBMA + $0800 + $09

	DC.B	$05,$41,$50

	ORG	RBMA + $0900 + $09

	DC.B	$06,$41,$90

	ORG	RBMA + $0A00 + $09

	DC.B	$05,$41,$50

	ORG	RBMA + $0B00 + $09

	DC.B	$15,$00,$54

	ORG	RBMA + $0C00 + $09

	DC.B	$10,$00,$04

	ORG	RBMA + $0D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

; FRAME # 5  FACE2 /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$02,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$88,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$20,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $0C

	DC.B	$01,$81,$40

	ORG	RBMA + $0800 + $0C

	DC.B	$05,$81,$60

	ORG	RBMA + $0900 + $0C

	DC.B	$05,$81,$60

	ORG	RBMA + $0A00 + $0C

	DC.B	$05,$41,$50

	ORG	RBMA + $0B00 + $0C

	DC.B	$15,$00,$54

	ORG	RBMA + $0C00 + $0C

	DC.B	$10,$00,$04

	ORG	RBMA + $0D00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$00,$00,$00

; FRAME # 6  FACE2 /SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$02,$00,$80

	ORG	RBMA + $0100 + $0F

	DC.B	$00,$82,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$00,$82,$00

	ORG	RBMA + $0300 + $0F

	DC.B	$00,$28,$00

	ORG	RBMA + $0400 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $0F

	DC.B	$01,$81,$40

	ORG	RBMA + $0800 + $0F

	DC.B	$05,$82,$50

	ORG	RBMA + $0900 + $0F

	DC.B	$05,$82,$50

	ORG	RBMA + $0A00 + $0F

	DC.B	$05,$41,$50

	ORG	RBMA + $0B00 + $0F

	DC.B	$15,$00,$54

	ORG	RBMA + $0C00 + $0F

	DC.B	$10,$00,$04

	ORG	RBMA + $0D00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $0F

	DC.B	$00,$00,$00

	.END
