	ORG	RBMA + $0000

	DC.B	$02,$00,$0B,$00,$00,$80

	ORG	RBMA + $0100

	DC.B	$02,$00,$0B,$00,$00,$80

	ORG	RBMA + $0200

	DC.B	$02,$00,$0B,$00,$00,$80

	ORG	RBMA + $0300

	DC.B	$02,$C0,$0B,$00,$00,$80

	ORG	RBMA + $0400

	DC.B	$02,$C0,$0B,$00,$00,$80

	ORG	RBMA + $0500

	DC.B	$02,$C0,$0B,$00,$00,$80

	ORG	RBMA + $0600

	DC.B	$02,$C0,$0B,$C0,$00,$80

	ORG	RBMA + $0700

	DC.B	$02,$C0,$0B,$C0,$00,$80

	ORG	RBMA + $0800

	DC.B	$0A,$C0,$0B,$C0,$00,$80

	ORG	RBMA + $0900

	DC.B	$0A,$C0,$0B,$C0,$02,$80

	ORG	RBMA + $0A00

	DC.B	$0A,$C0,$2B,$C0,$02,$C0

	ORG	RBMA + $0B00

	DC.B	$0A,$C0,$2A,$C0,$02,$C0

	ORG	RBMA + $0C00

	DC.B	$0A,$F0,$2A,$F0,$0A,$C0

	ORG	RBMA + $0D00

	DC.B	$2A,$F0,$2A,$F0,$0A,$F0

	ORG	RBMA + $0E00

	DC.B	$2A,$F0,$2A,$F0,$0A,$F0

	ORG	RBMA + $0F00

	DC.B	$2A,$F0,$2A,$FC,$2A,$F0

	ORG	RBMA + $1000

	DC.B	$2A,$FC,$2A,$FC,$2A,$F0

	ORG	RBMA + $1100

	DC.B	$2A,$FC,$2A,$FC,$AA,$FC

	ORG	RBMA + $1200

	DC.B	$AA,$FC,$2A,$FC,$AA,$FC

	ORG	RBMA + $1300

	DC.B	$AA,$FC,$AA,$FC,$AA,$FC

	ORG	RBMA + $1400

	DC.B	$AA,$FC,$AA,$F0,$2A,$FC

	ORG	RBMA + $1500

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1600

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1700

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00,$00,$00,$00

	.END
