; FRAME # 1  FD1   /SPR

	ORG	RBMA + $0000

	DC.B	$C0

	ORG	RBMA + $0100

	DC.B	$C0

	ORG	RBMA + $0200

	DC.B	$C0

	ORG	RBMA + $0300

	DC.B	$30

	ORG	RBMA + $0400

	DC.B	$30

	ORG	RBMA + $0500

	DC.B	$F0

	ORG	RBMA + $0600

	DC.B	$0C

	ORG	RBMA + $0700

	DC.B	$0C

	ORG	RBMA + $0800

	DC.B	$0C

	ORG	RBMA + $0900

	DC.B	$0F

	ORG	RBMA + $0A00

	DC.B	$0F

	ORG	RBMA + $0B00

	DC.B	$0F

	ORG	RBMA + $0C00

	DC.B	$00

	ORG	RBMA + $0D00

	DC.B	$00

	ORG	RBMA + $0E00

	DC.B	$00

	ORG	RBMA + $0F00

	DC.B	$00

; FRAME # 2  FD1   /SPR

	ORG	RBMA + $0000 + $01

	DC.B	$C0

	ORG	RBMA + $0100 + $01

	DC.B	$C0

	ORG	RBMA + $0200 + $01

	DC.B	$C0

	ORG	RBMA + $0300 + $01

	DC.B	$30

	ORG	RBMA + $0400 + $01

	DC.B	$F0

	ORG	RBMA + $0500 + $01

	DC.B	$30

	ORG	RBMA + $0600 + $01

	DC.B	$0C

	ORG	RBMA + $0700 + $01

	DC.B	$0C

	ORG	RBMA + $0800 + $01

	DC.B	$0C

	ORG	RBMA + $0900 + $01

	DC.B	$0F

	ORG	RBMA + $0A00 + $01

	DC.B	$0F

	ORG	RBMA + $0B00 + $01

	DC.B	$0F

	ORG	RBMA + $0C00 + $01

	DC.B	$00

	ORG	RBMA + $0D00 + $01

	DC.B	$00

	ORG	RBMA + $0E00 + $01

	DC.B	$00

	ORG	RBMA + $0F00 + $01

	DC.B	$00

	.END
