; FRAME # 1  FISH  /SPR

	ORG	RBMA + $0000

	DC.B	$00,$FF,$00

	ORG	RBMA + $0100

	DC.B	$03,$00,$C0

	ORG	RBMA + $0200

	DC.B	$03,$00,$C0

	ORG	RBMA + $0300

	DC.B	$00,$FF,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  FISH  /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$FF,$00

	ORG	RBMA + $0100 + $03

	DC.B	$0F,$00,$F0

	ORG	RBMA + $0200 + $03

	DC.B	$30,$00,$0C

	ORG	RBMA + $0300 + $03

	DC.B	$30,$FF,$0C

	ORG	RBMA + $0400 + $03

	DC.B	$C3,$00,$C3

	ORG	RBMA + $0500 + $03

	DC.B	$C3,$00,$C3

	ORG	RBMA + $0600 + $03

	DC.B	$C0,$FF,$03

	ORG	RBMA + $0700 + $03

	DC.B	$30,$00,$0C

	ORG	RBMA + $0800 + $03

	DC.B	$0F,$00,$F0

	ORG	RBMA + $0900 + $03

	DC.B	$00,$FF,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  FISH  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$FF,$00

	ORG	RBMA + $0100 + $06

	DC.B	$0F,$00,$F0

	ORG	RBMA + $0200 + $06

	DC.B	$30,$00,$0C

	ORG	RBMA + $0300 + $06

	DC.B	$30,$F2,$8C

	ORG	RBMA + $0400 + $06

	DC.B	$C3,$0A,$A3

	ORG	RBMA + $0500 + $06

	DC.B	$C3,$0A,$A3

	ORG	RBMA + $0600 + $06

	DC.B	$C0,$EA,$A3

	ORG	RBMA + $0700 + $06

	DC.B	$30,$2A,$8C

	ORG	RBMA + $0800 + $06

	DC.B	$0F,$EA,$B0

	ORG	RBMA + $0900 + $06

	DC.B	$00,$2A,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$28,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  FISH  /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$20

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$20

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$28

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$AA

	ORG	RBMA + $0400 + $09

	DC.B	$00,$02,$A0

	ORG	RBMA + $0500 + $09

	DC.B	$00,$0A,$A0

	ORG	RBMA + $0600 + $09

	DC.B	$00,$2A,$80

	ORG	RBMA + $0700 + $09

	DC.B	$00,$2A,$80

	ORG	RBMA + $0800 + $09

	DC.B	$00,$AA,$80

	ORG	RBMA + $0900 + $09

	DC.B	$00,$AA,$80

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$AA,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$00,$A0,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

; FRAME # 5  FISH  /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $0C

	DC.B	$00,$A0,$02

	ORG	RBMA + $0900 + $0C

	DC.B	$0A,$AA,$08

	ORG	RBMA + $0A00 + $0C

	DC.B	$2A,$AA,$A8

	ORG	RBMA + $0B00 + $0C

	DC.B	$2A,$AA,$A8

	ORG	RBMA + $0C00 + $0C

	DC.B	$0A,$AA,$88

	ORG	RBMA + $0D00 + $0C

	DC.B	$00,$AA,$02

	ORG	RBMA + $0E00 + $0C

	DC.B	$00,$20,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$00,$00,$00

; FRAME # 6  FISH  /SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0F

	DC.B	$A0,$00,$00

	ORG	RBMA + $0400 + $0F

	DC.B	$A8,$00,$00

	ORG	RBMA + $0500 + $0F

	DC.B	$AA,$00,$00

	ORG	RBMA + $0600 + $0F

	DC.B	$AA,$80,$00

	ORG	RBMA + $0700 + $0F

	DC.B	$2A,$80,$00

	ORG	RBMA + $0800 + $0F

	DC.B	$2A,$80,$00

	ORG	RBMA + $0900 + $0F

	DC.B	$2A,$A0,$00

	ORG	RBMA + $0A00 + $0F

	DC.B	$0A,$A0,$00

	ORG	RBMA + $0B00 + $0F

	DC.B	$00,$AA,$00

	ORG	RBMA + $0C00 + $0F

	DC.B	$00,$28,$00

	ORG	RBMA + $0D00 + $0F

	DC.B	$00,$20,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$00,$20,$00

	ORG	RBMA + $0F00 + $0F

	DC.B	$00,$00,$00

; FRAME # 7  FISH  /SPR

	ORG	RBMA + $0000 + $12

	DC.B	$00,$FF,$00

	ORG	RBMA + $0100 + $12

	DC.B	$0F,$00,$F0

	ORG	RBMA + $0200 + $12

	DC.B	$30,$00,$0C

	ORG	RBMA + $0300 + $12

	DC.B	$30,$FF,$0C

	ORG	RBMA + $0400 + $12

	DC.B	$CA,$00,$C3

	ORG	RBMA + $0500 + $12

	DC.B	$EA,$80,$C3

	ORG	RBMA + $0600 + $12

	DC.B	$EA,$BF,$03

	ORG	RBMA + $0700 + $12

	DC.B	$2A,$80,$0C

	ORG	RBMA + $0800 + $12

	DC.B	$0A,$80,$F0

	ORG	RBMA + $0900 + $12

	DC.B	$0A,$BF,$00

	ORG	RBMA + $0A00 + $12

	DC.B	$02,$A0,$00

	ORG	RBMA + $0B00 + $12

	DC.B	$02,$AA,$00

	ORG	RBMA + $0C00 + $12

	DC.B	$00,$A0,$00

	ORG	RBMA + $0D00 + $12

	DC.B	$00,$80,$00

	ORG	RBMA + $0E00 + $12

	DC.B	$00,$80,$00

	ORG	RBMA + $0F00 + $12

	DC.B	$00,$00,$00

	.END
