; FRAME # 1  FRBALL/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00

	ORG	RBMA + $0100

	DC.B	$09,$90

	ORG	RBMA + $0200

	DC.B	$1A,$68

	ORG	RBMA + $0300

	DC.B	$A2,$A9

	ORG	RBMA + $0400

	DC.B	$42,$66

	ORG	RBMA + $0500

	DC.B	$81,$A9

	ORG	RBMA + $0600

	DC.B	$02,$9A

	ORG	RBMA + $0700

	DC.B	$01,$A9

	ORG	RBMA + $0800

	DC.B	$00,$98

	ORG	RBMA + $0900

	DC.B	$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00

; FRAME # 2  FRBALL/SPR

	ORG	RBMA + $0000 + $02

	DC.B	$0A,$40

	ORG	RBMA + $0100 + $02

	DC.B	$20,$A0

	ORG	RBMA + $0200 + $02

	DC.B	$00,$A4

	ORG	RBMA + $0300 + $02

	DC.B	$00,$6A

	ORG	RBMA + $0400 + $02

	DC.B	$02,$A6

	ORG	RBMA + $0500 + $02

	DC.B	$09,$AA

	ORG	RBMA + $0600 + $02

	DC.B	$1A,$A8

	ORG	RBMA + $0700 + $02

	DC.B	$2A,$90

	ORG	RBMA + $0800 + $02

	DC.B	$06,$80

	ORG	RBMA + $0900 + $02

	DC.B	$00,$00

	ORG	RBMA + $0A00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0B00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $02

	DC.B	$00,$00

; FRAME # 3  FRBALL/SPR

	ORG	RBMA + $0000 + $04

	DC.B	$06,$00

	ORG	RBMA + $0100 + $04

	DC.B	$2A,$40

	ORG	RBMA + $0200 + $04

	DC.B	$9A,$A0

	ORG	RBMA + $0300 + $04

	DC.B	$A9,$80

	ORG	RBMA + $0400 + $04

	DC.B	$6A,$80

	ORG	RBMA + $0500 + $04

	DC.B	$A6,$42

	ORG	RBMA + $0600 + $04

	DC.B	$2A,$AA

	ORG	RBMA + $0700 + $04

	DC.B	$06,$A4

	ORG	RBMA + $0800 + $04

	DC.B	$00,$60

	ORG	RBMA + $0900 + $04

	DC.B	$00,$00

	ORG	RBMA + $0A00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0B00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $04

	DC.B	$00,$00

	.END
