; FRAME # 1  GHOST /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$C0,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$03,$3F,$C0

	ORG	RBMA + $0200

	DC.B	$00,$00,$FC,$00,$30

	ORG	RBMA + $0300

	DC.B	$00,$0F,$00,$00,$0C

	ORG	RBMA + $0400

	DC.B	$00,$30,$00,$00,$0C

	ORG	RBMA + $0500

	DC.B	$00,$C0,$00,$00,$0C

	ORG	RBMA + $0600

	DC.B	$03,$00,$00,$00,$0C

	ORG	RBMA + $0700

	DC.B	$03,$00,$00,$00,$0C

	ORG	RBMA + $0800

	DC.B	$03,$00,$0F,$C0,$0C

	ORG	RBMA + $0900

	DC.B	$03,$0F,$FC,$30,$03

	ORG	RBMA + $0A00

	DC.B	$0C,$0C,$0C,$0C,$03

	ORG	RBMA + $0B00

	DC.B	$0C,$0C,$0C,$03,$03

	ORG	RBMA + $0C00

	DC.B	$0C,$3C,$0F,$00,$CC

	ORG	RBMA + $0D00

	DC.B	$03,$F0,$0C,$00,$30

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00,$00

; FRAME # 2  GHOST /SPR

	ORG	RBMA + $0000 + $05

	DC.B	$00,$00,$3F,$00,$00

	ORG	RBMA + $0100 + $05

	DC.B	$00,$00,$FF,$FF,$3C

	ORG	RBMA + $0200 + $05

	DC.B	$00,$03,$FF,$FF,$FF

	ORG	RBMA + $0300 + $05

	DC.B	$00,$0F,$FF,$FF,$FC

	ORG	RBMA + $0400 + $05

	DC.B	$00,$3F,$FF,$FF,$F0

	ORG	RBMA + $0500 + $05

	DC.B	$00,$3F,$FF,$FF,$FC

	ORG	RBMA + $0600 + $05

	DC.B	$00,$FF,$FF,$FF,$FF

	ORG	RBMA + $0700 + $05

	DC.B	$0F,$FF,$FF,$FF,$FC

	ORG	RBMA + $0800 + $05

	DC.B	$3F,$FF,$FF,$FF,$F0

	ORG	RBMA + $0900 + $05

	DC.B	$3F,$FF,$FC,$3F,$FC

	ORG	RBMA + $0A00 + $05

	DC.B	$33,$FF,$30,$0F,$FF

	ORG	RBMA + $0B00 + $05

	DC.B	$F3,$FF,$30,$03,$FC

	ORG	RBMA + $0C00 + $05

	DC.B	$F3,$FF,$30,$00,$FF

	ORG	RBMA + $0D00 + $05

	DC.B	$F0,$F0,$00,$00,$3F

	ORG	RBMA + $0E00 + $05

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0F00 + $05

	DC.B	$00,$00,$00,$00,$00

; FRAME # 3  GHOST /SPR

	ORG	RBMA + $0000 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $0A

	DC.B	$00,$03,$FF,$FF,$00

	ORG	RBMA + $0200 + $0A

	DC.B	$00,$03,$00,$00,$C0

	ORG	RBMA + $0300 + $0A

	DC.B	$00,$0C,$00,$00,$30

	ORG	RBMA + $0400 + $0A

	DC.B	$00,$30,$00,$00,$0C

	ORG	RBMA + $0500 + $0A

	DC.B	$00,$30,$00,$00,$0C

	ORG	RBMA + $0600 + $0A

	DC.B	$3F,$C0,$00,$00,$03

	ORG	RBMA + $0700 + $0A

	DC.B	$F0,$00,$00,$00,$0C

	ORG	RBMA + $0800 + $0A

	DC.B	$FC,$03,$F3,$C0,$0C

	ORG	RBMA + $0900 + $0A

	DC.B	$C3,$0F,$3F,$30,$0C

	ORG	RBMA + $0A00 + $0A

	DC.B	$0C,$0C,$0F,$0C,$0C

	ORG	RBMA + $0B00 + $0A

	DC.B	$0C,$0C,$0F,$C3,$F0

	ORG	RBMA + $0C00 + $0A

	DC.B	$0F,$3C,$03,$C0,$00

	ORG	RBMA + $0D00 + $0A

	DC.B	$03,$F0,$00,$F0,$00

	ORG	RBMA + $0E00 + $0A

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0F00 + $0A

	DC.B	$00,$00,$00,$00,$00

; FRAME # 4  GHOST /SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$3C,$00,$3F,$FC,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$3F,$03,$FF,$FF,$C0

	ORG	RBMA + $0300 + $0F

	DC.B	$3F,$0F,$FF,$FF,$F0

	ORG	RBMA + $0400 + $0F

	DC.B	$0F,$FF,$FF,$FF,$FC

	ORG	RBMA + $0500 + $0F

	DC.B	$03,$FF,$FF,$FF,$FC

	ORG	RBMA + $0600 + $0F

	DC.B	$00,$FF,$FF,$FF,$CC

	ORG	RBMA + $0700 + $0F

	DC.B	$3C,$FF,$FF,$FF,$F0

	ORG	RBMA + $0800 + $0F

	DC.B	$FF,$FF,$FF,$FF,$F0

	ORG	RBMA + $0900 + $0F

	DC.B	$FF,$FF,$FF,$C3,$FC

	ORG	RBMA + $0A00 + $0F

	DC.B	$FF,$FF,$FF,$C3,$FC

	ORG	RBMA + $0B00 + $0F

	DC.B	$FF,$FC,$3F,$FC,$F0

	ORG	RBMA + $0C00 + $0F

	DC.B	$3F,$00,$00,$3F,$00

	ORG	RBMA + $0D00 + $0F

	DC.B	$00,$00,$00,$0C,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0F00 + $0F

	DC.B	$00,$00,$00,$00,$00

; FRAME # 5  GHOST /SPR

	ORG	RBMA + $0000 + $14

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $14

	DC.B	$30,$00,$0F,$FC,$00

	ORG	RBMA + $0200 + $14

	DC.B	$0C,$00,$F0,$03,$C0

	ORG	RBMA + $0300 + $14

	DC.B	$3F,$0F,$00,$00,$3C

	ORG	RBMA + $0400 + $14

	DC.B	$0F,$F0,$00,$00,$0C

	ORG	RBMA + $0500 + $14

	DC.B	$03,$00,$00,$00,$03

	ORG	RBMA + $0600 + $14

	DC.B	$00,$C0,$00,$00,$0C

	ORG	RBMA + $0700 + $14

	DC.B	$3C,$C0,$00,$00,$0C

	ORG	RBMA + $0800 + $14

	DC.B	$C3,$00,$00,$FF,$0C

	ORG	RBMA + $0900 + $14

	DC.B	$C0,$00,$03,$C3,$0C

	ORG	RBMA + $0A00 + $14

	DC.B	$C0,$03,$FC,$00,$CC

	ORG	RBMA + $0B00 + $14

	DC.B	$30,$FC,$0C,$30,$F0

	ORG	RBMA + $0C00 + $14

	DC.B	$0F,$00,$0C,$F0,$00

	ORG	RBMA + $0D00 + $14

	DC.B	$00,$00,$0F,$F0,$00

	ORG	RBMA + $0E00 + $14

	DC.B	$00,$00,$03,$F0,$00

	ORG	RBMA + $0F00 + $14

	DC.B	$00,$00,$00,$00,$00

; FRAME # 6  GHOST /SPR

	ORG	RBMA + $0000 + $19

	DC.B	$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $19

	DC.B	$3F,$C0,$0F,$FC,$00

	ORG	RBMA + $0200 + $19

	DC.B	$FF,$F3,$FF,$FF,$00

	ORG	RBMA + $0300 + $19

	DC.B	$F3,$FF,$FF,$FF,$F0

	ORG	RBMA + $0400 + $19

	DC.B	$03,$FF,$FF,$FF,$FC

	ORG	RBMA + $0500 + $19

	DC.B	$00,$FF,$FF,$FF,$FC

	ORG	RBMA + $0600 + $19

	DC.B	$03,$FF,$FF,$FF,$FF

	ORG	RBMA + $0700 + $19

	DC.B	$0F,$FF,$FF,$FF,$FF

	ORG	RBMA + $0800 + $19

	DC.B	$3F,$FF,$FF,$FF,$FC

	ORG	RBMA + $0900 + $19

	DC.B	$FF,$FF,$FF,$FF,$FC

	ORG	RBMA + $0A00 + $19

	DC.B	$FF,$FF,$FF,$FF,$FF

	ORG	RBMA + $0B00 + $19

	DC.B	$FF,$F0,$3F,$FF,$FF

	ORG	RBMA + $0C00 + $19

	DC.B	$FF,$C0,$FC,$3F,$FF

	ORG	RBMA + $0D00 + $19

	DC.B	$FF,$0F,$F0,$0F,$F0

	ORG	RBMA + $0E00 + $19

	DC.B	$3C,$3F,$00,$03,$FC

	ORG	RBMA + $0F00 + $19

	DC.B	$00,$00,$00,$00,$F0

	.END
