; FRAME # 1  MAN   /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$02,$A8,$00

	ORG	RBMA + $0700

	DC.B	$02,$A8,$00

	ORG	RBMA + $0800

	DC.B	$02,$82,$80

	ORG	RBMA + $0900

	DC.B	$02,$82,$80

	ORG	RBMA + $0A00

	DC.B	$03,$CA,$00

	ORG	RBMA + $0B00

	DC.B	$03,$CA,$00

	ORG	RBMA + $0C00

	DC.B	$03,$CA,$00

	ORG	RBMA + $0D00

	DC.B	$03,$CB,$00

	ORG	RBMA + $0E00

	DC.B	$0F,$CF,$00

	ORG	RBMA + $0F00

	DC.B	$0F,$C3,$C0

	ORG	RBMA + $1000

	DC.B	$0F,$C3,$C0

	ORG	RBMA + $1100

	DC.B	$0F,$EF,$C0

	ORG	RBMA + $1200

	DC.B	$0F,$EF,$C0

	ORG	RBMA + $1300

	DC.B	$0F,$EF,$C0

	ORG	RBMA + $1400

	DC.B	$0F,$FB,$00

	ORG	RBMA + $1500

	DC.B	$0F,$FB,$00

	ORG	RBMA + $1600

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1700

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1800

	DC.B	$0F,$F4,$00

	ORG	RBMA + $1900

	DC.B	$0F,$F4,$00

	ORG	RBMA + $1A00

	DC.B	$0A,$55,$00

	ORG	RBMA + $1B00

	DC.B	$0A,$55,$40

	ORG	RBMA + $1C00

	DC.B	$3D,$5C,$50

	ORG	RBMA + $1D00

	DC.B	$3D,$5C,$14

	ORG	RBMA + $1E00

	DC.B	$3D,$7C,$05

	ORG	RBMA + $1F00

	DC.B	$35,$7C,$01

	ORG	RBMA + $2000

	DC.B	$35,$7C,$00

	ORG	RBMA + $2100

	DC.B	$35,$7C,$00

	ORG	RBMA + $2200

	DC.B	$3F,$FC,$00

	ORG	RBMA + $2300

	DC.B	$3F,$FC,$00

	ORG	RBMA + $2400

	DC.B	$0F,$F0,$00

	ORG	RBMA + $2500

	DC.B	$0F,$F0,$00

	ORG	RBMA + $2600

	DC.B	$01,$40,$00

	ORG	RBMA + $2700

	DC.B	$01,$40,$00

	ORG	RBMA + $2800

	DC.B	$01,$50,$00

	ORG	RBMA + $2900

	DC.B	$01,$50,$00

	ORG	RBMA + $2A00

	DC.B	$2A,$50,$00

	ORG	RBMA + $2B00

	DC.B	$EA,$50,$00

	ORG	RBMA + $2C00

	DC.B	$FA,$A0,$00

	ORG	RBMA + $2D00

	DC.B	$3A,$A0,$00

	ORG	RBMA + $2E00

	DC.B	$0A,$80,$00

	ORG	RBMA + $2F00

	DC.B	$0A,$00,$00

; FRAME # 2  MAN   /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$0A,$82,$A8

	ORG	RBMA + $0700 + $03

	DC.B	$2A,$02,$A8

	ORG	RBMA + $0800 + $03

	DC.B	$2A,$02,$80

	ORG	RBMA + $0900 + $03

	DC.B	$28,$02,$80

	ORG	RBMA + $0A00 + $03

	DC.B	$28,$03,$C0

	ORG	RBMA + $0B00 + $03

	DC.B	$3C,$03,$C0

	ORG	RBMA + $0C00 + $03

	DC.B	$3C,$03,$C0

	ORG	RBMA + $0D00 + $03

	DC.B	$3C,$0F,$C0

	ORG	RBMA + $0E00 + $03

	DC.B	$3F,$0F,$C0

	ORG	RBMA + $0F00 + $03

	DC.B	$3F,$0F,$C0

	ORG	RBMA + $1000 + $03

	DC.B	$3F,$0F,$C0

	ORG	RBMA + $1100 + $03

	DC.B	$0F,$EF,$00

	ORG	RBMA + $1200 + $03

	DC.B	$0F,$EF,$00

	ORG	RBMA + $1300 + $03

	DC.B	$0F,$EF,$00

	ORG	RBMA + $1400 + $03

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1500 + $03

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1600 + $03

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1700 + $03

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1800 + $03

	DC.B	$0F,$FC,$00

	ORG	RBMA + $1900 + $03

	DC.B	$0F,$FC,$00

	ORG	RBMA + $1A00 + $03

	DC.B	$0A,$A8,$00

	ORG	RBMA + $1B00 + $03

	DC.B	$0A,$A8,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$3D,$55,$40

	ORG	RBMA + $1D00 + $03

	DC.B	$7D,$55,$40

	ORG	RBMA + $1E00 + $03

	DC.B	$7D,$7C,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$75,$7C,$40

	ORG	RBMA + $2000 + $03

	DC.B	$35,$7C,$40

	ORG	RBMA + $2100 + $03

	DC.B	$35,$7C,$40

	ORG	RBMA + $2200 + $03

	DC.B	$3F,$FC,$40

	ORG	RBMA + $2300 + $03

	DC.B	$3F,$FC,$40

	ORG	RBMA + $2400 + $03

	DC.B	$0F,$F0,$40

	ORG	RBMA + $2500 + $03

	DC.B	$0F,$F0,$40

	ORG	RBMA + $2600 + $03

	DC.B	$01,$40,$40

	ORG	RBMA + $2700 + $03

	DC.B	$01,$40,$40

	ORG	RBMA + $2800 + $03

	DC.B	$01,$50,$00

	ORG	RBMA + $2900 + $03

	DC.B	$01,$50,$00

	ORG	RBMA + $2A00 + $03

	DC.B	$2A,$50,$00

	ORG	RBMA + $2B00 + $03

	DC.B	$EA,$50,$00

	ORG	RBMA + $2C00 + $03

	DC.B	$FA,$A0,$00

	ORG	RBMA + $2D00 + $03

	DC.B	$3A,$A0,$00

	ORG	RBMA + $2E00 + $03

	DC.B	$0A,$80,$00

	ORG	RBMA + $2F00 + $03

	DC.B	$0A,$00,$00

; FRAME # 3  MAN   /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$2A,$80

	ORG	RBMA + $0700 + $06

	DC.B	$00,$2A,$80

	ORG	RBMA + $0800 + $06

	DC.B	$A0,$28,$00

	ORG	RBMA + $0900 + $06

	DC.B	$A0,$28,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$A0,$3C,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$A8,$3C,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$A8,$3C,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$AF,$3C,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$3F,$EC,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1000 + $06

	DC.B	$0F,$FC,$00

	ORG	RBMA + $1100 + $06

	DC.B	$03,$FC,$00

	ORG	RBMA + $1200 + $06

	DC.B	$03,$FC,$00

	ORG	RBMA + $1300 + $06

	DC.B	$0F,$FC,$00

	ORG	RBMA + $1400 + $06

	DC.B	$0F,$FC,$00

	ORG	RBMA + $1500 + $06

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1600 + $06

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1700 + $06

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1800 + $06

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1900 + $06

	DC.B	$0F,$FD,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$0A,$A5,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$0A,$95,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$3F,$54,$40

	ORG	RBMA + $1D00 + $06

	DC.B	$3D,$5C,$40

	ORG	RBMA + $1E00 + $06

	DC.B	$3D,$7C,$10

	ORG	RBMA + $1F00 + $06

	DC.B	$35,$7C,$10

	ORG	RBMA + $2000 + $06

	DC.B	$35,$7C,$04

	ORG	RBMA + $2100 + $06

	DC.B	$35,$7C,$04

	ORG	RBMA + $2200 + $06

	DC.B	$3F,$FC,$01

	ORG	RBMA + $2300 + $06

	DC.B	$3F,$FC,$01

	ORG	RBMA + $2400 + $06

	DC.B	$0F,$F0,$00

	ORG	RBMA + $2500 + $06

	DC.B	$0F,$F0,$00

	ORG	RBMA + $2600 + $06

	DC.B	$01,$40,$00

	ORG	RBMA + $2700 + $06

	DC.B	$01,$40,$00

	ORG	RBMA + $2800 + $06

	DC.B	$01,$50,$00

	ORG	RBMA + $2900 + $06

	DC.B	$01,$50,$00

	ORG	RBMA + $2A00 + $06

	DC.B	$2A,$50,$00

	ORG	RBMA + $2B00 + $06

	DC.B	$EA,$50,$00

	ORG	RBMA + $2C00 + $06

	DC.B	$FA,$A0,$00

	ORG	RBMA + $2D00 + $06

	DC.B	$3A,$A0,$00

	ORG	RBMA + $2E00 + $06

	DC.B	$0A,$80,$00

	ORG	RBMA + $2F00 + $06

	DC.B	$0A,$00,$00

; FRAME # 4  MAN   /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$02,$A8,$00

	ORG	RBMA + $0700 + $09

	DC.B	$02,$A8,$00

	ORG	RBMA + $0800 + $09

	DC.B	$02,$80,$20

	ORG	RBMA + $0900 + $09

	DC.B	$02,$80,$A0

	ORG	RBMA + $0A00 + $09

	DC.B	$03,$C2,$A0

	ORG	RBMA + $0B00 + $09

	DC.B	$03,$C2,$80

	ORG	RBMA + $0C00 + $09

	DC.B	$03,$C2,$80

	ORG	RBMA + $0D00 + $09

	DC.B	$03,$C2,$C0

	ORG	RBMA + $0E00 + $09

	DC.B	$03,$F3,$C0

	ORG	RBMA + $0F00 + $09

	DC.B	$03,$F3,$C0

	ORG	RBMA + $1000 + $09

	DC.B	$03,$F3,$F0

	ORG	RBMA + $1100 + $09

	DC.B	$03,$F3,$F0

	ORG	RBMA + $1200 + $09

	DC.B	$03,$E3,$F0

	ORG	RBMA + $1300 + $09

	DC.B	$03,$BF,$F0

	ORG	RBMA + $1400 + $09

	DC.B	$02,$FF,$F0

	ORG	RBMA + $1500 + $09

	DC.B	$0F,$FF,$C0

	ORG	RBMA + $1600 + $09

	DC.B	$0F,$55,$54

	ORG	RBMA + $1700 + $09

	DC.B	$0F,$55,$55

	ORG	RBMA + $1800 + $09

	DC.B	$0F,$58,$00

	ORG	RBMA + $1900 + $09

	DC.B	$0D,$7C,$00

	ORG	RBMA + $1A00 + $09

	DC.B	$09,$68,$00

	ORG	RBMA + $1B00 + $09

	DC.B	$09,$68,$00

	ORG	RBMA + $1C00 + $09

	DC.B	$3D,$7C,$00

	ORG	RBMA + $1D00 + $09

	DC.B	$35,$7C,$00

	ORG	RBMA + $1E00 + $09

	DC.B	$35,$7C,$00

	ORG	RBMA + $1F00 + $09

	DC.B	$35,$7C,$00

	ORG	RBMA + $2000 + $09

	DC.B	$35,$7C,$00

	ORG	RBMA + $2100 + $09

	DC.B	$35,$7C,$00

	ORG	RBMA + $2200 + $09

	DC.B	$3F,$FC,$00

	ORG	RBMA + $2300 + $09

	DC.B	$3F,$FC,$00

	ORG	RBMA + $2400 + $09

	DC.B	$0F,$F0,$00

	ORG	RBMA + $2500 + $09

	DC.B	$0F,$F0,$00

	ORG	RBMA + $2600 + $09

	DC.B	$01,$40,$00

	ORG	RBMA + $2700 + $09

	DC.B	$01,$40,$00

	ORG	RBMA + $2800 + $09

	DC.B	$01,$50,$00

	ORG	RBMA + $2900 + $09

	DC.B	$01,$50,$00

	ORG	RBMA + $2A00 + $09

	DC.B	$2A,$50,$00

	ORG	RBMA + $2B00 + $09

	DC.B	$EA,$50,$00

	ORG	RBMA + $2C00 + $09

	DC.B	$FA,$A0,$00

	ORG	RBMA + $2D00 + $09

	DC.B	$3A,$A0,$00

	ORG	RBMA + $2E00 + $09

	DC.B	$0A,$80,$00

	ORG	RBMA + $2F00 + $09

	DC.B	$0A,$00,$00

; FRAME # 5  MAN   /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$0A,$82,$A8

	ORG	RBMA + $0700 + $0C

	DC.B	$2A,$02,$A8

	ORG	RBMA + $0800 + $0C

	DC.B	$28,$02,$80

	ORG	RBMA + $0900 + $0C

	DC.B	$28,$02,$80

	ORG	RBMA + $0A00 + $0C

	DC.B	$2C,$03,$C0

	ORG	RBMA + $0B00 + $0C

	DC.B	$3C,$03,$C0

	ORG	RBMA + $0C00 + $0C

	DC.B	$3F,$03,$C0

	ORG	RBMA + $0D00 + $0C

	DC.B	$3F,$0F,$C0

	ORG	RBMA + $0E00 + $0C

	DC.B	$3F,$CF,$C0

	ORG	RBMA + $0F00 + $0C

	DC.B	$3F,$CF,$C0

	ORG	RBMA + $1000 + $0C

	DC.B	$0F,$BF,$C0

	ORG	RBMA + $1100 + $0C

	DC.B	$0F,$BF,$00

	ORG	RBMA + $1200 + $0C

	DC.B	$0E,$FF,$00

	ORG	RBMA + $1300 + $0C

	DC.B	$0E,$FD,$40

	ORG	RBMA + $1400 + $0C

	DC.B	$0B,$F5,$00

	ORG	RBMA + $1500 + $0C

	DC.B	$0F,$D4,$00

	ORG	RBMA + $1600 + $0C

	DC.B	$0F,$5C,$00

	ORG	RBMA + $1700 + $0C

	DC.B	$0D,$7C,$00

	ORG	RBMA + $1800 + $0C

	DC.B	$05,$FC,$00

	ORG	RBMA + $1900 + $0C

	DC.B	$15,$FC,$00

	ORG	RBMA + $1A00 + $0C

	DC.B	$15,$A8,$00

	ORG	RBMA + $1B00 + $0C

	DC.B	$16,$A8,$50

	ORG	RBMA + $1C00 + $0C

	DC.B	$57,$FD,$50

	ORG	RBMA + $1D00 + $0C

	DC.B	$57,$FD,$40

	ORG	RBMA + $1E00 + $0C

	DC.B	$57,$FD,$00

	ORG	RBMA + $1F00 + $0C

	DC.B	$55,$FC,$00

	ORG	RBMA + $2000 + $0C

	DC.B	$15,$FC,$00

	ORG	RBMA + $2100 + $0C

	DC.B	$17,$FC,$00

	ORG	RBMA + $2200 + $0C

	DC.B	$3F,$FC,$00

	ORG	RBMA + $2300 + $0C

	DC.B	$3F,$FC,$00

	ORG	RBMA + $2400 + $0C

	DC.B	$0F,$F0,$00

	ORG	RBMA + $2500 + $0C

	DC.B	$0F,$F0,$00

	ORG	RBMA + $2600 + $0C

	DC.B	$01,$40,$00

	ORG	RBMA + $2700 + $0C

	DC.B	$01,$40,$00

	ORG	RBMA + $2800 + $0C

	DC.B	$01,$50,$00

	ORG	RBMA + $2900 + $0C

	DC.B	$01,$50,$00

	ORG	RBMA + $2A00 + $0C

	DC.B	$2A,$50,$00

	ORG	RBMA + $2B00 + $0C

	DC.B	$EA,$50,$00

	ORG	RBMA + $2C00 + $0C

	DC.B	$FA,$A0,$00

	ORG	RBMA + $2D00 + $0C

	DC.B	$3A,$A0,$00

	ORG	RBMA + $2E00 + $0C

	DC.B	$0A,$80,$00

	ORG	RBMA + $2F00 + $0C

	DC.B	$0A,$00,$00

; FRAME # 6  MAN   /SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0F

	DC.B	$00,$2A,$80

	ORG	RBMA + $0700 + $0F

	DC.B	$00,$2A,$80

	ORG	RBMA + $0800 + $0F

	DC.B	$28,$28,$00

	ORG	RBMA + $0900 + $0F

	DC.B	$28,$28,$00

	ORG	RBMA + $0A00 + $0F

	DC.B	$A0,$3C,$00

	ORG	RBMA + $0B00 + $0F

	DC.B	$A8,$3C,$00

	ORG	RBMA + $0C00 + $0F

	DC.B	$A8,$3C,$00

	ORG	RBMA + $0D00 + $0F

	DC.B	$2C,$3C,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$3F,$BC,$00

	ORG	RBMA + $0F00 + $0F

	DC.B	$0F,$BC,$00

	ORG	RBMA + $1000 + $0F

	DC.B	$0F,$FC,$00

	ORG	RBMA + $1100 + $0F

	DC.B	$03,$FC,$00

	ORG	RBMA + $1200 + $0F

	DC.B	$03,$FC,$00

	ORG	RBMA + $1300 + $0F

	DC.B	$03,$FC,$00

	ORG	RBMA + $1400 + $0F

	DC.B	$0F,$FC,$00

	ORG	RBMA + $1500 + $0F

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1600 + $0F

	DC.B	$0F,$F8,$00

	ORG	RBMA + $1700 + $0F

	DC.B	$0F,$55,$54

	ORG	RBMA + $1800 + $0F

	DC.B	$0F,$55,$55

	ORG	RBMA + $1900 + $0F

	DC.B	$0D,$5C,$00

	ORG	RBMA + $1A00 + $0F

	DC.B	$09,$68,$00

	ORG	RBMA + $1B00 + $0F

	DC.B	$09,$68,$00

	ORG	RBMA + $1C00 + $0F

	DC.B	$3D,$7C,$00

	ORG	RBMA + $1D00 + $0F

	DC.B	$3D,$7C,$00

	ORG	RBMA + $1E00 + $0F

	DC.B	$35,$7C,$00

	ORG	RBMA + $1F00 + $0F

	DC.B	$35,$7C,$00

	ORG	RBMA + $2000 + $0F

	DC.B	$35,$7C,$00

	ORG	RBMA + $2100 + $0F

	DC.B	$35,$7C,$00

	ORG	RBMA + $2200 + $0F

	DC.B	$3F,$FC,$00

	ORG	RBMA + $2300 + $0F

	DC.B	$3F,$FC,$00

	ORG	RBMA + $2400 + $0F

	DC.B	$0F,$F0,$00

	ORG	RBMA + $2500 + $0F

	DC.B	$0F,$F0,$00

	ORG	RBMA + $2600 + $0F

	DC.B	$01,$40,$00

	ORG	RBMA + $2700 + $0F

	DC.B	$01,$40,$00

	ORG	RBMA + $2800 + $0F

	DC.B	$01,$50,$00

	ORG	RBMA + $2900 + $0F

	DC.B	$01,$50,$00

	ORG	RBMA + $2A00 + $0F

	DC.B	$2A,$50,$00

	ORG	RBMA + $2B00 + $0F

	DC.B	$EA,$50,$00

	ORG	RBMA + $2C00 + $0F

	DC.B	$FA,$A0,$00

	ORG	RBMA + $2D00 + $0F

	DC.B	$3A,$A0,$00

	ORG	RBMA + $2E00 + $0F

	DC.B	$0A,$80,$00

	ORG	RBMA + $2F00 + $0F

	DC.B	$0A,$00,$00

	.END
