; FRAME # 1  ICE   /SPR

	ORG	RBMA + $0000

	DC.B	$00,$80,$00

	ORG	RBMA + $0100

	DC.B	$00,$80,$00

	ORG	RBMA + $0200

	DC.B	$02,$80,$00

	ORG	RBMA + $0300

	DC.B	$02,$B0,$00

	ORG	RBMA + $0400

	DC.B	$02,$F0,$00

	ORG	RBMA + $0500

	DC.B	$02,$70,$00

	ORG	RBMA + $0600

	DC.B	$02,$5C,$00

	ORG	RBMA + $0700

	DC.B	$02,$5C,$00

	ORG	RBMA + $0800

	DC.B	$0B,$5F,$00

	ORG	RBMA + $0900

	DC.B	$0B,$9F,$00

	ORG	RBMA + $0A00

	DC.B	$0B,$BF,$00

	ORG	RBMA + $0B00

	DC.B	$2A,$0C,$C0

	ORG	RBMA + $0C00

	DC.B	$30,$40,$00

	ORG	RBMA + $0D00

	DC.B	$40,$00,$40

	ORG	RBMA + $0E00

	DC.B	$30,$43,$00

	ORG	RBMA + $0F00

	DC.B	$03,$00,$00

; FRAME # 2  ICE   /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$80,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$80,$00

	ORG	RBMA + $0200 + $03

	DC.B	$02,$80,$00

	ORG	RBMA + $0300 + $03

	DC.B	$02,$B0,$00

	ORG	RBMA + $0400 + $03

	DC.B	$02,$F0,$00

	ORG	RBMA + $0500 + $03

	DC.B	$02,$70,$00

	ORG	RBMA + $0600 + $03

	DC.B	$02,$5C,$00

	ORG	RBMA + $0700 + $03

	DC.B	$02,$5C,$00

	ORG	RBMA + $0800 + $03

	DC.B	$0B,$5F,$00

	ORG	RBMA + $0900 + $03

	DC.B	$08,$9F,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$0B,$BF,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$28,$04,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$10,$C0,$30

	ORG	RBMA + $0D00 + $03

	DC.B	$04,$10,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$C0,$C4,$C0

	ORG	RBMA + $0F00 + $03

	DC.B	$0C,$00,$00

; FRAME # 3  ICE   /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$03,$00

	ORG	RBMA + $0200 + $06

	DC.B	$10,$01,$00

	ORG	RBMA + $0300 + $06

	DC.B	$01,$04,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$40

	ORG	RBMA + $0500 + $06

	DC.B	$01,$01,$00

	ORG	RBMA + $0600 + $06

	DC.B	$30,$00,$CC

	ORG	RBMA + $0700 + $06

	DC.B	$00,$01,$00

	ORG	RBMA + $0800 + $06

	DC.B	$04,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$40,$03,$10

	ORG	RBMA + $0A00 + $06

	DC.B	$01,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00,$C0

	ORG	RBMA + $0C00 + $06

	DC.B	$10,$C4,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$C0,$C0,$C0

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

	.END
