	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$02,$AA,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00,$00
	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$2A,$AA,$A0,$2A,$AA,$80,$00,$00,$00,$00,$00,$00,$00,$00
	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$AA,$AA,$AA,$AA,$AA,$A0,$00,$00,$AA,$80,$00,$00,$00,$2A
	DC.B	$A0,$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$AA,$AA,$AA,$AA,$AA,$AA,$A0,$02,$AA,$A0,$00,$00,$00,$AA
	DC.B	$A8,$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$2A,$02,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$A2,$AA,$A0,$00,$00,$00,$AA
	DC.B	$A8,$A8,$2A,$00

	ORG	RBMA + $0A00

	DC.B	$AA,$82,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$8A,$80,$0A,$AA
	DC.B	$AA,$AA,$AA,$8A

	ORG	RBMA + $0B00

	DC.B	$AA,$8A,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$A0,$2A,$AA
	DC.B	$AA,$AA,$AA,$AA

	ORG	RBMA + $0C00

	DC.B	$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA
	DC.B	$AA,$AA,$AA,$AA

	ORG	RBMA + $0D00

	DC.B	$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA
	DC.B	$AA,$AA,$AA,$AA

	ORG	RBMA + $0E00

	DC.B	$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA
	DC.B	$AA,$AA,$AA,$AA

	ORG	RBMA + $0F00

	DC.B	$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA,$AA
	DC.B	$AA,$AA,$AA,$AA

	.END
