; FRAME # 1  BAG   /SPR

	ORG	RBMA + $0000

	DC.B	$02,$AA,$00

	ORG	RBMA + $0100

	DC.B	$0A,$9A,$80

	ORG	RBMA + $0200

	DC.B	$0A,$56,$80

	ORG	RBMA + $0300

	DC.B	$29,$99,$A0

	ORG	RBMA + $0400

	DC.B	$2A,$99,$A0

	ORG	RBMA + $0500

	DC.B	$2A,$56,$A0

	ORG	RBMA + $0600

	DC.B	$29,$9A,$A0

	ORG	RBMA + $0700

	DC.B	$09,$99,$80

	ORG	RBMA + $0800

	DC.B	$0A,$56,$80

	ORG	RBMA + $0900

	DC.B	$02,$9A,$00

	ORG	RBMA + $0A00

	DC.B	$02,$AA,$00

	ORG	RBMA + $0B00

	DC.B	$08,$54,$80

	ORG	RBMA + $0C00

	DC.B	$20,$A8,$20

	ORG	RBMA + $0D00

	DC.B	$82,$A8,$08

	ORG	RBMA + $0E00

	DC.B	$20,$00,$00

	ORG	RBMA + $0F00

	DC.B	$88,$88,$20

	.END
