; FRAME # 1  LTNING/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

	ORG	RBMA + $1000

	DC.B	$00,$00,$00

	ORG	RBMA + $1100

	DC.B	$00,$00,$00

	ORG	RBMA + $1200

	DC.B	$00,$00,$00

	ORG	RBMA + $1300

	DC.B	$00,$00,$00

	ORG	RBMA + $1400

	DC.B	$03,$00,$00

	ORG	RBMA + $1500

	DC.B	$00,$C0,$00

	ORG	RBMA + $1600

	DC.B	$00,$F0,$00

	ORG	RBMA + $1700

	DC.B	$00,$30,$00

	ORG	RBMA + $1800

	DC.B	$00,$3C,$00

	ORG	RBMA + $1900

	DC.B	$00,$0F,$00

	ORG	RBMA + $1A00

	DC.B	$00,$03,$00

	ORG	RBMA + $1B00

	DC.B	$00,$03,$00

	ORG	RBMA + $1C00

	DC.B	$00,$03,$00

	ORG	RBMA + $1D00

	DC.B	$00,$03,$00

	ORG	RBMA + $1E00

	DC.B	$00,$03,$00

	ORG	RBMA + $1F00

	DC.B	$00,$0F,$C0

	ORG	RBMA + $2000

	DC.B	$00,$0C,$C0

	ORG	RBMA + $2100

	DC.B	$00,$0C,$C0

	ORG	RBMA + $2200

	DC.B	$00,$0C,$C0

	ORG	RBMA + $2300

	DC.B	$00,$0C,$30

	ORG	RBMA + $2400

	DC.B	$00,$3C,$3C

	ORG	RBMA + $2500

	DC.B	$00,$3C,$0C

	ORG	RBMA + $2600

	DC.B	$00,$FC,$0F

	ORG	RBMA + $2700

	DC.B	$03,$CC,$03

	ORG	RBMA + $2800

	DC.B	$0F,$0C,$03

	ORG	RBMA + $2900

	DC.B	$3C,$0C,$03

	ORG	RBMA + $2A00

	DC.B	$F0,$0C,$03

	ORG	RBMA + $2B00

	DC.B	$C0,$0C,$03

	ORG	RBMA + $2C00

	DC.B	$C0,$0C,$03

	ORG	RBMA + $2D00

	DC.B	$C0,$03,$03

	ORG	RBMA + $2E00

	DC.B	$C0,$03,$00

	ORG	RBMA + $2F00

	DC.B	$C0,$00,$00

	.END
