	ORG	RBMA + $0000

	DC.B	$05,$55,$6A,$AA,$AA,$80,$00

	ORG	RBMA + $0100

	DC.B	$16,$AA,$AA,$AA,$AA,$A8,$00

	ORG	RBMA + $0200

	DC.B	$56,$AA,$AA,$AA,$AA,$AA,$00

	ORG	RBMA + $0300

	DC.B	$5F,$AA,$AA,$BE,$FF,$AA,$80

	ORG	RBMA + $0400

	DC.B	$7F,$AA,$AF,$FF,$FF,$FA,$80

	ORG	RBMA + $0500

	DC.B	$1F,$44,$4F,$FF,$D5,$5E,$80

	ORG	RBMA + $0600

	DC.B	$0F,$15,$11,$FF,$55,$5A,$00

	ORG	RBMA + $0700

	DC.B	$03,$44,$45,$7D,$55,$58,$00

	ORG	RBMA + $0800

	DC.B	$00,$15,$11,$55,$55,$50,$00

	ORG	RBMA + $0900

	DC.B	$00,$44,$45,$55,$55,$50,$00

	ORG	RBMA + $0A00

	DC.B	$00,$15,$11,$55,$55,$50,$00

	ORG	RBMA + $0B00

	DC.B	$00,$44,$45,$55,$55,$50,$00

	ORG	RBMA + $0C00

	DC.B	$00,$15,$11,$55,$55,$50,$00

	ORG	RBMA + $0D00

	DC.B	$00,$54,$45,$55,$55,$50,$00

	ORG	RBMA + $0E00

	DC.B	$00,$11,$51,$55,$55,$50,$00

	ORG	RBMA + $0F00

	DC.B	$00,$44,$45,$55,$55,$50,$00

	ORG	RBMA + $0000 + $07

	DC.B	$00,$11,$11,$55,$55,$50,$00

	ORG	RBMA + $0100 + $07

	DC.B	$00,$44,$45,$55,$55,$50,$00

	ORG	RBMA + $0200 + $07

	DC.B	$00,$11,$11,$55,$55,$50,$00

	ORG	RBMA + $0300 + $07

	DC.B	$00,$44,$45,$55,$55,$50,$00

	ORG	RBMA + $0400 + $07

	DC.B	$00,$11,$11,$55,$55,$50,$00

	ORG	RBMA + $0500 + $07

	DC.B	$00,$FC,$45,$55,$55,$50,$00

	ORG	RBMA + $0600 + $07

	DC.B	$00,$FF,$D1,$55,$55,$50,$00

	ORG	RBMA + $0700 + $07

	DC.B	$00,$FF,$F5,$55,$55,$50,$00

	ORG	RBMA + $0800 + $07

	DC.B	$03,$FF,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $0900 + $07

	DC.B	$03,$FF,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $0A00 + $07

	DC.B	$03,$FF,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $0B00 + $07

	DC.B	$03,$FC,$CF,$FF,$FF,$FC,$00

	ORG	RBMA + $0C00 + $07

	DC.B	$03,$FC,$CF,$FF,$33,$3F,$00

	ORG	RBMA + $0D00 + $07

	DC.B	$00,$FC,$0F,$FF,$33,$3F,$00

	ORG	RBMA + $0E00 + $07

	DC.B	$00,$FC,$0F,$FC,$00,$3F,$00

	ORG	RBMA + $0F00 + $07

	DC.B	$00,$FC,$0F,$FC,$00,$3F,$00

	ORG	RBMA + $0000 + $0E

	DC.B	$00,$FC,$0F,$FC,$00,$3F,$00

	ORG	RBMA + $0100 + $0E

	DC.B	$00,$30,$0F,$FC,$00,$3F,$00

	ORG	RBMA + $0200 + $0E

	DC.B	$00,$30,$0F,$FC,$00,$3F,$00

	ORG	RBMA + $0300 + $0E

	DC.B	$00,$30,$0F,$FC,$00,$3F,$00

	ORG	RBMA + $0400 + $0E

	DC.B	$00,$30,$0F,$FC,$00,$0C,$00

	ORG	RBMA + $0500 + $0E

	DC.B	$00,$30,$0F,$FC,$00,$0C,$00

	ORG	RBMA + $0600 + $0E

	DC.B	$00,$00,$03,$F0,$00,$0C,$00

	ORG	RBMA + $0700 + $0E

	DC.B	$00,$00,$03,$F0,$00,$0C,$00

	ORG	RBMA + $0800 + $0E

	DC.B	$00,$00,$03,$F0,$00,$0C,$00

	ORG	RBMA + $0900 + $0E

	DC.B	$00,$00,$03,$F0,$00,$0C,$00

	ORG	RBMA + $0A00 + $0E

	DC.B	$00,$00,$00,$C0,$00,$0C,$00

	ORG	RBMA + $0B00 + $0E

	DC.B	$00,$00,$00,$C0,$00,$00,$00

	ORG	RBMA + $0C00 + $0E

	DC.B	$00,$00,$00,$C0,$00,$00,$00

	ORG	RBMA + $0D00 + $0E

	DC.B	$00,$00,$00,$C0,$00,$00,$00

	ORG	RBMA + $0E00 + $0E

	DC.B	$00,$00,$00,$C0,$00,$00,$00

	ORG	RBMA + $0F00 + $0E

	DC.B	$00,$00,$00,$C0,$00,$00,$00

	.END
