	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$14,$00,$00

	ORG	RBMA + $0200

	DC.B	$14,$00,$50

	ORG	RBMA + $0300

	DC.B	$10,$00,$40

	ORG	RBMA + $0400

	DC.B	$20,$00,$40

	ORG	RBMA + $0500

	DC.B	$28,$00,$80

	ORG	RBMA + $0600

	DC.B	$0A,$00,$A0

	ORG	RBMA + $0700

	DC.B	$0A,$00,$A0

	ORG	RBMA + $0800

	DC.B	$02,$82,$A0

	ORG	RBMA + $0900

	DC.B	$42,$8A,$80

	ORG	RBMA + $0A00

	DC.B	$12,$AA,$80

	ORG	RBMA + $0B00

	DC.B	$04,$AA,$00

	ORG	RBMA + $0C00

	DC.B	$01,$AA,$00

	ORG	RBMA + $0D00

	DC.B	$00,$68,$00

	ORG	RBMA + $0E00

	DC.B	$02,$FC,$00

	ORG	RBMA + $0F00

	DC.B	$08,$54,$00

	ORG	RBMA + $0000 + $03

	DC.B	$20,$FC,$00

	ORG	RBMA + $0100 + $03

	DC.B	$28,$FF,$2A

	ORG	RBMA + $0200 + $03

	DC.B	$28,$FF,$A2

	ORG	RBMA + $0300 + $03

	DC.B	$0A,$FF,$E0

	ORG	RBMA + $0400 + $03

	DC.B	$0F,$FF,$C0

	ORG	RBMA + $0500 + $03

	DC.B	$03,$FF,$00

	ORG	RBMA + $0600 + $03

	DC.B	$03,$FC,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$F0,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$20,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$28,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$28,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$28,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$DB,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$01,$7C,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

	.END
