	ORG	RBMA + $0000

	DC.B	$00,$3F,$C0,$00,$02,$00,$00,$02,$FF,$F0

	ORG	RBMA + $0100

	DC.B	$00,$BF,$FC,$00,$0A,$80,$00,$09,$FF,$FC

	ORG	RBMA + $0200

	DC.B	$02,$7F,$FF,$F0,$AA,$A0,$66,$66,$FF,$FC

	ORG	RBMA + $0300

	DC.B	$19,$BF,$FF,$F2,$AA,$A9,$99,$99,$FF,$FC

	ORG	RBMA + $0400

	DC.B	$66,$7F,$FF,$F2,$AA,$26,$66,$66,$55,$54

	ORG	RBMA + $0500

	DC.B	$99,$BF,$FF,$FA,$82,$19,$99,$AA,$55,$50

	ORG	RBMA + $0600

	DC.B	$66,$7F,$FF,$FA,$82,$26,$6A,$AA,$95,$40

	ORG	RBMA + $0700

	DC.B	$99,$BF,$FF,$EA,$80,$19,$AA,$A2,$A5,$00

	ORG	RBMA + $0800

	DC.B	$66,$7F,$FF,$F2,$00,$2A,$AA,$A0,$A4,$00

	ORG	RBMA + $0900

	DC.B	$99,$BF,$FF,$F2,$00,$0A,$AA,$A0,$20,$00

	ORG	RBMA + $0A00

	DC.B	$AA,$95,$55,$50,$00,$02,$AA,$A0,$00,$00

	ORG	RBMA + $0B00

	DC.B	$AA,$95,$55,$50,$00,$00,$A0,$0A,$80,$00

	ORG	RBMA + $0C00

	DC.B	$AA,$54,$55,$50,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$2A,$50,$55,$50,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$29,$50,$55,$7B,$F5,$FC,$28,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$09,$50,$55,$7B,$F5,$FD,$48,$00,$00,$00

	ORG	RBMA + $0000 + $0A

	DC.B	$09,$50,$55,$FB,$F5,$FD,$48,$FD,$7F,$40

	ORG	RBMA + $0100 + $0A

	DC.B	$00,$00,$3F,$FB,$F5,$FD,$48,$FD,$7F,$50

	ORG	RBMA + $0200 + $0A

	DC.B	$00,$0A,$3D,$DB,$F5,$FD,$48,$FD,$7F,$54

	ORG	RBMA + $0300 + $0A

	DC.B	$00,$00,$3F,$FB,$FF,$FD,$48,$FD,$7F,$54

	ORG	RBMA + $0400 + $0A

	DC.B	$00,$00,$3F,$FB,$DF,$7D,$48,$FD,$7F,$54

	ORG	RBMA + $0500 + $0A

	DC.B	$00,$00,$2A,$AB,$FF,$FD,$48,$FF,$FF,$54

	ORG	RBMA + $0600 + $0A

	DC.B	$00,$00,$2A,$AB,$FF,$FD,$48,$F7,$DF,$54

	ORG	RBMA + $0700 + $0A

	DC.B	$00,$00,$0A,$AA,$AA,$A9,$68,$F7,$DF,$54

	ORG	RBMA + $0800 + $0A

	DC.B	$00,$00,$02,$A0,$AA,$A9,$48,$FF,$FF,$54

	ORG	RBMA + $0900 + $0A

	DC.B	$00,$00,$00,$80,$2A,$A5,$00,$FF,$FF,$54

	ORG	RBMA + $0A00 + $0A

	DC.B	$00,$00,$00,$00,$0A,$94,$00,$AA,$AA,$54

	ORG	RBMA + $0B00 + $0A

	DC.B	$00,$00,$00,$00,$02,$50,$00,$2A,$AA,$50

	ORG	RBMA + $0C00 + $0A

	DC.B	$00,$00,$00,$00,$00,$40,$00,$0A,$A9,$40

	ORG	RBMA + $0D00 + $0A

	DC.B	$00,$00,$00,$00,$00,$00,$00,$02,$A5,$00

	ORG	RBMA + $0E00 + $0A

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$94,$00

	ORG	RBMA + $0F00 + $0A

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00,$10,$00

	.END
