;mite 1
	ORG	RBMA + $0000

	DC.B	$AB,$FF,$F0

	ORG	RBMA + $0100

	DC.B	$AB,$FF,$F0

	ORG	RBMA + $0200

	DC.B	$AB,$FF,$F0

	ORG	RBMA + $0300

	DC.B	$AA,$FF,$F0

	ORG	RBMA + $0400

	DC.B	$2A,$FF,$F0

	ORG	RBMA + $0500

	DC.B	$2A,$BF,$F0

	ORG	RBMA + $0600

	DC.B	$2A,$BF,$F0

	ORG	RBMA + $0700

	DC.B	$0A,$BF,$F0

	ORG	RBMA + $0800

	DC.B	$0A,$AF,$F0

	ORG	RBMA + $0900

	DC.B	$0A,$AF,$F0

	ORG	RBMA + $0A00

	DC.B	$0A,$AF,$C0

	ORG	RBMA + $0B00

	DC.B	$02,$AF,$C0

	ORG	RBMA + $0C00

	DC.B	$02,$AF,$C0

	ORG	RBMA + $0D00

	DC.B	$02,$AB,$C0

	ORG	RBMA + $0E00

	DC.B	$02,$AB,$C0

	ORG	RBMA + $0F00

	DC.B	$00,$AB,$C0

	ORG	RBMA + $0000 + $03

	DC.B	$00,$AB,$C0

	ORG	RBMA + $0100 + $03

	DC.B	$00,$AB,$C0

	ORG	RBMA + $0200 + $03

	DC.B	$00,$AB,$C0

	ORG	RBMA + $0300 + $03

	DC.B	$00,$AB,$C0

	ORG	RBMA + $0400 + $03

	DC.B	$00,$AB,$C0

	ORG	RBMA + $0500 + $03

	DC.B	$00,$2B,$C0

	ORG	RBMA + $0600 + $03

	DC.B	$00,$2B,$C0

	ORG	RBMA + $0700 + $03

	DC.B	$00,$0B,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$0B,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$0B,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$08,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$08,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$08,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$08,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

	.END
