	ORG	RBMA + $0000

	DC.B	$AB,$FF,$F0

	ORG	RBMA + $0100

	DC.B	$AB,$FF,$F0

	ORG	RBMA + $0200

	DC.B	$AB,$FF,$F0

	ORG	RBMA + $0300

	DC.B	$AA,$FF,$C0

	ORG	RBMA + $0400

	DC.B	$2A,$FF,$C0

	ORG	RBMA + $0500

	DC.B	$2A,$BF,$00

	ORG	RBMA + $0600

	DC.B	$2A,$BF,$00

	ORG	RBMA + $0700

	DC.B	$0A,$BF,$00

	ORG	RBMA + $0800

	DC.B	$0A,$BF,$00

	ORG	RBMA + $0900

	DC.B	$0A,$BC,$00

	ORG	RBMA + $0A00

	DC.B	$02,$BC,$00

	ORG	RBMA + $0B00

	DC.B	$02,$B0,$00

	ORG	RBMA + $0C00

	DC.B	$02,$B0,$00

	ORG	RBMA + $0D00

	DC.B	$00,$B0,$00

	ORG	RBMA + $0E00

	DC.B	$00,$80,$00

	ORG	RBMA + $0F00

	DC.B	$00,$80,$00

	.END
