; FRAME # 1  MONKEY/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$40

	ORG	RBMA + $0300

	DC.B	$02,$80,$50

	ORG	RBMA + $0400

	DC.B	$0A,$A2,$90

	ORG	RBMA + $0500

	DC.B	$2A,$AA,$80

	ORG	RBMA + $0600

	DC.B	$2A,$AA,$00

	ORG	RBMA + $0700

	DC.B	$2A,$9A,$10

	ORG	RBMA + $0800

	DC.B	$2A,$90,$90

	ORG	RBMA + $0900

	DC.B	$2A,$9A,$90

	ORG	RBMA + $0A00

	DC.B	$0A,$A6,$80

	ORG	RBMA + $0B00

	DC.B	$0A,$A4,$00

	ORG	RBMA + $0C00

	DC.B	$01,$A8,$00

	ORG	RBMA + $0D00

	DC.B	$0A,$EA,$00

	ORG	RBMA + $0E00

	DC.B	$0A,$BA,$00

	ORG	RBMA + $0F00

	DC.B	$2A,$A6,$80

	ORG	RBMA + $1000

	DC.B	$2D,$A9,$A0

	ORG	RBMA + $1100

	DC.B	$2F,$D8,$90

	ORG	RBMA + $1200

	DC.B	$2A,$F8,$50

	ORG	RBMA + $1300

	DC.B	$0A,$A8,$00

	ORG	RBMA + $1400

	DC.B	$02,$A0,$00

	ORG	RBMA + $1500

	DC.B	$00,$00,$00

	ORG	RBMA + $1600

	DC.B	$00,$00,$00

	ORG	RBMA + $1700

	DC.B	$00,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00

; FRAME # 2  MONKEY/SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$40

	ORG	RBMA + $0200 + $03

	DC.B	$00,$02,$50

	ORG	RBMA + $0300 + $03

	DC.B	$02,$8A,$90

	ORG	RBMA + $0400 + $03

	DC.B	$0A,$AA,$80

	ORG	RBMA + $0500 + $03

	DC.B	$2A,$AA,$00

	ORG	RBMA + $0600 + $03

	DC.B	$2A,$A8,$00

	ORG	RBMA + $0700 + $03

	DC.B	$2A,$90,$00

	ORG	RBMA + $0800 + $03

	DC.B	$29,$50,$00

	ORG	RBMA + $0900 + $03

	DC.B	$2A,$A6,$80

	ORG	RBMA + $0A00 + $03

	DC.B	$0A,$A9,$90

	ORG	RBMA + $0B00 + $03

	DC.B	$0A,$AA,$50

	ORG	RBMA + $0C00 + $03

	DC.B	$02,$9A,$80

	ORG	RBMA + $0D00 + $03

	DC.B	$0A,$E6,$90

	ORG	RBMA + $0E00 + $03

	DC.B	$0B,$E8,$50

	ORG	RBMA + $0F00 + $03

	DC.B	$0B,$A8,$10

	ORG	RBMA + $1000 + $03

	DC.B	$0A,$AA,$00

	ORG	RBMA + $1100 + $03

	DC.B	$09,$9A,$00

	ORG	RBMA + $1200 + $03

	DC.B	$0B,$BA,$00

	ORG	RBMA + $1300 + $03

	DC.B	$02,$A8,$00

	ORG	RBMA + $1400 + $03

	DC.B	$00,$A8,$00

	ORG	RBMA + $1500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  MONKEY/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$02,$50

	ORG	RBMA + $0100 + $06

	DC.B	$00,$02,$90

	ORG	RBMA + $0200 + $06

	DC.B	$00,$0A,$80

	ORG	RBMA + $0300 + $06

	DC.B	$00,$AA,$00

	ORG	RBMA + $0400 + $06

	DC.B	$02,$AA,$00

	ORG	RBMA + $0500 + $06

	DC.B	$0A,$A8,$00

	ORG	RBMA + $0600 + $06

	DC.B	$0A,$A0,$00

	ORG	RBMA + $0700 + $06

	DC.B	$0A,$92,$90

	ORG	RBMA + $0800 + $06

	DC.B	$0A,$6A,$90

	ORG	RBMA + $0900 + $06

	DC.B	$09,$AA,$90

	ORG	RBMA + $0A00 + $06

	DC.B	$0A,$A0,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$0A,$90,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$01,$58,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$0A,$9A,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$2A,$A6,$80

	ORG	RBMA + $0F00 + $06

	DC.B	$2A,$A9,$90

	ORG	RBMA + $1000 + $06

	DC.B	$2A,$AA,$50

	ORG	RBMA + $1100 + $06

	DC.B	$09,$9A,$10

	ORG	RBMA + $1200 + $06

	DC.B	$0B,$BA,$00

	ORG	RBMA + $1300 + $06

	DC.B	$0A,$AA,$00

	ORG	RBMA + $1400 + $06

	DC.B	$02,$A8,$00

	ORG	RBMA + $1500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  MONKEY/SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$50

	ORG	RBMA + $0100 + $09

	DC.B	$00,$02,$50

	ORG	RBMA + $0200 + $09

	DC.B	$00,$0A,$80

	ORG	RBMA + $0300 + $09

	DC.B	$00,$AA,$60

	ORG	RBMA + $0400 + $09

	DC.B	$02,$AA,$60

	ORG	RBMA + $0500 + $09

	DC.B	$0A,$A9,$80

	ORG	RBMA + $0600 + $09

	DC.B	$0A,$A6,$80

	ORG	RBMA + $0700 + $09

	DC.B	$0A,$9A,$00

	ORG	RBMA + $0800 + $09

	DC.B	$0A,$98,$00

	ORG	RBMA + $0900 + $09

	DC.B	$0A,$90,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$0A,$A9,$90

	ORG	RBMA + $0B00 + $09

	DC.B	$0A,$AA,$50

	ORG	RBMA + $0C00 + $09

	DC.B	$02,$9A,$80

	ORG	RBMA + $0D00 + $09

	DC.B	$0B,$F6,$90

	ORG	RBMA + $0E00 + $09

	DC.B	$2A,$A9,$94

	ORG	RBMA + $0F00 + $09

	DC.B	$2A,$AA,$10

	ORG	RBMA + $1000 + $09

	DC.B	$2A,$AA,$00

	ORG	RBMA + $1100 + $09

	DC.B	$09,$9A,$00

	ORG	RBMA + $1200 + $09

	DC.B	$0B,$BA,$00

	ORG	RBMA + $1300 + $09

	DC.B	$0A,$AA,$00

	ORG	RBMA + $1400 + $09

	DC.B	$02,$A8,$00

	ORG	RBMA + $1500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $09

	DC.B	$00,$00,$00

	.END
