; FRAME # 1  MONKE3/SPR

	ORG	RBMA + $0000

	DC.B	$00,$02,$50

	ORG	RBMA + $0100

	DC.B	$00,$0A,$90

	ORG	RBMA + $0200

	DC.B	$00,$2A,$00

	ORG	RBMA + $0300

	DC.B	$24,$28,$00

	ORG	RBMA + $0400

	DC.B	$99,$28,$20

	ORG	RBMA + $0500

	DC.B	$6A,$68,$A8

	ORG	RBMA + $0600

	DC.B	$AA,$6A,$AA

	ORG	RBMA + $0700

	DC.B	$6B,$AA,$8A

	ORG	RBMA + $0800

	DC.B	$2F,$AA,$0A

	ORG	RBMA + $0900

	DC.B	$0E,$A8,$05

	ORG	RBMA + $0A00

	DC.B	$2A,$AA,$01

	ORG	RBMA + $0B00

	DC.B	$28,$0A,$80

	ORG	RBMA + $0C00

	DC.B	$A0,$02,$80

	ORG	RBMA + $0D00

	DC.B	$A8,$02,$A0

	ORG	RBMA + $0E00

	DC.B	$29,$00,$A9

	ORG	RBMA + $0F00

	DC.B	$05,$00,$25

	ORG	RBMA + $1000

	DC.B	$00,$00,$01

	ORG	RBMA + $1100

	DC.B	$00,$00,$00

	ORG	RBMA + $1200

	DC.B	$00,$00,$00

	ORG	RBMA + $1300

	DC.B	$00,$00,$00

	ORG	RBMA + $1400

	DC.B	$00,$00,$00

	ORG	RBMA + $1500

	DC.B	$00,$00,$00

	ORG	RBMA + $1600

	DC.B	$00,$00,$00

	ORG	RBMA + $1700

	DC.B	$00,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00

; FRAME # 2  MONKE3/SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$02,$A4

	ORG	RBMA + $0200 + $03

	DC.B	$00,$0A,$94

	ORG	RBMA + $0300 + $03

	DC.B	$18,$2A,$00

	ORG	RBMA + $0400 + $03

	DC.B	$66,$28,$00

	ORG	RBMA + $0500 + $03

	DC.B	$9A,$68,$00

	ORG	RBMA + $0600 + $03

	DC.B	$6A,$6A,$80

	ORG	RBMA + $0700 + $03

	DC.B	$AB,$AA,$A0

	ORG	RBMA + $0800 + $03

	DC.B	$2F,$AA,$A0

	ORG	RBMA + $0900 + $03

	DC.B	$0E,$A9,$A0

	ORG	RBMA + $0A00 + $03

	DC.B	$2A,$AA,$28

	ORG	RBMA + $0B00 + $03

	DC.B	$28,$0A,$2A

	ORG	RBMA + $0C00 + $03

	DC.B	$A8,$0A,$09

	ORG	RBMA + $0D00 + $03

	DC.B	$A0,$0A,$09

	ORG	RBMA + $0E00 + $03

	DC.B	$A0,$02,$80

	ORG	RBMA + $0F00 + $03

	DC.B	$28,$02,$80

	ORG	RBMA + $1000 + $03

	DC.B	$29,$00,$A0

	ORG	RBMA + $1100 + $03

	DC.B	$05,$00,$94

	ORG	RBMA + $1200 + $03

	DC.B	$00,$00,$14

	ORG	RBMA + $1300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  MONKE3/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$18,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$66,$2A,$80

	ORG	RBMA + $0500 + $06

	DC.B	$9A,$6A,$90

	ORG	RBMA + $0600 + $06

	DC.B	$6A,$68,$50

	ORG	RBMA + $0700 + $06

	DC.B	$AB,$AA,$00

	ORG	RBMA + $0800 + $06

	DC.B	$2F,$AA,$A0

	ORG	RBMA + $0900 + $06

	DC.B	$0E,$A9,$A0

	ORG	RBMA + $0A00 + $06

	DC.B	$0A,$AA,$A0

	ORG	RBMA + $0B00 + $06

	DC.B	$0A,$02,$68

	ORG	RBMA + $0C00 + $06

	DC.B	$0A,$02,$68

	ORG	RBMA + $0D00 + $06

	DC.B	$2A,$0A,$0A

	ORG	RBMA + $0E00 + $06

	DC.B	$28,$0A,$09

	ORG	RBMA + $0F00 + $06

	DC.B	$24,$0A,$01

	ORG	RBMA + $1000 + $06

	DC.B	$14,$02,$80

	ORG	RBMA + $1100 + $06

	DC.B	$18,$02,$80

	ORG	RBMA + $1200 + $06

	DC.B	$00,$00,$A0

	ORG	RBMA + $1300 + $06

	DC.B	$00,$00,$50

	ORG	RBMA + $1400 + $06

	DC.B	$00,$01,$40

	ORG	RBMA + $1500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$00,$00

	.END
