; FRAME # 1  MONKE5/SPR

	ORG	RBMA + $0000

	DC.B	$00,$28,$00

	ORG	RBMA + $0100

	DC.B	$00,$29,$80

	ORG	RBMA + $0200

	DC.B	$00,$26,$80

	ORG	RBMA + $0300

	DC.B	$00,$1A,$80

	ORG	RBMA + $0400

	DC.B	$00,$2A,$80

	ORG	RBMA + $0500

	DC.B	$00,$AA,$60

	ORG	RBMA + $0600

	DC.B	$00,$A9,$A0

	ORG	RBMA + $0700

	DC.B	$00,$A5,$A0

	ORG	RBMA + $0800

	DC.B	$00,$5A,$40

	ORG	RBMA + $0900

	DC.B	$02,$99,$40

	ORG	RBMA + $0A00

	DC.B	$02,$96,$A0

	ORG	RBMA + $0B00

	DC.B	$02,$9A,$A0

	ORG	RBMA + $0C00

	DC.B	$00,$9A,$60

	ORG	RBMA + $0D00

	DC.B	$00,$3D,$80

	ORG	RBMA + $0E00

	DC.B	$00,$BE,$80

	ORG	RBMA + $0F00

	DC.B	$00,$AA,$80

	ORG	RBMA + $1000

	DC.B	$00,$AA,$80

	ORG	RBMA + $1100

	DC.B	$00,$99,$80

	ORG	RBMA + $1200

	DC.B	$00,$BB,$80

	ORG	RBMA + $1300

	DC.B	$00,$2A,$00

	ORG	RBMA + $1400

	DC.B	$00,$2A,$00

	ORG	RBMA + $1500

	DC.B	$00,$00,$00

	ORG	RBMA + $1600

	DC.B	$00,$00,$00

	ORG	RBMA + $1700

	DC.B	$00,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00

	.END
