; FRAME # 1  MONKE4/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$A8

	ORG	RBMA + $0200

	DC.B	$00,$02,$A5

	ORG	RBMA + $0300

	DC.B	$00,$0A,$85

	ORG	RBMA + $0400

	DC.B	$00,$0A,$80

	ORG	RBMA + $0500

	DC.B	$14,$0A,$00

	ORG	RBMA + $0600

	DC.B	$94,$0A,$00

	ORG	RBMA + $0700

	DC.B	$A0,$2A,$00

	ORG	RBMA + $0800

	DC.B	$A0,$AA,$81

	ORG	RBMA + $0900

	DC.B	$A2,$AA,$A9

	ORG	RBMA + $0A00

	DC.B	$2A,$AA,$A9

	ORG	RBMA + $0B00

	DC.B	$2A,$AA,$89

	ORG	RBMA + $0C00

	DC.B	$09,$6A,$81

	ORG	RBMA + $0D00

	DC.B	$02,$9A,$80

	ORG	RBMA + $0E00

	DC.B	$0A,$A6,$A0

	ORG	RBMA + $0F00

	DC.B	$0A,$A9,$A0

	ORG	RBMA + $1000

	DC.B	$0A,$AA,$20

	ORG	RBMA + $1100

	DC.B	$01,$9A,$28

	ORG	RBMA + $1200

	DC.B	$03,$BA,$28

	ORG	RBMA + $1300

	DC.B	$02,$A8,$14

	ORG	RBMA + $1400

	DC.B	$00,$A8,$10

	ORG	RBMA + $1500

	DC.B	$00,$00,$00

	ORG	RBMA + $1600

	DC.B	$00,$00,$00

	ORG	RBMA + $1700

	DC.B	$00,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00

; FRAME # 2  MONKE4/SPR

	ORG	RBMA + $0000 + $03

	DC.B	$40,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$50,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$60,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$28,$02,$A0

	ORG	RBMA + $0400 + $03

	DC.B	$2A,$8A,$A9

	ORG	RBMA + $0500 + $03

	DC.B	$0A,$AA,$A9

	ORG	RBMA + $0600 + $03

	DC.B	$02,$AA,$81

	ORG	RBMA + $0700 + $03

	DC.B	$01,$5A,$80

	ORG	RBMA + $0800 + $03

	DC.B	$0A,$A6,$A9

	ORG	RBMA + $0900 + $03

	DC.B	$0A,$A9,$A9

	ORG	RBMA + $0A00 + $03

	DC.B	$0A,$AA,$61

	ORG	RBMA + $0B00 + $03

	DC.B	$0A,$A6,$60

	ORG	RBMA + $0C00 + $03

	DC.B	$02,$6E,$28

	ORG	RBMA + $0D00 + $03

	DC.B	$02,$EA,$29

	ORG	RBMA + $0E00 + $03

	DC.B	$02,$A8,$09

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$A8,$01

	ORG	RBMA + $1000 + $03

	DC.B	$00,$00,$01

	ORG	RBMA + $1100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  MONKE4/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$05,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$29,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$A0,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$A2,$A0

	ORG	RBMA + $0400 + $06

	DC.B	$02,$8A,$A9

	ORG	RBMA + $0500 + $06

	DC.B	$02,$AA,$A9

	ORG	RBMA + $0600 + $06

	DC.B	$02,$AA,$81

	ORG	RBMA + $0700 + $06

	DC.B	$01,$5A,$80

	ORG	RBMA + $0800 + $06

	DC.B	$0A,$A6,$A9

	ORG	RBMA + $0900 + $06

	DC.B	$0A,$A9,$A9

	ORG	RBMA + $0A00 + $06

	DC.B	$0A,$AA,$61

	ORG	RBMA + $0B00 + $06

	DC.B	$0A,$A6,$60

	ORG	RBMA + $0C00 + $06

	DC.B	$02,$6E,$28

	ORG	RBMA + $0D00 + $06

	DC.B	$02,$EA,$29

	ORG	RBMA + $0E00 + $06

	DC.B	$02,$A8,$09

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$A8,$01

	ORG	RBMA + $1000 + $06

	DC.B	$00,$00,$01

	ORG	RBMA + $1100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$00,$00

	.END
