; FRAME # 1  MONKE2/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$94

	ORG	RBMA + $0100

	DC.B	$00,$02,$A4

	ORG	RBMA + $0200

	DC.B	$02,$AA,$80

	ORG	RBMA + $0300

	DC.B	$01,$55,$00

	ORG	RBMA + $0400

	DC.B	$2A,$69,$00

	ORG	RBMA + $0500

	DC.B	$2A,$6A,$40

	ORG	RBMA + $0600

	DC.B	$29,$6A,$40

	ORG	RBMA + $0700

	DC.B	$29,$5A,$60

	ORG	RBMA + $0800

	DC.B	$2A,$65,$A8

	ORG	RBMA + $0900

	DC.B	$0A,$95,$A9

	ORG	RBMA + $0A00

	DC.B	$0A,$A0,$09

	ORG	RBMA + $0B00

	DC.B	$01,$68,$01

	ORG	RBMA + $0C00

	DC.B	$0A,$9A,$00

	ORG	RBMA + $0D00

	DC.B	$0A,$A6,$80

	ORG	RBMA + $0E00

	DC.B	$0A,$AA,$80

	ORG	RBMA + $0F00

	DC.B	$0A,$A8,$A0

	ORG	RBMA + $1000

	DC.B	$06,$78,$A0

	ORG	RBMA + $1100

	DC.B	$0E,$F8,$A0

	ORG	RBMA + $1200

	DC.B	$0A,$A8,$50

	ORG	RBMA + $1300

	DC.B	$02,$A0,$40

	ORG	RBMA + $1400

	DC.B	$00,$00,$00

	ORG	RBMA + $1500

	DC.B	$00,$00,$00

	ORG	RBMA + $1600

	DC.B	$00,$00,$00

	ORG	RBMA + $1700

	DC.B	$00,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00

; FRAME # 2  MONKE2/SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$94

	ORG	RBMA + $0100 + $03

	DC.B	$00,$02,$A4

	ORG	RBMA + $0200 + $03

	DC.B	$02,$AA,$80

	ORG	RBMA + $0300 + $03

	DC.B	$01,$55,$00

	ORG	RBMA + $0400 + $03

	DC.B	$2A,$69,$00

	ORG	RBMA + $0500 + $03

	DC.B	$2A,$6A,$40

	ORG	RBMA + $0600 + $03

	DC.B	$29,$6A,$40

	ORG	RBMA + $0700 + $03

	DC.B	$29,$5A,$60

	ORG	RBMA + $0800 + $03

	DC.B	$2A,$65,$A8

	ORG	RBMA + $0900 + $03

	DC.B	$0A,$95,$A9

	ORG	RBMA + $0A00 + $03

	DC.B	$0A,$A0,$09

	ORG	RBMA + $0B00 + $03

	DC.B	$01,$68,$01

	ORG	RBMA + $0C00 + $03

	DC.B	$0F,$DA,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$0A,$B6,$80

	ORG	RBMA + $0E00 + $03

	DC.B	$0A,$AA,$80

	ORG	RBMA + $0F00 + $03

	DC.B	$0A,$A8,$A0

	ORG	RBMA + $1000 + $03

	DC.B	$06,$78,$A0

	ORG	RBMA + $1100 + $03

	DC.B	$0E,$F8,$A0

	ORG	RBMA + $1200 + $03

	DC.B	$0A,$A8,$50

	ORG	RBMA + $1300 + $03

	DC.B	$02,$A0,$40

	ORG	RBMA + $1400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  MONKE2/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$0A,$50

	ORG	RBMA + $0100 + $06

	DC.B	$15,$2A,$80

	ORG	RBMA + $0200 + $06

	DC.B	$6A,$6A,$00

	ORG	RBMA + $0300 + $06

	DC.B	$5A,$68,$00

	ORG	RBMA + $0400 + $06

	DC.B	$5A,$68,$00

	ORG	RBMA + $0500 + $06

	DC.B	$5A,$68,$00

	ORG	RBMA + $0600 + $06

	DC.B	$56,$6A,$00

	ORG	RBMA + $0700 + $06

	DC.B	$15,$AA,$A0

	ORG	RBMA + $0800 + $06

	DC.B	$2A,$AA,$A8

	ORG	RBMA + $0900 + $06

	DC.B	$0A,$AA,$A9

	ORG	RBMA + $0A00 + $06

	DC.B	$0A,$A8,$29

	ORG	RBMA + $0B00 + $06

	DC.B	$02,$6A,$01

	ORG	RBMA + $0C00 + $06

	DC.B	$0A,$9A,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$0A,$A6,$80

	ORG	RBMA + $0E00 + $06

	DC.B	$0A,$AA,$80

	ORG	RBMA + $0F00 + $06

	DC.B	$0A,$A8,$A0

	ORG	RBMA + $1000 + $06

	DC.B	$06,$78,$A0

	ORG	RBMA + $1100 + $06

	DC.B	$0E,$F8,$A0

	ORG	RBMA + $1200 + $06

	DC.B	$0A,$A8,$50

	ORG	RBMA + $1300 + $06

	DC.B	$02,$A0,$40

	ORG	RBMA + $1400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$00,$00

	.END
