	ORG	RBMA + $0000

	DC.B	$C0,$CC,$CF,$CC,$33,$C0

	ORG	RBMA + $0100

	DC.B	$C0,$CC,$CC,$0C,$33,$30

	ORG	RBMA + $0200

	DC.B	$F0,$F0,$CF,$0C,$F3,$30

	ORG	RBMA + $0300

	DC.B	$C0,$CC,$CC,$0F,$33,$30

	ORG	RBMA + $0400

	DC.B	$FC,$F0,$CF,$CC,$33,$C0

	ORG	RBMA + $0500

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$C3,$3F,$0C,$C0,$00

	ORG	RBMA + $0700

	DC.B	$00,$C3,$30,$33,$30,$00

	ORG	RBMA + $0800

	DC.B	$00,$CF,$3C,$33,$30,$00

	ORG	RBMA + $0900

	DC.B	$00,$F3,$30,$33,$30,$00

	ORG	RBMA + $0A00

	DC.B	$00,$C3,$3F,$33,$30,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00,$00,$00

	.END
