; FRAME # 1  PLANT /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$20

	ORG	RBMA + $0C00

	DC.B	$2A,$00,$50

	ORG	RBMA + $0D00

	DC.B	$2A,$A8,$40

	ORG	RBMA + $0E00

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $0F00

	DC.B	$2A,$AE,$A0

	ORG	RBMA + $1000

	DC.B	$0F,$BF,$A8

	ORG	RBMA + $1100

	DC.B	$0F,$AE,$F8

	ORG	RBMA + $1200

	DC.B	$0A,$AA,$F8

	ORG	RBMA + $1300

	DC.B	$02,$AA,$F8

	ORG	RBMA + $1400

	DC.B	$02,$BE,$A0

	ORG	RBMA + $1500

	DC.B	$00,$BE,$80

	ORG	RBMA + $1600

	DC.B	$00,$2A,$00

	ORG	RBMA + $1700

	DC.B	$00,$00,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00

; FRAME # 2  PLANT /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$2A,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$A0,$80

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$AA,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$08,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$2A,$00

	ORG	RBMA + $1000 + $03

	DC.B	$00,$81,$00

	ORG	RBMA + $1100 + $03

	DC.B	$00,$2A,$80

	ORG	RBMA + $1200 + $03

	DC.B	$00,$00,$A0

	ORG	RBMA + $1300 + $03

	DC.B	$00,$00,$20

	ORG	RBMA + $1400 + $03

	DC.B	$00,$00,$20

	ORG	RBMA + $1500 + $03

	DC.B	$2A,$00,$50

	ORG	RBMA + $1600 + $03

	DC.B	$2A,$A8,$40

	ORG	RBMA + $1700 + $03

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $1800 + $03

	DC.B	$2A,$AE,$A0

	ORG	RBMA + $1900 + $03

	DC.B	$0F,$BF,$A8

	ORG	RBMA + $1A00 + $03

	DC.B	$0F,$AE,$F8

	ORG	RBMA + $1B00 + $03

	DC.B	$0A,$AA,$F8

	ORG	RBMA + $1C00 + $03

	DC.B	$02,$AA,$F8

	ORG	RBMA + $1D00 + $03

	DC.B	$02,$BE,$A0

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$BE,$80

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$2A,$00

; FRAME # 3  PLANT /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$2A,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$A0,$80

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$AA,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$08,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$2A,$00

	ORG	RBMA + $1000 + $06

	DC.B	$00,$81,$00

	ORG	RBMA + $1100 + $06

	DC.B	$00,$2A,$80

	ORG	RBMA + $1200 + $06

	DC.B	$00,$00,$A0

	ORG	RBMA + $1300 + $06

	DC.B	$00,$00,$20

	ORG	RBMA + $1400 + $06

	DC.B	$0A,$80,$20

	ORG	RBMA + $1500 + $06

	DC.B	$07,$E8,$50

	ORG	RBMA + $1600 + $06

	DC.B	$29,$58,$40

	ORG	RBMA + $1700 + $06

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $1800 + $06

	DC.B	$2A,$AE,$A0

	ORG	RBMA + $1900 + $06

	DC.B	$0F,$BF,$A8

	ORG	RBMA + $1A00 + $06

	DC.B	$0F,$AE,$F8

	ORG	RBMA + $1B00 + $06

	DC.B	$0A,$AA,$F8

	ORG	RBMA + $1C00 + $06

	DC.B	$02,$AA,$F8

	ORG	RBMA + $1D00 + $06

	DC.B	$02,$BE,$A0

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$BE,$80

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$2A,$00

; FRAME # 4  PLANT /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$00,$2A,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$00,$A0,$80

	ORG	RBMA + $0D00 + $09

	DC.B	$00,$AA,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$08,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$2A,$00

	ORG	RBMA + $1000 + $09

	DC.B	$00,$81,$00

	ORG	RBMA + $1100 + $09

	DC.B	$00,$2A,$80

	ORG	RBMA + $1200 + $09

	DC.B	$0A,$00,$A0

	ORG	RBMA + $1300 + $09

	DC.B	$05,$80,$20

	ORG	RBMA + $1400 + $09

	DC.B	$0F,$68,$10

	ORG	RBMA + $1500 + $09

	DC.B	$03,$D8,$50

	ORG	RBMA + $1600 + $09

	DC.B	$57,$FA,$80

	ORG	RBMA + $1700 + $09

	DC.B	$A9,$56,$A0

	ORG	RBMA + $1800 + $09

	DC.B	$AA,$AD,$A0

	ORG	RBMA + $1900 + $09

	DC.B	$2A,$BF,$A8

	ORG	RBMA + $1A00 + $09

	DC.B	$2F,$BE,$F8

	ORG	RBMA + $1B00 + $09

	DC.B	$0F,$AA,$F8

	ORG	RBMA + $1C00 + $09

	DC.B	$0A,$AA,$F8

	ORG	RBMA + $1D00 + $09

	DC.B	$02,$BE,$A0

	ORG	RBMA + $1E00 + $09

	DC.B	$00,$BE,$80

	ORG	RBMA + $1F00 + $09

	DC.B	$00,$2A,$00

	.END
