; FRAME # 1  RABBIT/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

	ORG	RBMA + $1000

	DC.B	$00,$0F,$00

	ORG	RBMA + $1100

	DC.B	$00,$FC,$00

	ORG	RBMA + $1200

	DC.B	$0F,$F0,$00

	ORG	RBMA + $1300

	DC.B	$FF,$C0,$00

	ORG	RBMA + $1400

	DC.B	$FF,$C0,$00

	ORG	RBMA + $1500

	DC.B	$3F,$F0,$00

	ORG	RBMA + $1600

	DC.B	$3F,$FF,$F0

	ORG	RBMA + $1700

	DC.B	$3F,$FF,$F0

	ORG	RBMA + $1800

	DC.B	$3F,$FF,$FC

	ORG	RBMA + $1900

	DC.B	$0F,$FC,$C0

	ORG	RBMA + $1A00

	DC.B	$0F,$F0,$C0

	ORG	RBMA + $1B00

	DC.B	$03,$03,$C0

	ORG	RBMA + $1C00

	DC.B	$00,$03,$F0

	ORG	RBMA + $1D00

	DC.B	$00,$00,$FC

	ORG	RBMA + $1E00

	DC.B	$00,$00,$FC

	ORG	RBMA + $1F00

	DC.B	$00,$00,$F0

; FRAME # 2  RABBIT/SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$C0,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$F0,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$3C,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$0F,$C0,$00

	ORG	RBMA + $1000 + $03

	DC.B	$0F,$FC,$30

	ORG	RBMA + $1100 + $03

	DC.B	$3F,$FC,$30

	ORG	RBMA + $1200 + $03

	DC.B	$3F,$FF,$C0

	ORG	RBMA + $1300 + $03

	DC.B	$3F,$FF,$00

	ORG	RBMA + $1400 + $03

	DC.B	$3F,$FF,$00

	ORG	RBMA + $1500 + $03

	DC.B	$0F,$FF,$F0

	ORG	RBMA + $1600 + $03

	DC.B	$03,$FF,$F0

	ORG	RBMA + $1700 + $03

	DC.B	$00,$C3,$FC

	ORG	RBMA + $1800 + $03

	DC.B	$00,$00,$C0

	ORG	RBMA + $1900 + $03

	DC.B	$00,$00,$F0

	ORG	RBMA + $1A00 + $03

	DC.B	$00,$00,$F0

	ORG	RBMA + $1B00 + $03

	DC.B	$00,$00,$FC

	ORG	RBMA + $1C00 + $03

	DC.B	$00,$00,$3C

	ORG	RBMA + $1D00 + $03

	DC.B	$00,$00,$3F

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$00,$0C

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$0F

; FRAME # 3  RABBIT/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $1100 + $06

	DC.B	$C0,$00,$00

	ORG	RBMA + $1200 + $06

	DC.B	$FC,$00,$00

	ORG	RBMA + $1300 + $06

	DC.B	$3F,$C0,$00

	ORG	RBMA + $1400 + $06

	DC.B	$0F,$F0,$00

	ORG	RBMA + $1500 + $06

	DC.B	$3F,$FC,$00

	ORG	RBMA + $1600 + $06

	DC.B	$3F,$FF,$FC

	ORG	RBMA + $1700 + $06

	DC.B	$FF,$FF,$FF

	ORG	RBMA + $1800 + $06

	DC.B	$FF,$FF,$F0

	ORG	RBMA + $1900 + $06

	DC.B	$3F,$FC,$3C

	ORG	RBMA + $1A00 + $06

	DC.B	$30,$30,$3C

	ORG	RBMA + $1B00 + $06

	DC.B	$00,$00,$3C

	ORG	RBMA + $1C00 + $06

	DC.B	$00,$00,$0F

	ORG	RBMA + $1D00 + $06

	DC.B	$00,$00,$0F

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$00,$0F

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$00,$03

; FRAME # 4  RABBIT/SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $1100 + $09

	DC.B	$03,$00,$00

	ORG	RBMA + $1200 + $09

	DC.B	$0F,$C0,$C0

	ORG	RBMA + $1300 + $09

	DC.B	$0F,$F0,$C0

	ORG	RBMA + $1400 + $09

	DC.B	$0F,$FF,$00

	ORG	RBMA + $1500 + $09

	DC.B	$33,$FF,$C0

	ORG	RBMA + $1600 + $09

	DC.B	$FF,$FF,$F0

	ORG	RBMA + $1700 + $09

	DC.B	$3F,$FF,$F0

	ORG	RBMA + $1800 + $09

	DC.B	$0F,$FF,$C0

	ORG	RBMA + $1900 + $09

	DC.B	$03,$F0,$F0

	ORG	RBMA + $1A00 + $09

	DC.B	$00,$F0,$F0

	ORG	RBMA + $1B00 + $09

	DC.B	$00,$00,$FC

	ORG	RBMA + $1C00 + $09

	DC.B	$00,$00,$FF

	ORG	RBMA + $1D00 + $09

	DC.B	$00,$00,$3F

	ORG	RBMA + $1E00 + $09

	DC.B	$00,$00,$0F

	ORG	RBMA + $1F00 + $09

	DC.B	$00,$00,$00

	.END
