; FRAME # 1  RDEYE4/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$FF,$80,$00

	ORG	RBMA + $0300

	DC.B	$0F,$0F,$E8,$00

	ORG	RBMA + $0400

	DC.B	$0C,$03,$EA,$80

	ORG	RBMA + $0500

	DC.B	$3C,$03,$EA,$A0

	ORG	RBMA + $0600

	DC.B	$3C,$17,$EA,$A8

	ORG	RBMA + $0700

	DC.B	$AF,$05,$AA,$AA

	ORG	RBMA + $0800

	DC.B	$AF,$F7,$AA,$AA

	ORG	RBMA + $0900

	DC.B	$2B,$FE,$AA,$A8

	ORG	RBMA + $0A00

	DC.B	$0A,$AA,$AA,$A0

	ORG	RBMA + $0B00

	DC.B	$02,$AA,$AA,$80

	ORG	RBMA + $0C00

	DC.B	$00,$2A,$A8,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00

; FRAME # 2  RDEYE4/SPR

	ORG	RBMA + $0000 + $04

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0100 + $04

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0200 + $04

	DC.B	$00,$AF,$C0,$00

	ORG	RBMA + $0300 + $04

	DC.B	$0A,$BF,$0C,$00

	ORG	RBMA + $0400 + $04

	DC.B	$0A,$BC,$03,$80

	ORG	RBMA + $0500 + $04

	DC.B	$2A,$BC,$03,$A0

	ORG	RBMA + $0600 + $04

	DC.B	$2A,$BC,$13,$A8

	ORG	RBMA + $0700 + $04

	DC.B	$AA,$BF,$17,$AA

	ORG	RBMA + $0800 + $04

	DC.B	$AA,$AF,$F7,$AA

	ORG	RBMA + $0900 + $04

	DC.B	$2A,$AB,$FE,$A8

	ORG	RBMA + $0A00 + $04

	DC.B	$0A,$AA,$AA,$A0

	ORG	RBMA + $0B00 + $04

	DC.B	$02,$AA,$AA,$80

	ORG	RBMA + $0C00 + $04

	DC.B	$00,$2A,$A8,$00

	ORG	RBMA + $0D00 + $04

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0E00 + $04

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0F00 + $04

	DC.B	$00,$00,$00,$00

; FRAME # 3  RDEYE4/SPR

	ORG	RBMA + $0000 + $08

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0100 + $08

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0200 + $08

	DC.B	$00,$AA,$C0,$00

	ORG	RBMA + $0300 + $08

	DC.B	$0A,$AA,$FC,$00

	ORG	RBMA + $0400 + $08

	DC.B	$0A,$AA,$F0,$C0

	ORG	RBMA + $0500 + $08

	DC.B	$2A,$AA,$F0,$30

	ORG	RBMA + $0600 + $08

	DC.B	$2A,$AA,$F0,$7C

	ORG	RBMA + $0700 + $08

	DC.B	$AA,$AA,$FC,$5E

	ORG	RBMA + $0800 + $08

	DC.B	$AA,$AA,$BF,$DA

	ORG	RBMA + $0900 + $08

	DC.B	$2A,$AA,$AF,$E8

	ORG	RBMA + $0A00 + $08

	DC.B	$0A,$AA,$AA,$A0

	ORG	RBMA + $0B00 + $08

	DC.B	$02,$AA,$AA,$80

	ORG	RBMA + $0C00 + $08

	DC.B	$00,$2A,$A8,$00

	ORG	RBMA + $0D00 + $08

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0E00 + $08

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0F00 + $08

	DC.B	$00,$00,$00,$00

	.END
