; FRAME # 1  RDEYE5/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$AF,$C0,$00

	ORG	RBMA + $0300

	DC.B	$0A,$F3,$0C,$00

	ORG	RBMA + $0400

	DC.B	$0F,$30,$03,$80

	ORG	RBMA + $0500

	DC.B	$2B,$83,$C3,$A0

	ORG	RBMA + $0600

	DC.B	$2E,$F3,$0F,$A8

	ORG	RBMA + $0700

	DC.B	$AB,$C0,$07,$AA

	ORG	RBMA + $0800

	DC.B	$AE,$EC,$C7,$AA

	ORG	RBMA + $0900

	DC.B	$2B,$BB,$FE,$A8

	ORG	RBMA + $0A00

	DC.B	$0A,$EE,$BB,$A0

	ORG	RBMA + $0B00

	DC.B	$02,$BB,$EA,$80

	ORG	RBMA + $0C00

	DC.B	$00,$2A,$A8,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00

	.END
