; FRAME # 1  RDEYE6/SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$3F,$3E,$00

	ORG	RBMA + $0300

	DC.B	$00,$FC,$C0,$80

	ORG	RBMA + $0400

	DC.B	$00,$FC,$F0,$E0

	ORG	RBMA + $0500

	DC.B	$02,$F0,$30,$B8

	ORG	RBMA + $0600

	DC.B	$2B,$CC,$07,$E8

	ORG	RBMA + $0700

	DC.B	$AE,$FC,$37,$BA

	ORG	RBMA + $0800

	DC.B	$AB,$B3,$CE,$EA

	ORG	RBMA + $0900

	DC.B	$2A,$EF,$AF,$A8

	ORG	RBMA + $0A00

	DC.B	$0B,$BB,$BA,$A0

	ORG	RBMA + $0B00

	DC.B	$02,$AE,$EE,$80

	ORG	RBMA + $0C00

	DC.B	$00,$2A,$A8,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00

	.END
