; FRAME # 1  ROCK  /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$0A,$BC,$00

	ORG	RBMA + $0C00

	DC.B	$2B,$AF,$00

	ORG	RBMA + $0D00

	DC.B	$2A,$FF,$00

	ORG	RBMA + $0E00

	DC.B	$AA,$FF,$C0

	ORG	RBMA + $0F00

	DC.B	$AB,$BB,$C0

	ORG	RBMA + $1000

	DC.B	$2E,$FF,$C0

	ORG	RBMA + $1100

	DC.B	$AB,$EF,$C0

	ORG	RBMA + $1200

	DC.B	$AA,$FB,$C0

	ORG	RBMA + $1300

	DC.B	$AB,$EF,$00

	ORG	RBMA + $1400

	DC.B	$2F,$BF,$00

	ORG	RBMA + $1500

	DC.B	$2A,$FF,$00

	ORG	RBMA + $1600

	DC.B	$2A,$BF,$00

	ORG	RBMA + $1700

	DC.B	$0A,$FC,$00

	ORG	RBMA + $1800

	DC.B	$0B,$F8,$00

	ORG	RBMA + $1900

	DC.B	$2B,$FF,$00

	ORG	RBMA + $1A00

	DC.B	$2B,$EF,$00

	ORG	RBMA + $1B00

	DC.B	$2A,$FF,$00

	ORG	RBMA + $1C00

	DC.B	$2B,$BF,$00

	ORG	RBMA + $1D00

	DC.B	$0B,$FC,$00

	ORG	RBMA + $1E00

	DC.B	$0A,$FC,$00

	ORG	RBMA + $1F00

	DC.B	$02,$A0,$00

	.END
