; FRAME # 1  ROCKC /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$80,$2A,$00

	ORG	RBMA + $0C00

	DC.B	$80,$AA,$80

	ORG	RBMA + $0D00

	DC.B	$0A,$AA,$A0

	ORG	RBMA + $0E00

	DC.B	$2A,$AA,$A8

	ORG	RBMA + $0F00

	DC.B	$2A,$AA,$B8

	ORG	RBMA + $1000

	DC.B	$2A,$AA,$BA

	ORG	RBMA + $1100

	DC.B	$2A,$AA,$EA

	ORG	RBMA + $1200

	DC.B	$2B,$EB,$AE

	ORG	RBMA + $1300

	DC.B	$AA,$BE,$9A

	ORG	RBMA + $1400

	DC.B	$AA,$AA,$7A

	ORG	RBMA + $1500

	DC.B	$AB,$AA,$E8

	ORG	RBMA + $1600

	DC.B	$AE,$AB,$A0

	ORG	RBMA + $1700

	DC.B	$AA,$B6,$00

	ORG	RBMA + $1800

	DC.B	$AE,$EC,$02

	ORG	RBMA + $1900

	DC.B	$2F,$B0,$20

	ORG	RBMA + $1A00

	DC.B	$0A,$A0,$20

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$20,$00,$02

	ORG	RBMA + $1F00

	DC.B	$20,$00,$00

; FRAME # 2  ROCKC /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$20,$A8,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$02,$AA,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$0A,$AA,$80

	ORG	RBMA + $0E00 + $03

	DC.B	$0A,$AA,$82

	ORG	RBMA + $0F00 + $03

	DC.B	$8A,$AB,$A0

	ORG	RBMA + $1000 + $03

	DC.B	$8A,$AA,$A0

	ORG	RBMA + $1100 + $03

	DC.B	$0E,$AB,$A0

	ORG	RBMA + $1200 + $03

	DC.B	$0A,$AB,$A0

	ORG	RBMA + $1300 + $03

	DC.B	$2A,$AA,$E8

	ORG	RBMA + $1400 + $03

	DC.B	$2A,$AA,$E8

	ORG	RBMA + $1500 + $03

	DC.B	$2B,$AA,$A8

	ORG	RBMA + $1600 + $03

	DC.B	$2A,$AA,$B8

	ORG	RBMA + $1700 + $03

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $1800 + $03

	DC.B	$AA,$AA,$F8

	ORG	RBMA + $1900 + $03

	DC.B	$AA,$AB,$B8

	ORG	RBMA + $1A00 + $03

	DC.B	$AA,$BA,$B8

	ORG	RBMA + $1B00 + $03

	DC.B	$AE,$AA,$E0

	ORG	RBMA + $1C00 + $03

	DC.B	$2B,$EF,$80

	ORG	RBMA + $1D00 + $03

	DC.B	$0A,$AA,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$20

	.END
