; FRAME # 1  FRBALL/SPR

	ORG	RBMA + $0000

	DC.B	$20,$00,$00

	ORG	RBMA + $0100

	DC.B	$50,$A0,$00

	ORG	RBMA + $0200

	DC.B	$50,$A8,$00

	ORG	RBMA + $0300

	DC.B	$56,$58,$00

	ORG	RBMA + $0400

	DC.B	$96,$58,$00

	ORG	RBMA + $0500

	DC.B	$9A,$65,$00

	ORG	RBMA + $0600

	DC.B	$96,$99,$00

	ORG	RBMA + $0700

	DC.B	$25,$A6,$40

	ORG	RBMA + $0800

	DC.B	$2A,$A5,$40

	ORG	RBMA + $0900

	DC.B	$06,$95,$50

	ORG	RBMA + $0A00

	DC.B	$02,$95,$50

	ORG	RBMA + $0B00

	DC.B	$02,$96,$54

	ORG	RBMA + $0C00

	DC.B	$00,$A4,$A4

	ORG	RBMA + $0D00

	DC.B	$00,$05,$64

	ORG	RBMA + $0E00

	DC.B	$00,$01,$69

	ORG	RBMA + $0F00

	DC.B	$00,$00,$90

; FRAME # 2  FRBALL/SPR

	ORG	RBMA + $0000 + $03

	DC.B	$25,$80,$00

	ORG	RBMA + $0100 + $03

	DC.B	$9A,$90,$00

	ORG	RBMA + $0200 + $03

	DC.B	$55,$A4,$00

	ORG	RBMA + $0300 + $03

	DC.B	$96,$68,$00

	ORG	RBMA + $0400 + $03

	DC.B	$66,$40,$00

	ORG	RBMA + $0500 + $03

	DC.B	$AA,$60,$00

	ORG	RBMA + $0600 + $03

	DC.B	$25,$9A,$80

	ORG	RBMA + $0700 + $03

	DC.B	$09,$9A,$A0

	ORG	RBMA + $0800 + $03

	DC.B	$0A,$96,$60

	ORG	RBMA + $0900 + $03

	DC.B	$02,$66,$90

	ORG	RBMA + $0A00 + $03

	DC.B	$02,$A9,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$02,$66,$A0

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$AA,$A0

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$02,$40

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$80

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$A0

; FRAME # 3  FRBALL/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$25,$80,$00

	ORG	RBMA + $0100 + $06

	DC.B	$9A,$60,$00

	ORG	RBMA + $0200 + $06

	DC.B	$A6,$60,$00

	ORG	RBMA + $0300 + $06

	DC.B	$9A,$60,$00

	ORG	RBMA + $0400 + $06

	DC.B	$26,$80,$00

	ORG	RBMA + $0500 + $06

	DC.B	$06,$40,$00

	ORG	RBMA + $0600 + $06

	DC.B	$09,$60,$00

	ORG	RBMA + $0700 + $06

	DC.B	$0A,$5A,$80

	ORG	RBMA + $0800 + $06

	DC.B	$0A,$A6,$60

	ORG	RBMA + $0900 + $06

	DC.B	$0A,$6A,$90

	ORG	RBMA + $0A00 + $06

	DC.B	$01,$AA,$A0

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$46,$98

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$02,$A0

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$02,$68

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$02,$A8

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$90

	.END
