; FRAME # 1  SNAKE /SPR

	ORG	RBMA + $0000

	DC.B	$02,$A0

	ORG	RBMA + $0100

	DC.B	$00,$A0

	ORG	RBMA + $0200

	DC.B	$00,$A8

	ORG	RBMA + $0300

	DC.B	$00,$2A

	ORG	RBMA + $0400

	DC.B	$A8,$AA

	ORG	RBMA + $0500

	DC.B	$AA,$A8

	ORG	RBMA + $0600

	DC.B	$2A,$A8

	ORG	RBMA + $0700

	DC.B	$0A,$A0

	ORG	RBMA + $0800

	DC.B	$02,$A0

	ORG	RBMA + $0900

	DC.B	$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00

; FRAME # 2  SNAKE /SPR

	ORG	RBMA + $0000 + $02

	DC.B	$0A,$80

	ORG	RBMA + $0100 + $02

	DC.B	$02,$80

	ORG	RBMA + $0200 + $02

	DC.B	$02,$A0

	ORG	RBMA + $0300 + $02

	DC.B	$00,$A0

	ORG	RBMA + $0400 + $02

	DC.B	$00,$A8

	ORG	RBMA + $0500 + $02

	DC.B	$00,$28

	ORG	RBMA + $0600 + $02

	DC.B	$80,$2A

	ORG	RBMA + $0700 + $02

	DC.B	$80,$2A

	ORG	RBMA + $0800 + $02

	DC.B	$20,$2A

	ORG	RBMA + $0900 + $02

	DC.B	$A8,$2A

	ORG	RBMA + $0A00 + $02

	DC.B	$2A,$AA

	ORG	RBMA + $0B00 + $02

	DC.B	$2A,$A8

	ORG	RBMA + $0C00 + $02

	DC.B	$0A,$A0

	ORG	RBMA + $0D00 + $02

	DC.B	$02,$A0

	ORG	RBMA + $0E00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $02

	DC.B	$00,$00

; FRAME # 3  SNAKE /SPR

	ORG	RBMA + $0000 + $04

	DC.B	$00,$A0

	ORG	RBMA + $0100 + $04

	DC.B	$02,$A0

	ORG	RBMA + $0200 + $04

	DC.B	$02,$A0

	ORG	RBMA + $0300 + $04

	DC.B	$02,$80

	ORG	RBMA + $0400 + $04

	DC.B	$02,$80

	ORG	RBMA + $0500 + $04

	DC.B	$02,$80

	ORG	RBMA + $0600 + $04

	DC.B	$02,$A0

	ORG	RBMA + $0700 + $04

	DC.B	$00,$A0

	ORG	RBMA + $0800 + $04

	DC.B	$00,$A0

	ORG	RBMA + $0900 + $04

	DC.B	$00,$A0

	ORG	RBMA + $0A00 + $04

	DC.B	$00,$28

	ORG	RBMA + $0B00 + $04

	DC.B	$28,$28

	ORG	RBMA + $0C00 + $04

	DC.B	$2A,$A8

	ORG	RBMA + $0D00 + $04

	DC.B	$0A,$A8

	ORG	RBMA + $0E00 + $04

	DC.B	$0A,$A0

	ORG	RBMA + $0F00 + $04

	DC.B	$02,$A0

; FRAME # 4  SNAKE /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$A8

	ORG	RBMA + $0100 + $06

	DC.B	$00,$28

	ORG	RBMA + $0200 + $06

	DC.B	$00,$28

	ORG	RBMA + $0300 + $06

	DC.B	$00,$2A

	ORG	RBMA + $0400 + $06

	DC.B	$00,$2A

	ORG	RBMA + $0500 + $06

	DC.B	$00,$28

	ORG	RBMA + $0600 + $06

	DC.B	$00,$28

	ORG	RBMA + $0700 + $06

	DC.B	$00,$A8

	ORG	RBMA + $0800 + $06

	DC.B	$00,$A0

	ORG	RBMA + $0900 + $06

	DC.B	$02,$A0

	ORG	RBMA + $0A00 + $06

	DC.B	$02,$A0

	ORG	RBMA + $0B00 + $06

	DC.B	$0A,$A0

	ORG	RBMA + $0C00 + $06

	DC.B	$0A,$A8

	ORG	RBMA + $0D00 + $06

	DC.B	$0A,$A8

	ORG	RBMA + $0E00 + $06

	DC.B	$0A,$A8

	ORG	RBMA + $0F00 + $06

	DC.B	$02,$A0

	.END
