	ORG	RBMA + $0000

	DC.B	$00,$F0,$30,$C3,$0C,$3C,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$CC,$CC,$C3,$33,$03,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$F0,$CC,$CF,$33,$0C,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$CC,$CC,$F3,$33,$30,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$F0,$30,$C3,$33,$0F,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$F0,$30,$CC,$30,$C3,$0C,$CF,$C0

	ORG	RBMA + $0700

	DC.B	$0C,$CC,$CC,$30,$C3,$0C,$CC,$00

	ORG	RBMA + $0800

	DC.B	$30,$CC,$F0,$CC,$CC,$CF,$CC,$00

	ORG	RBMA + $0900

	DC.B	$C0,$CC,$CC,$CC,$CC,$CC,$CC,$00

	ORG	RBMA + $0A00

	DC.B	$3C,$CC,$F0,$CC,$CC,$C3,$0C,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00,$00,$00,$00,$00

	.END
