;	star in town sky
.org	RBMA
.dc.b	$C0
.org	RBMA + $100
.dc.b	$C0
.org	RBMA + $200
.dc.b	$00
.org	RBMA + $300
.dc.b	$00
.org	RBMA + $400
.dc.b	$00
.org	RBMA + $500
.dc.b	$00
.org	RBMA + $600
.dc.b	$00
.org	RBMA + $700
.dc.b	$00
.org	RBMA + $800
.dc.b	$00
.org	RBMA + $900
.dc.b	$00
.org	RBMA + $A00
.dc.b	$00
.org	RBMA + $B00
.dc.b	$00
.org	RBMA + $C00
.dc.b	$00
.org	RBMA + $D00
.dc.b	$00
.org	RBMA + $E00
.dc.b	$00
.org	RBMA + $F00
.dc.b	$00
