;	stub file for bitmaps that don't exist yet
.org	RBMA + $0000
.dc.b	$E4,$E4
.org	RBMA + $0100
.dc.b	$E4
.org	RBMA + $0200
.dc.b	$E4
.org	RBMA + $0300
.dc.b	$E4
.org	RBMA + $0400
.dc.b	$E4
.org	RBMA + $0500
.dc.b	$E4
.org	RBMA + $0600
.dc.b	$E4
.org	RBMA + $0700
.dc.b	$E4
.org	RBMA + $0800
.dc.b	$E4
.org	RBMA + $0900
.dc.b	$E4
.org	RBMA + $0A00
.dc.b	$E4
.org	RBMA + $0B00
.dc.b	$E4
.org	RBMA + $0C00
.dc.b	$E4
.org	RBMA + $0D00
.dc.b	$E4
.org	RBMA + $0E00
.dc.b	$E4
.org	RBMA + $0F00
.dc.b	$E4
