; FRAME # 1  TOCAN2/SPR

	ORG	RBMA + $0000

	DC.B	$03,$D4,$00

	ORG	RBMA + $0100

	DC.B	$0F,$58,$00

	ORG	RBMA + $0200

	DC.B	$0D,$64,$00

	ORG	RBMA + $0300

	DC.B	$35,$90,$00

	ORG	RBMA + $0400

	DC.B	$2A,$5A,$00

	ORG	RBMA + $0500

	DC.B	$A9,$6A,$80

	ORG	RBMA + $0600

	DC.B	$AA,$AF,$A0

	ORG	RBMA + $0700

	DC.B	$BA,$BD,$E2

	ORG	RBMA + $0800

	DC.B	$AA,$F5,$E2

	ORG	RBMA + $0900

	DC.B	$AA,$D5,$6A

	ORG	RBMA + $0A00

	DC.B	$2A,$EA,$52

	ORG	RBMA + $0B00

	DC.B	$0A,$6A,$A0

	ORG	RBMA + $0C00

	DC.B	$01,$AA,$A0

	ORG	RBMA + $0D00

	DC.B	$01,$6A,$A8

	ORG	RBMA + $0E00

	DC.B	$00,$41,$F2

	ORG	RBMA + $0F00

	DC.B	$00,$10,$7C

; FRAME # 2  TOCAN2/SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$0A,$F0

	ORG	RBMA + $0100 + $03

	DC.B	$00,$2E,$5C

	ORG	RBMA + $0200 + $03

	DC.B	$00,$2A,$5C

	ORG	RBMA + $0300 + $03

	DC.B	$00,$2A,$97

	ORG	RBMA + $0400 + $03

	DC.B	$00,$29,$67

	ORG	RBMA + $0500 + $03

	DC.B	$00,$AA,$1B

	ORG	RBMA + $0600 + $03

	DC.B	$02,$FE,$86

	ORG	RBMA + $0700 + $03

	DC.B	$02,$5F,$80

	ORG	RBMA + $0800 + $03

	DC.B	$0A,$5F,$80

	ORG	RBMA + $0900 + $03

	DC.B	$09,$57,$80

	ORG	RBMA + $0A00 + $03

	DC.B	$1A,$9F,$80

	ORG	RBMA + $0B00 + $03

	DC.B	$36,$9A,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$F6,$AA,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$FD,$A8,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$D4,$08,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$0A,$00

; FRAME # 3  TOCAN2/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$3D,$04,$00

	ORG	RBMA + $0100 + $06

	DC.B	$8F,$41,$00

	ORG	RBMA + $0200 + $06

	DC.B	$2A,$A9,$40

	ORG	RBMA + $0300 + $06

	DC.B	$0A,$AA,$40

	ORG	RBMA + $0400 + $06

	DC.B	$0A,$A9,$A0

	ORG	RBMA + $0500 + $06

	DC.B	$85,$AB,$A8

	ORG	RBMA + $0600 + $06

	DC.B	$A9,$57,$AA

	ORG	RBMA + $0700 + $06

	DC.B	$8B,$5F,$AA

	ORG	RBMA + $0800 + $06

	DC.B	$8B,$7E,$AE

	ORG	RBMA + $0900 + $06

	DC.B	$0A,$FA,$AA

	ORG	RBMA + $0A00 + $06

	DC.B	$02,$A9,$6A

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$A5,$A8

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$06,$5C

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$19,$70

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$25,$F0

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$17,$C0

	.END
