; FRAME # 1  TOCAN /SPR

	ORG	RBMA + $0000

	DC.B	$00,$A0,$00

	ORG	RBMA + $0100

	DC.B	$00,$20,$1F

	ORG	RBMA + $0200

	DC.B	$00,$20,$7F

	ORG	RBMA + $0300

	DC.B	$00,$2A,$9F

	ORG	RBMA + $0400

	DC.B	$00,$AA,$9C

	ORG	RBMA + $0500

	DC.B	$02,$F6,$A4

	ORG	RBMA + $0600

	DC.B	$02,$F5,$60

	ORG	RBMA + $0700

	DC.B	$02,$D5,$A0

	ORG	RBMA + $0800

	DC.B	$02,$F5,$80

	ORG	RBMA + $0900

	DC.B	$92,$BF,$80

	ORG	RBMA + $0A00

	DC.B	$E4,$AA,$00

	ORG	RBMA + $0B00

	DC.B	$D9,$68,$00

	ORG	RBMA + $0C00

	DC.B	$F6,$A8,$00

	ORG	RBMA + $0D00

	DC.B	$35,$A8,$00

	ORG	RBMA + $0E00

	DC.B	$3D,$B8,$00

	ORG	RBMA + $0F00

	DC.B	$0F,$A0,$00

; FRAME # 2  TOCAN /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$A0,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$20,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$20,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$2A,$40

	ORG	RBMA + $0400 + $03

	DC.B	$00,$A6,$90

	ORG	RBMA + $0500 + $03

	DC.B	$02,$F6,$9C

	ORG	RBMA + $0600 + $03

	DC.B	$02,$F5,$6C

	ORG	RBMA + $0700 + $03

	DC.B	$02,$D5,$AF

	ORG	RBMA + $0800 + $03

	DC.B	$02,$F5,$83

	ORG	RBMA + $0900 + $03

	DC.B	$92,$BF,$80

	ORG	RBMA + $0A00 + $03

	DC.B	$E4,$AA,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$D9,$68,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$F6,$A8,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$35,$A8,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$3D,$B8,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$0F,$A0,$00

; FRAME # 3  TOCAN /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$A0,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$20,$7C

	ORG	RBMA + $0200 + $06

	DC.B	$00,$2A,$7C

	ORG	RBMA + $0300 + $06

	DC.B	$00,$A5,$AC

	ORG	RBMA + $0400 + $06

	DC.B	$00,$95,$90

	ORG	RBMA + $0500 + $06

	DC.B	$02,$D5,$60

	ORG	RBMA + $0600 + $06

	DC.B	$02,$D5,$60

	ORG	RBMA + $0700 + $06

	DC.B	$02,$D5,$A0

	ORG	RBMA + $0800 + $06

	DC.B	$02,$F5,$80

	ORG	RBMA + $0900 + $06

	DC.B	$02,$BF,$80

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$AA,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$05,$A8,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$0E,$A8,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$0E,$A8,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$02,$A8,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$02,$A0,$00

; FRAME # 4  TOCAN /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$AA,$00

	ORG	RBMA + $0300 + $09

	DC.B	$01,$69,$40

	ORG	RBMA + $0400 + $09

	DC.B	$01,$69,$40

	ORG	RBMA + $0500 + $09

	DC.B	$01,$55,$40

	ORG	RBMA + $0600 + $09

	DC.B	$01,$55,$40

	ORG	RBMA + $0700 + $09

	DC.B	$01,$69,$40

	ORG	RBMA + $0800 + $09

	DC.B	$30,$AA,$0C

	ORG	RBMA + $0900 + $09

	DC.B	$F0,$AA,$0F

	ORG	RBMA + $0A00 + $09

	DC.B	$F0,$3C,$0F

	ORG	RBMA + $0B00 + $09

	DC.B	$00,$3C,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

; FRAME # 5  TOCAN /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$AA,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$02,$AA,$80

	ORG	RBMA + $0500 + $0C

	DC.B	$01,$69,$40

	ORG	RBMA + $0600 + $0C

	DC.B	$01,$55,$40

	ORG	RBMA + $0700 + $0C

	DC.B	$01,$55,$40

	ORG	RBMA + $0800 + $0C

	DC.B	$00,$55,$00

	ORG	RBMA + $0900 + $0C

	DC.B	$00,$3C,$00

	ORG	RBMA + $0A00 + $0C

	DC.B	$00,$3C,$00

	ORG	RBMA + $0B00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$00,$00,$00

; FRAME # 6  TOCAN /SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0F

	DC.B	$00,$3F,$00

	ORG	RBMA + $0700 + $0F

	DC.B	$00,$3F,$00

	ORG	RBMA + $0800 + $0F

	DC.B	$00,$0C,$00

	ORG	RBMA + $0900 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $0F

	DC.B	$00,$00,$00

	.END
