; FRAME # 1  TORCH /SPR

	ORG	RBMA + $0000

	DC.B	$15,$00

	ORG	RBMA + $0100

	DC.B	$19,$00

	ORG	RBMA + $0200

	DC.B	$59,$40

	ORG	RBMA + $0300

	DC.B	$26,$00

	ORG	RBMA + $0400

	DC.B	$09,$00

	ORG	RBMA + $0500

	DC.B	$26,$00

	ORG	RBMA + $0600

	DC.B	$15,$00

	ORG	RBMA + $0700

	DC.B	$08,$00

	ORG	RBMA + $0800

	DC.B	$04,$00

	ORG	RBMA + $0900

	DC.B	$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00

; FRAME # 2  TORCH /SPR

	ORG	RBMA + $0000 + $02

	DC.B	$15,$00

	ORG	RBMA + $0100 + $02

	DC.B	$15,$00

	ORG	RBMA + $0200 + $02

	DC.B	$55,$40

	ORG	RBMA + $0300 + $02

	DC.B	$55,$40

	ORG	RBMA + $0400 + $02

	DC.B	$55,$40

	ORG	RBMA + $0500 + $02

	DC.B	$26,$00

	ORG	RBMA + $0600 + $02

	DC.B	$25,$00

	ORG	RBMA + $0700 + $02

	DC.B	$19,$00

	ORG	RBMA + $0800 + $02

	DC.B	$01,$00

	ORG	RBMA + $0900 + $02

	DC.B	$04,$00

	ORG	RBMA + $0A00 + $02

	DC.B	$04,$00

	ORG	RBMA + $0B00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $02

	DC.B	$01,$00

	ORG	RBMA + $0D00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $02

	DC.B	$00,$00

; FRAME # 3  TORCH /SPR

	ORG	RBMA + $0000 + $04

	DC.B	$15,$00

	ORG	RBMA + $0100 + $04

	DC.B	$15,$40

	ORG	RBMA + $0200 + $04

	DC.B	$55,$40

	ORG	RBMA + $0300 + $04

	DC.B	$55,$50

	ORG	RBMA + $0400 + $04

	DC.B	$55,$50

	ORG	RBMA + $0500 + $04

	DC.B	$66,$50

	ORG	RBMA + $0600 + $04

	DC.B	$25,$50

	ORG	RBMA + $0700 + $04

	DC.B	$19,$40

	ORG	RBMA + $0800 + $04

	DC.B	$15,$40

	ORG	RBMA + $0900 + $04

	DC.B	$04,$40

	ORG	RBMA + $0A00 + $04

	DC.B	$04,$10

	ORG	RBMA + $0B00 + $04

	DC.B	$01,$00

	ORG	RBMA + $0C00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $04

	DC.B	$00,$00

; FRAME # 4  TORCH /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$15,$00

	ORG	RBMA + $0100 + $06

	DC.B	$15,$40

	ORG	RBMA + $0200 + $06

	DC.B	$15,$40

	ORG	RBMA + $0300 + $06

	DC.B	$59,$40

	ORG	RBMA + $0400 + $06

	DC.B	$A5,$40

	ORG	RBMA + $0500 + $06

	DC.B	$26,$00

	ORG	RBMA + $0600 + $06

	DC.B	$49,$00

	ORG	RBMA + $0700 + $06

	DC.B	$11,$00

	ORG	RBMA + $0800 + $06

	DC.B	$04,$00

	ORG	RBMA + $0900 + $06

	DC.B	$04,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$10,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00

	.END
