; FRAME # 1  TOWNT /SPR

	ORG	RBMA + $0000

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0100

	DC.B	$AB,$AB,$A8

	ORG	RBMA + $0200

	DC.B	$AE,$BA,$E8

	ORG	RBMA + $0300

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0400

	DC.B	$3F,$FF,$F0

	ORG	RBMA + $0500

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $0600

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0700

	DC.B	$A8,$88,$A8

	ORG	RBMA + $0800

	DC.B	$88,$88,$88

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

	.END
