; FRAME # 1  TRAP  /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$FF,$FF,$FF,$FF,$FF,$FC

	ORG	RBMA + $0900

	DC.B	$FF,$FF,$FF,$FF,$FF,$FC

	ORG	RBMA + $0A00

	DC.B	$FF,$FF,$FF,$FF,$FF,$FC

	ORG	RBMA + $0B00

	DC.B	$3F,$FF,$FF,$FF,$FF,$F0

	ORG	RBMA + $0C00

	DC.B	$3F,$FF,$FF,$FF,$FF,$F0

	ORG	RBMA + $0D00

	DC.B	$3F,$FF,$FF,$FF,$FF,$F0

	ORG	RBMA + $0E00

	DC.B	$0F,$FF,$FF,$FF,$FF,$C0

	ORG	RBMA + $0F00

	DC.B	$0F,$FF,$FF,$FF,$FF,$C0

	ORG	RBMA + $1000

	DC.B	$0F,$FF,$FF,$FF,$FF,$C0

	ORG	RBMA + $1100

	DC.B	$03,$FF,$FF,$FF,$FF,$00

	ORG	RBMA + $1200

	DC.B	$03,$FF,$FF,$FF,$FF,$00

	ORG	RBMA + $1300

	DC.B	$03,$FF,$FF,$FF,$FF,$00

	ORG	RBMA + $1400

	DC.B	$00,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $1500

	DC.B	$00,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $1600

	DC.B	$00,$FF,$FF,$FF,$FC,$00

	ORG	RBMA + $1700

	DC.B	$00,$3F,$FF,$FF,$F0,$00

	ORG	RBMA + $1800

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1900

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00,$00,$00,$00

; FRAME # 2  TRAP  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0800 + $06

	DC.B	$FF,$FF,$FD,$FF,$FF,$FC

	ORG	RBMA + $0900 + $06

	DC.B	$FF,$FF,$FD,$FF,$FF,$FC

	ORG	RBMA + $0A00 + $06

	DC.B	$FF,$FF,$FD,$FF,$FF,$FC

	ORG	RBMA + $0B00 + $06

	DC.B	$3F,$FF,$FD,$FF,$FF,$F0

	ORG	RBMA + $0C00 + $06

	DC.B	$3F,$FF,$FD,$FF,$FF,$F0

	ORG	RBMA + $0D00 + $06

	DC.B	$3F,$FF,$FD,$FF,$FF,$F0

	ORG	RBMA + $0E00 + $06

	DC.B	$0F,$FF,$FD,$FF,$FF,$C0

	ORG	RBMA + $0F00 + $06

	DC.B	$0F,$FF,$FD,$FF,$FF,$C0

	ORG	RBMA + $1000 + $06

	DC.B	$0F,$FF,$FD,$FF,$FF,$C0

	ORG	RBMA + $1100 + $06

	DC.B	$03,$FF,$FD,$FF,$FF,$00

	ORG	RBMA + $1200 + $06

	DC.B	$03,$FF,$FD,$FF,$FF,$00

	ORG	RBMA + $1300 + $06

	DC.B	$03,$FF,$FD,$FF,$FF,$00

	ORG	RBMA + $1400 + $06

	DC.B	$00,$FF,$FD,$FF,$FC,$00

	ORG	RBMA + $1500 + $06

	DC.B	$00,$FF,$FD,$FF,$FC,$00

	ORG	RBMA + $1600 + $06

	DC.B	$00,$FF,$FD,$FF,$FC,$00

	ORG	RBMA + $1700 + $06

	DC.B	$00,$3F,$FD,$FF,$F0,$00

	ORG	RBMA + $1800 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1900 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$00,$00,$00,$00,$00

; FRAME # 3  TRAP  /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0800 + $0C

	DC.B	$FF,$FF,$F5,$7F,$FF,$FC

	ORG	RBMA + $0900 + $0C

	DC.B	$FF,$FF,$F5,$7F,$FF,$FC

	ORG	RBMA + $0A00 + $0C

	DC.B	$FF,$FF,$F5,$7F,$FF,$FC

	ORG	RBMA + $0B00 + $0C

	DC.B	$3F,$FF,$F5,$7F,$FF,$F0

	ORG	RBMA + $0C00 + $0C

	DC.B	$3F,$FF,$F5,$7F,$FF,$F0

	ORG	RBMA + $0D00 + $0C

	DC.B	$3F,$FF,$F5,$7F,$FF,$F0

	ORG	RBMA + $0E00 + $0C

	DC.B	$0F,$FF,$F5,$7F,$FF,$C0

	ORG	RBMA + $0F00 + $0C

	DC.B	$0F,$FF,$F5,$7F,$FF,$C0

	ORG	RBMA + $1000 + $0C

	DC.B	$0F,$FF,$F5,$7F,$FF,$C0

	ORG	RBMA + $1100 + $0C

	DC.B	$03,$FF,$F5,$7F,$FF,$00

	ORG	RBMA + $1200 + $0C

	DC.B	$03,$FF,$F5,$7F,$FF,$00

	ORG	RBMA + $1300 + $0C

	DC.B	$03,$FF,$F5,$7F,$FF,$00

	ORG	RBMA + $1400 + $0C

	DC.B	$00,$FF,$D5,$5F,$FC,$00

	ORG	RBMA + $1500 + $0C

	DC.B	$00,$FF,$55,$57,$FC,$00

	ORG	RBMA + $1600 + $0C

	DC.B	$00,$FD,$55,$55,$FC,$00

	ORG	RBMA + $1700 + $0C

	DC.B	$00,$35,$55,$55,$70,$00

	ORG	RBMA + $1800 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1900 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1A00 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1B00 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1C00 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1D00 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1E00 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1F00 + $0C

	DC.B	$00,$00,$00,$00,$00,$00

; FRAME # 4  TRAP  /SPR

	ORG	RBMA + $0000 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0200 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0300 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0400 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0500 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0600 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0700 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0800 + $12

	DC.B	$FF,$FF,$55,$5F,$FF,$FC

	ORG	RBMA + $0900 + $12

	DC.B	$FF,$FF,$55,$5F,$FF,$FC

	ORG	RBMA + $0A00 + $12

	DC.B	$FF,$FF,$55,$5F,$FF,$FC

	ORG	RBMA + $0B00 + $12

	DC.B	$3F,$FF,$55,$5F,$FF,$F0

	ORG	RBMA + $0C00 + $12

	DC.B	$3F,$FF,$55,$5F,$FF,$F0

	ORG	RBMA + $0D00 + $12

	DC.B	$3F,$FF,$55,$5F,$FF,$F0

	ORG	RBMA + $0E00 + $12

	DC.B	$0F,$FF,$55,$5F,$FF,$C0

	ORG	RBMA + $0F00 + $12

	DC.B	$0F,$FF,$55,$5F,$FF,$C0

	ORG	RBMA + $1000 + $12

	DC.B	$0F,$FF,$55,$5F,$FF,$C0

	ORG	RBMA + $1100 + $12

	DC.B	$03,$FD,$55,$57,$FF,$00

	ORG	RBMA + $1200 + $12

	DC.B	$03,$FD,$55,$57,$FF,$00

	ORG	RBMA + $1300 + $12

	DC.B	$03,$F5,$55,$55,$FF,$00

	ORG	RBMA + $1400 + $12

	DC.B	$00,$F5,$55,$55,$FC,$00

	ORG	RBMA + $1500 + $12

	DC.B	$00,$D5,$55,$55,$7C,$00

	ORG	RBMA + $1600 + $12

	DC.B	$00,$D5,$55,$55,$7C,$00

	ORG	RBMA + $1700 + $12

	DC.B	$00,$15,$55,$55,$70,$00

	ORG	RBMA + $1800 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1900 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1A00 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1B00 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1C00 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1D00 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1E00 + $12

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1F00 + $12

	DC.B	$00,$00,$00,$00,$00,$00

; FRAME # 5  TRAP  /SPR

	ORG	RBMA + $0000 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0100 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0200 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0300 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0400 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0500 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0600 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0700 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $0800 + $18

	DC.B	$FF,$D5,$55,$55,$5F,$FC

	ORG	RBMA + $0900 + $18

	DC.B	$FF,$D5,$55,$55,$5F,$FC

	ORG	RBMA + $0A00 + $18

	DC.B	$FF,$D5,$55,$55,$5F,$FC

	ORG	RBMA + $0B00 + $18

	DC.B	$3F,$D5,$55,$55,$5F,$F0

	ORG	RBMA + $0C00 + $18

	DC.B	$3F,$D5,$55,$55,$5F,$F0

	ORG	RBMA + $0D00 + $18

	DC.B	$3F,$D5,$55,$55,$5F,$F0

	ORG	RBMA + $0E00 + $18

	DC.B	$0F,$D5,$55,$55,$5F,$C0

	ORG	RBMA + $0F00 + $18

	DC.B	$0F,$D5,$55,$55,$5F,$C0

	ORG	RBMA + $1000 + $18

	DC.B	$0F,$D5,$55,$55,$5F,$C0

	ORG	RBMA + $1100 + $18

	DC.B	$03,$D5,$55,$55,$5F,$00

	ORG	RBMA + $1200 + $18

	DC.B	$03,$D5,$55,$55,$5F,$00

	ORG	RBMA + $1300 + $18

	DC.B	$03,$D5,$55,$55,$5F,$00

	ORG	RBMA + $1400 + $18

	DC.B	$00,$D5,$55,$55,$5C,$00

	ORG	RBMA + $1500 + $18

	DC.B	$00,$D5,$55,$55,$5C,$00

	ORG	RBMA + $1600 + $18

	DC.B	$00,$D5,$55,$55,$5C,$00

	ORG	RBMA + $1700 + $18

	DC.B	$00,$15,$55,$55,$50,$00

	ORG	RBMA + $1800 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1900 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1A00 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1B00 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1C00 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1D00 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1E00 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	ORG	RBMA + $1F00 + $18

	DC.B	$00,$00,$00,$00,$00,$00

	.END
