; FRAME # 1  VROCK3/SPR

	ORG	RBMA + $0000

	DC.B	$0A,$80,$00

	ORG	RBMA + $0100

	DC.B	$0A,$80,$00

	ORG	RBMA + $0200

	DC.B	$06,$80,$00

	ORG	RBMA + $0300

	DC.B	$14,$80,$00

	ORG	RBMA + $0400

	DC.B	$05,$00,$00

	ORG	RBMA + $0500

	DC.B	$14,$40,$00

	ORG	RBMA + $0600

	DC.B	$01,$00,$00

	ORG	RBMA + $0700

	DC.B	$04,$40,$00

	ORG	RBMA + $0800

	DC.B	$14,$40,$00

	ORG	RBMA + $0900

	DC.B	$05,$00,$00

	ORG	RBMA + $0A00

	DC.B	$04,$00,$00

	ORG	RBMA + $0B00

	DC.B	$11,$10,$00

	ORG	RBMA + $0C00

	DC.B	$14,$40,$00

	ORG	RBMA + $0D00

	DC.B	$44,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$40,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  VROCK3/SPR

	ORG	RBMA + $0000 + $03

	DC.B	$0A,$80,$00

	ORG	RBMA + $0100 + $03

	DC.B	$1A,$80,$00

	ORG	RBMA + $0200 + $03

	DC.B	$2A,$80,$00

	ORG	RBMA + $0300 + $03

	DC.B	$14,$80,$00

	ORG	RBMA + $0400 + $03

	DC.B	$24,$40,$00

	ORG	RBMA + $0500 + $03

	DC.B	$15,$40,$00

	ORG	RBMA + $0600 + $03

	DC.B	$59,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$15,$40,$00

	ORG	RBMA + $0800 + $03

	DC.B	$54,$40,$00

	ORG	RBMA + $0900 + $03

	DC.B	$14,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$51,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$50,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$50,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$40,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  VROCK3/SPR

	ORG	RBMA + $0000 + $06

	DC.B	$0A,$80,$00

	ORG	RBMA + $0100 + $06

	DC.B	$0A,$90,$00

	ORG	RBMA + $0200 + $06

	DC.B	$16,$50,$00

	ORG	RBMA + $0300 + $06

	DC.B	$14,$90,$00

	ORG	RBMA + $0400 + $06

	DC.B	$05,$54,$00

	ORG	RBMA + $0500 + $06

	DC.B	$15,$50,$00

	ORG	RBMA + $0600 + $06

	DC.B	$41,$54,$00

	ORG	RBMA + $0700 + $06

	DC.B	$05,$40,$00

	ORG	RBMA + $0800 + $06

	DC.B	$14,$50,$00

	ORG	RBMA + $0900 + $06

	DC.B	$05,$44,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$14,$10,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$11,$10,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$04,$40,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$04,$40,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  VROCK3/SPR

	ORG	RBMA + $0000 + $09

	DC.B	$0A,$80,$00

	ORG	RBMA + $0100 + $09

	DC.B	$0A,$90,$00

	ORG	RBMA + $0200 + $09

	DC.B	$0A,$60,$00

	ORG	RBMA + $0300 + $09

	DC.B	$08,$50,$00

	ORG	RBMA + $0400 + $09

	DC.B	$04,$60,$00

	ORG	RBMA + $0500 + $09

	DC.B	$05,$50,$00

	ORG	RBMA + $0600 + $09

	DC.B	$01,$94,$00

	ORG	RBMA + $0700 + $09

	DC.B	$05,$50,$00

	ORG	RBMA + $0800 + $09

	DC.B	$04,$54,$00

	ORG	RBMA + $0900 + $09

	DC.B	$00,$50,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$01,$14,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$00,$14,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$00,$14,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$04,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

	.END
