; FRAME # 1  VROCK /SPR

	ORG	RBMA + $0000

	DC.B	$02,$A0,$00

	ORG	RBMA + $0100

	DC.B	$0A,$A8,$00

	ORG	RBMA + $0200

	DC.B	$2A,$A8,$00

	ORG	RBMA + $0300

	DC.B	$2A,$AA,$00

	ORG	RBMA + $0400

	DC.B	$2A,$6A,$00

	ORG	RBMA + $0500

	DC.B	$AA,$AA,$80

	ORG	RBMA + $0600

	DC.B	$AA,$6A,$A0

	ORG	RBMA + $0700

	DC.B	$A9,$9A,$A0

	ORG	RBMA + $0800

	DC.B	$A5,$AA,$60

	ORG	RBMA + $0900

	DC.B	$65,$A6,$A0

	ORG	RBMA + $0A00

	DC.B	$99,$5A,$80

	ORG	RBMA + $0B00

	DC.B	$29,$AA,$80

	ORG	RBMA + $0C00

	DC.B	$2A,$99,$80

	ORG	RBMA + $0D00

	DC.B	$09,$66,$00

	ORG	RBMA + $0E00

	DC.B	$02,$60,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  VROCK /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$0A,$A8,$00

	ORG	RBMA + $0300 + $03

	DC.B	$09,$A6,$00

	ORG	RBMA + $0400 + $03

	DC.B	$19,$A6,$00

	ORG	RBMA + $0500 + $03

	DC.B	$2A,$5A,$80

	ORG	RBMA + $0600 + $03

	DC.B	$AA,$A9,$A0

	ORG	RBMA + $0700 + $03

	DC.B	$AA,$A6,$A0

	ORG	RBMA + $0800 + $03

	DC.B	$AA,$AA,$A0

	ORG	RBMA + $0900 + $03

	DC.B	$AA,$AA,$A0

	ORG	RBMA + $0A00 + $03

	DC.B	$2A,$AA,$60

	ORG	RBMA + $0B00 + $03

	DC.B	$2A,$AA,$60

	ORG	RBMA + $0C00 + $03

	DC.B	$02,$AA,$80

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$AA,$80

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  VROCK /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$2A,$A8,$00

	ORG	RBMA + $0100 + $06

	DC.B	$2A,$AA,$00

	ORG	RBMA + $0200 + $06

	DC.B	$AA,$AA,$00

	ORG	RBMA + $0300 + $06

	DC.B	$AA,$AA,$80

	ORG	RBMA + $0400 + $06

	DC.B	$AA,$AA,$60

	ORG	RBMA + $0500 + $06

	DC.B	$AA,$AA,$60

	ORG	RBMA + $0600 + $06

	DC.B	$AA,$AA,$A0

	ORG	RBMA + $0700 + $06

	DC.B	$AA,$AA,$A0

	ORG	RBMA + $0800 + $06

	DC.B	$AA,$AA,$80

	ORG	RBMA + $0900 + $06

	DC.B	$2A,$AA,$80

	ORG	RBMA + $0A00 + $06

	DC.B	$2A,$AA,$80

	ORG	RBMA + $0B00 + $06

	DC.B	$2A,$AA,$80

	ORG	RBMA + $0C00 + $06

	DC.B	$0A,$AA,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$0A,$AA,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$02,$94,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  VROCK /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$0A,$80,$00

	ORG	RBMA + $0300 + $09

	DC.B	$2A,$AA,$00

	ORG	RBMA + $0400 + $09

	DC.B	$AA,$AA,$80

	ORG	RBMA + $0500 + $09

	DC.B	$AA,$AA,$A0

	ORG	RBMA + $0600 + $09

	DC.B	$AA,$AA,$A0

	ORG	RBMA + $0700 + $09

	DC.B	$AA,$AA,$A0

	ORG	RBMA + $0800 + $09

	DC.B	$A9,$9A,$A0

	ORG	RBMA + $0900 + $09

	DC.B	$AA,$AA,$A0

	ORG	RBMA + $0A00 + $09

	DC.B	$2A,$5A,$A0

	ORG	RBMA + $0B00 + $09

	DC.B	$26,$66,$80

	ORG	RBMA + $0C00 + $09

	DC.B	$09,$A6,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$02,$54,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

	.END
