; FRAME # 1  VROCK2/SPR

	ORG	RBMA + $0000

	DC.B	$02,$A8,$00

	ORG	RBMA + $0100

	DC.B	$0A,$A8,$00

	ORG	RBMA + $0200

	DC.B	$0A,$E8,$80

	ORG	RBMA + $0300

	DC.B	$0B,$A0,$A0

	ORG	RBMA + $0400

	DC.B	$00,$E0,$A0

	ORG	RBMA + $0500

	DC.B	$00,$80,$A8

	ORG	RBMA + $0600

	DC.B	$A0,$02,$BA

	ORG	RBMA + $0700

	DC.B	$BA,$02,$EE

	ORG	RBMA + $0800

	DC.B	$AA,$00,$AA

	ORG	RBMA + $0900

	DC.B	$BA,$00,$28

	ORG	RBMA + $0A00

	DC.B	$2E,$80,$00

	ORG	RBMA + $0B00

	DC.B	$2A,$8A,$00

	ORG	RBMA + $0C00

	DC.B	$07,$8A,$A0

	ORG	RBMA + $0D00

	DC.B	$06,$AA,$A0

	ORG	RBMA + $0E00

	DC.B	$01,$AA,$A0

	ORG	RBMA + $0F00

	DC.B	$00,$A2,$80

	.END
