; FRAME # 1  BOY   /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$28,$0A,$80

	ORG	RBMA + $0700

	DC.B	$20,$0A,$80

	ORG	RBMA + $0800

	DC.B	$A0,$08,$00

	ORG	RBMA + $0900

	DC.B	$80,$08,$00

	ORG	RBMA + $0A00

	DC.B	$80,$08,$00

	ORG	RBMA + $0B00

	DC.B	$A0,$08,$00

	ORG	RBMA + $0C00

	DC.B	$20,$08,$00

	ORG	RBMA + $0D00

	DC.B	$20,$08,$00

	ORG	RBMA + $0E00

	DC.B	$28,$38,$00

	ORG	RBMA + $0F00

	DC.B	$28,$38,$00

	ORG	RBMA + $1000

	DC.B	$08,$E0,$00

	ORG	RBMA + $1100

	DC.B	$08,$E0,$00

	ORG	RBMA + $1200

	DC.B	$0A,$E0,$00

	ORG	RBMA + $1300

	DC.B	$0A,$E0,$00

	ORG	RBMA + $1400

	DC.B	$09,$60,$00

	ORG	RBMA + $1500

	DC.B	$09,$60,$00

	ORG	RBMA + $1600

	DC.B	$0A,$A5,$00

	ORG	RBMA + $1700

	DC.B	$0A,$A5,$00

	ORG	RBMA + $1800

	DC.B	$02,$88,$00

	ORG	RBMA + $1900

	DC.B	$02,$88,$00

	ORG	RBMA + $1A00

	DC.B	$02,$A8,$00

	ORG	RBMA + $1B00

	DC.B	$02,$A8,$00

	ORG	RBMA + $1C00

	DC.B	$02,$A0,$00

	ORG	RBMA + $1D00

	DC.B	$02,$A0,$00

	ORG	RBMA + $1E00

	DC.B	$02,$A0,$00

	ORG	RBMA + $1F00

	DC.B	$02,$A0,$00

	ORG	RBMA + $2000

	DC.B	$02,$A0,$00

	ORG	RBMA + $2100

	DC.B	$02,$A0,$00

	ORG	RBMA + $2200

	DC.B	$00,$80,$00

	ORG	RBMA + $2300

	DC.B	$00,$40,$00

	ORG	RBMA + $2400

	DC.B	$02,$50,$00

	ORG	RBMA + $2500

	DC.B	$02,$50,$00

	ORG	RBMA + $2600

	DC.B	$02,$90,$00

	ORG	RBMA + $2700

	DC.B	$02,$90,$00

	ORG	RBMA + $2800

	DC.B	$00,$A8,$00

	ORG	RBMA + $2900

	DC.B	$00,$A8,$00

	ORG	RBMA + $2A00

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00

	DC.B	$00,$00,$00

; FRAME # 2  BOY   /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$A8,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$A8,$00

	ORG	RBMA + $0800 + $03

	DC.B	$08,$80,$00

	ORG	RBMA + $0900 + $03

	DC.B	$08,$80,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$20,$80,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$20,$80,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$08,$80,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$08,$80,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$08,$A0,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$08,$A0,$00

	ORG	RBMA + $1000 + $03

	DC.B	$00,$A0,$30

	ORG	RBMA + $1100 + $03

	DC.B	$00,$A0,$F0

	ORG	RBMA + $1200 + $03

	DC.B	$00,$A3,$00

	ORG	RBMA + $1300 + $03

	DC.B	$00,$A3,$00

	ORG	RBMA + $1400 + $03

	DC.B	$02,$94,$00

	ORG	RBMA + $1500 + $03

	DC.B	$02,$94,$00

	ORG	RBMA + $1600 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $1700 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $1800 + $03

	DC.B	$00,$A0,$00

	ORG	RBMA + $1900 + $03

	DC.B	$00,$A0,$00

	ORG	RBMA + $1A00 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $1B00 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $2000 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $2100 + $03

	DC.B	$02,$A0,$00

	ORG	RBMA + $2200 + $03

	DC.B	$00,$80,$00

	ORG	RBMA + $2300 + $03

	DC.B	$00,$40,$00

	ORG	RBMA + $2400 + $03

	DC.B	$02,$50,$00

	ORG	RBMA + $2500 + $03

	DC.B	$02,$50,$00

	ORG	RBMA + $2600 + $03

	DC.B	$02,$90,$00

	ORG	RBMA + $2700 + $03

	DC.B	$02,$90,$00

	ORG	RBMA + $2800 + $03

	DC.B	$00,$A8,$00

	ORG	RBMA + $2900 + $03

	DC.B	$00,$A8,$00

	ORG	RBMA + $2A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  BOY   /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$0A,$80,$00

	ORG	RBMA + $0700 + $06

	DC.B	$0A,$80,$00

	ORG	RBMA + $0800 + $06

	DC.B	$08,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$08,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$02,$08,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$02,$08,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$88,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$88,$00

	ORG	RBMA + $1000 + $06

	DC.B	$00,$8A,$00

	ORG	RBMA + $1100 + $06

	DC.B	$00,$8A,$00

	ORG	RBMA + $1200 + $06

	DC.B	$00,$A8,$00

	ORG	RBMA + $1300 + $06

	DC.B	$00,$A8,$00

	ORG	RBMA + $1400 + $06

	DC.B	$02,$94,$00

	ORG	RBMA + $1500 + $06

	DC.B	$02,$97,$FC

	ORG	RBMA + $1600 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $1700 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $1800 + $06

	DC.B	$00,$A0,$00

	ORG	RBMA + $1900 + $06

	DC.B	$00,$A0,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $2000 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $2100 + $06

	DC.B	$02,$A0,$00

	ORG	RBMA + $2200 + $06

	DC.B	$00,$80,$00

	ORG	RBMA + $2300 + $06

	DC.B	$00,$40,$00

	ORG	RBMA + $2400 + $06

	DC.B	$02,$50,$00

	ORG	RBMA + $2500 + $06

	DC.B	$02,$50,$00

	ORG	RBMA + $2600 + $06

	DC.B	$02,$90,$00

	ORG	RBMA + $2700 + $06

	DC.B	$02,$90,$00

	ORG	RBMA + $2800 + $06

	DC.B	$00,$A8,$00

	ORG	RBMA + $2900 + $06

	DC.B	$00,$A8,$00

	ORG	RBMA + $2A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  BOY   /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$28,$0A,$80

	ORG	RBMA + $0700 + $09

	DC.B	$20,$0A,$80

	ORG	RBMA + $0800 + $09

	DC.B	$A0,$08,$00

	ORG	RBMA + $0900 + $09

	DC.B	$80,$08,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$A0,$08,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$20,$08,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$28,$08,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$08,$08,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$0A,$08,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$0A,$08,$00

	ORG	RBMA + $1000 + $09

	DC.B	$02,$08,$00

	ORG	RBMA + $1100 + $09

	DC.B	$02,$A8,$00

	ORG	RBMA + $1200 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $1300 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $1400 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $1500 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $1600 + $09

	DC.B	$16,$A0,$00

	ORG	RBMA + $1700 + $09

	DC.B	$16,$A1,$40

	ORG	RBMA + $1800 + $09

	DC.B	$08,$A1,$F0

	ORG	RBMA + $1900 + $09

	DC.B	$08,$A2,$3C

	ORG	RBMA + $1A00 + $09

	DC.B	$0A,$A8,$0F

	ORG	RBMA + $1B00 + $09

	DC.B	$0A,$A8,$00

	ORG	RBMA + $1C00 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $1D00 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $1E00 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $1F00 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $2000 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $2100 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $2200 + $09

	DC.B	$00,$80,$00

	ORG	RBMA + $2300 + $09

	DC.B	$00,$40,$00

	ORG	RBMA + $2400 + $09

	DC.B	$02,$50,$00

	ORG	RBMA + $2500 + $09

	DC.B	$02,$50,$00

	ORG	RBMA + $2600 + $09

	DC.B	$02,$90,$00

	ORG	RBMA + $2700 + $09

	DC.B	$02,$90,$00

	ORG	RBMA + $2800 + $09

	DC.B	$00,$A8,$00

	ORG	RBMA + $2900 + $09

	DC.B	$00,$A8,$00

	ORG	RBMA + $2A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00 + $09

	DC.B	$00,$00,$00

; FRAME # 5  BOY   /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$A8,$00

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$A8,$00

	ORG	RBMA + $0800 + $0C

	DC.B	$0A,$80,$00

	ORG	RBMA + $0900 + $0C

	DC.B	$0A,$80,$00

	ORG	RBMA + $0A00 + $0C

	DC.B	$20,$80,$00

	ORG	RBMA + $0B00 + $0C

	DC.B	$20,$80,$00

	ORG	RBMA + $0C00 + $0C

	DC.B	$0A,$80,$00

	ORG	RBMA + $0D00 + $0C

	DC.B	$0A,$80,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $1000 + $0C

	DC.B	$00,$A0,$00

	ORG	RBMA + $1100 + $0C

	DC.B	$00,$A0,$00

	ORG	RBMA + $1200 + $0C

	DC.B	$00,$A0,$00

	ORG	RBMA + $1300 + $0C

	DC.B	$00,$A0,$00

	ORG	RBMA + $1400 + $0C

	DC.B	$02,$94,$00

	ORG	RBMA + $1500 + $0C

	DC.B	$02,$97,$FC

	ORG	RBMA + $1600 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $1700 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $1800 + $0C

	DC.B	$00,$A0,$00

	ORG	RBMA + $1900 + $0C

	DC.B	$00,$A0,$00

	ORG	RBMA + $1A00 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $1B00 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $1C00 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $1D00 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $1E00 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $1F00 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $2000 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $2100 + $0C

	DC.B	$02,$A0,$00

	ORG	RBMA + $2200 + $0C

	DC.B	$00,$80,$00

	ORG	RBMA + $2300 + $0C

	DC.B	$00,$40,$00

	ORG	RBMA + $2400 + $0C

	DC.B	$02,$50,$00

	ORG	RBMA + $2500 + $0C

	DC.B	$02,$50,$00

	ORG	RBMA + $2600 + $0C

	DC.B	$02,$90,$00

	ORG	RBMA + $2700 + $0C

	DC.B	$02,$90,$00

	ORG	RBMA + $2800 + $0C

	DC.B	$00,$A8,$00

	ORG	RBMA + $2900 + $0C

	DC.B	$00,$A8,$00

	ORG	RBMA + $2A00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00 + $0C

	DC.B	$00,$00,$00

; FRAME # 6  BOY   /SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0F

	DC.B	$0A,$80,$00

	ORG	RBMA + $0700 + $0F

	DC.B	$0A,$80,$00

	ORG	RBMA + $0800 + $0F

	DC.B	$08,$00,$00

	ORG	RBMA + $0900 + $0F

	DC.B	$08,$00,$00

	ORG	RBMA + $0A00 + $0F

	DC.B	$08,$08,$00

	ORG	RBMA + $0B00 + $0F

	DC.B	$0A,$08,$00

	ORG	RBMA + $0C00 + $0F

	DC.B	$02,$20,$00

	ORG	RBMA + $0D00 + $0F

	DC.B	$02,$20,$00

	ORG	RBMA + $0E00 + $0F

	DC.B	$02,$88,$00

	ORG	RBMA + $0F00 + $0F

	DC.B	$02,$88,$00

	ORG	RBMA + $1000 + $0F

	DC.B	$00,$8A,$00

	ORG	RBMA + $1100 + $0F

	DC.B	$00,$8A,$30

	ORG	RBMA + $1200 + $0F

	DC.B	$00,$A8,$F0

	ORG	RBMA + $1300 + $0F

	DC.B	$00,$AB,$00

	ORG	RBMA + $1400 + $0F

	DC.B	$02,$97,$00

	ORG	RBMA + $1500 + $0F

	DC.B	$02,$94,$00

	ORG	RBMA + $1600 + $0F

	DC.B	$02,$A0,$00

	ORG	RBMA + $1700 + $0F

	DC.B	$02,$A0,$00

	ORG	RBMA + $1800 + $0F

	DC.B	$00,$A0,$00

	ORG	RBMA + $1900 + $0F

	DC.B	$00,$A0,$00

	ORG	RBMA + $1A00 + $0F

	DC.B	$02,$A0,$00

	ORG	RBMA + $1B00 + $0F

	DC.B	$02,$A0,$00

	ORG	RBMA + $1C00 + $0F

	DC.B	$02,$A0,$00

	ORG	RBMA + $1D00 + $0F

	DC.B	$02,$A0,$00

	ORG	RBMA + $1E00 + $0F

	DC.B	$02,$A0,$00

	ORG	RBMA + $1F00 + $0F

	DC.B	$02,$A0,$00

	ORG	RBMA + $2000 + $0F

	DC.B	$02,$A0,$00

	ORG	RBMA + $2100 + $0F

	DC.B	$02,$A0,$00

	ORG	RBMA + $2200 + $0F

	DC.B	$00,$80,$00

	ORG	RBMA + $2300 + $0F

	DC.B	$00,$40,$00

	ORG	RBMA + $2400 + $0F

	DC.B	$02,$50,$00

	ORG	RBMA + $2500 + $0F

	DC.B	$02,$50,$00

	ORG	RBMA + $2600 + $0F

	DC.B	$02,$90,$00

	ORG	RBMA + $2700 + $0F

	DC.B	$02,$90,$00

	ORG	RBMA + $2800 + $0F

	DC.B	$00,$A8,$00

	ORG	RBMA + $2900 + $0F

	DC.B	$00,$A8,$00

	ORG	RBMA + $2A00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2B00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2C00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2D00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2E00 + $0F

	DC.B	$00,$00,$00

	ORG	RBMA + $2F00 + $0F

	DC.B	$00,$00,$00

	.END
