; FRAME # 1  WIN1  /SPR

	ORG	RBMA + $0000

	DC.B	$0A,$AA

	ORG	RBMA + $0100

	DC.B	$20,$AA

	ORG	RBMA + $0200

	DC.B	$20,$AA

	ORG	RBMA + $0300

	DC.B	$00,$28

	ORG	RBMA + $0400

	DC.B	$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00

; FRAME # 2  WIN1  /SPR

	ORG	RBMA + $0000 + $02

	DC.B	$00,$A8

	ORG	RBMA + $0100 + $02

	DC.B	$00,$A8

	ORG	RBMA + $0200 + $02

	DC.B	$00,$A8

	ORG	RBMA + $0300 + $02

	DC.B	$DA,$68

	ORG	RBMA + $0400 + $02

	DC.B	$00,$60

	ORG	RBMA + $0500 + $02

	DC.B	$01,$68

	ORG	RBMA + $0600 + $02

	DC.B	$01,$6A

	ORG	RBMA + $0700 + $02

	DC.B	$01,$5A

	ORG	RBMA + $0800 + $02

	DC.B	$02,$AA

	ORG	RBMA + $0900 + $02

	DC.B	$02,$5A

	ORG	RBMA + $0A00 + $02

	DC.B	$00,$A8

	ORG	RBMA + $0B00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $02

	DC.B	$00,$00

; FRAME # 3  WIN1  /SPR

	ORG	RBMA + $0000 + $04

	DC.B	$00,$2A

	ORG	RBMA + $0100 + $04

	DC.B	$00,$2A

	ORG	RBMA + $0200 + $04

	DC.B	$00,$AA

	ORG	RBMA + $0300 + $04

	DC.B	$02,$AA

	ORG	RBMA + $0400 + $04

	DC.B	$08,$28

	ORG	RBMA + $0500 + $04

	DC.B	$08,$96

	ORG	RBMA + $0600 + $04

	DC.B	$04,$96

	ORG	RBMA + $0700 + $04

	DC.B	$04,$96

	ORG	RBMA + $0800 + $04

	DC.B	$04,$AA

	ORG	RBMA + $0900 + $04

	DC.B	$04,$96

	ORG	RBMA + $0A00 + $04

	DC.B	$0C,$28

	ORG	RBMA + $0B00 + $04

	DC.B	$0C,$00

	ORG	RBMA + $0C00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $04

	DC.B	$00,$00

; FRAME # 4  WIN1  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$26

	ORG	RBMA + $0100 + $06

	DC.B	$00,$9A

	ORG	RBMA + $0200 + $06

	DC.B	$02,$AA

	ORG	RBMA + $0300 + $06

	DC.B	$02,$AA

	ORG	RBMA + $0400 + $06

	DC.B	$00,$A8

	ORG	RBMA + $0500 + $06

	DC.B	$00,$96

	ORG	RBMA + $0600 + $06

	DC.B	$00,$96

	ORG	RBMA + $0700 + $06

	DC.B	$00,$96

	ORG	RBMA + $0800 + $06

	DC.B	$00,$AA

	ORG	RBMA + $0900 + $06

	DC.B	$00,$96

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$28

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00

	.END
