; FRAME # 1  WIN5  /SPR

	ORG	RBMA + $0000

	DC.B	$28,$80

	ORG	RBMA + $0100

	DC.B	$20,$00

	ORG	RBMA + $0200

	DC.B	$20,$00

	ORG	RBMA + $0300

	DC.B	$20,$00

	ORG	RBMA + $0400

	DC.B	$0A,$00

	ORG	RBMA + $0500

	DC.B	$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00

; FRAME # 2  WIN5  /SPR

	ORG	RBMA + $0000 + $02

	DC.B	$2A,$08

	ORG	RBMA + $0100 + $02

	DC.B	$2A,$08

	ORG	RBMA + $0200 + $02

	DC.B	$2A,$A8

	ORG	RBMA + $0300 + $02

	DC.B	$09,$A0

	ORG	RBMA + $0400 + $02

	DC.B	$09,$60

	ORG	RBMA + $0500 + $02

	DC.B	$29,$40

	ORG	RBMA + $0600 + $02

	DC.B	$F9,$50

	ORG	RBMA + $0700 + $02

	DC.B	$C1,$50

	ORG	RBMA + $0800 + $02

	DC.B	$C3,$F0

	ORG	RBMA + $0900 + $02

	DC.B	$00,$F0

	ORG	RBMA + $0A00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0B00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $02

	DC.B	$00,$00

; FRAME # 3  WIN5  /SPR

	ORG	RBMA + $0000 + $04

	DC.B	$82,$A0

	ORG	RBMA + $0100 + $04

	DC.B	$A0,$A0

	ORG	RBMA + $0200 + $04

	DC.B	$A8,$20

	ORG	RBMA + $0300 + $04

	DC.B	$26,$08

	ORG	RBMA + $0400 + $04

	DC.B	$15,$80

	ORG	RBMA + $0500 + $04

	DC.B	$15,$A0

	ORG	RBMA + $0600 + $04

	DC.B	$15,$08

	ORG	RBMA + $0700 + $04

	DC.B	$37,$00

	ORG	RBMA + $0800 + $04

	DC.B	$3F,$00

	ORG	RBMA + $0900 + $04

	DC.B	$3F,$00

	ORG	RBMA + $0A00 + $04

	DC.B	$0C,$00

	ORG	RBMA + $0B00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $04

	DC.B	$00,$00

	.END
