; FRAME # 1  WIN6  /SPR

	ORG	RBMA + $0000

	DC.B	$82,$80

	ORG	RBMA + $0100

	DC.B	$81,$A0

	ORG	RBMA + $0200

	DC.B	$81,$50

	ORG	RBMA + $0300

	DC.B	$80,$50

	ORG	RBMA + $0400

	DC.B	$20,$A0

	ORG	RBMA + $0500

	DC.B	$A0,$F8

	ORG	RBMA + $0600

	DC.B	$0C,$20

	ORG	RBMA + $0700

	DC.B	$03,$00

	ORG	RBMA + $0800

	DC.B	$00,$C0

	ORG	RBMA + $0900

	DC.B	$00,$30

	ORG	RBMA + $0A00

	DC.B	$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00

; FRAME # 2  WIN6  /SPR

	ORG	RBMA + $0000 + $02

	DC.B	$02,$80

	ORG	RBMA + $0100 + $02

	DC.B	$02,$A0

	ORG	RBMA + $0200 + $02

	DC.B	$02,$A0

	ORG	RBMA + $0300 + $02

	DC.B	$12,$A0

	ORG	RBMA + $0400 + $02

	DC.B	$AA,$A8

	ORG	RBMA + $0500 + $02

	DC.B	$AA,$A8

	ORG	RBMA + $0600 + $02

	DC.B	$10,$A0

	ORG	RBMA + $0700 + $02

	DC.B	$10,$50

	ORG	RBMA + $0800 + $02

	DC.B	$1D,$50

	ORG	RBMA + $0900 + $02

	DC.B	$11,$70

	ORG	RBMA + $0A00 + $02

	DC.B	$13,$F0

	ORG	RBMA + $0B00 + $02

	DC.B	$10,$A0

	ORG	RBMA + $0C00 + $02

	DC.B	$10,$00

	ORG	RBMA + $0D00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $02

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $02

	DC.B	$00,$00

; FRAME # 3  WIN6  /SPR

	ORG	RBMA + $0000 + $04

	DC.B	$02,$80

	ORG	RBMA + $0100 + $04

	DC.B	$82,$A0

	ORG	RBMA + $0200 + $04

	DC.B	$A2,$A0

	ORG	RBMA + $0300 + $04

	DC.B	$2A,$A0

	ORG	RBMA + $0400 + $04

	DC.B	$0A,$A0

	ORG	RBMA + $0500 + $04

	DC.B	$02,$A0

	ORG	RBMA + $0600 + $04

	DC.B	$30,$A0

	ORG	RBMA + $0700 + $04

	DC.B	$0C,$50

	ORG	RBMA + $0800 + $04

	DC.B	$01,$50

	ORG	RBMA + $0900 + $04

	DC.B	$01,$70

	ORG	RBMA + $0A00 + $04

	DC.B	$03,$F0

	ORG	RBMA + $0B00 + $04

	DC.B	$00,$A0

	ORG	RBMA + $0C00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $04

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $04

	DC.B	$00,$00

; FRAME # 4  WIN6  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$0A,$A8

	ORG	RBMA + $0100 + $06

	DC.B	$2A,$08

	ORG	RBMA + $0200 + $06

	DC.B	$22,$88

	ORG	RBMA + $0300 + $06

	DC.B	$22,$88

	ORG	RBMA + $0400 + $06

	DC.B	$0A,$A0

	ORG	RBMA + $0500 + $06

	DC.B	$00,$80

	ORG	RBMA + $0600 + $06

	DC.B	$00,$A0

	ORG	RBMA + $0700 + $06

	DC.B	$01,$60

	ORG	RBMA + $0800 + $06

	DC.B	$01,$60

	ORG	RBMA + $0900 + $06

	DC.B	$03,$F0

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$A0

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00

	.END
