; FRAME # 1  WIZA  /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

	ORG	RBMA + $1000

	DC.B	$00,$54,$00

	ORG	RBMA + $1100

	DC.B	$01,$55,$40

	ORG	RBMA + $1200

	DC.B	$05,$55,$00

	ORG	RBMA + $1300

	DC.B	$05,$55,$40

	ORG	RBMA + $1400

	DC.B	$05,$55,$00

	ORG	RBMA + $1500

	DC.B	$05,$55,$40

	ORG	RBMA + $1600

	DC.B	$01,$55,$40

	ORG	RBMA + $1700

	DC.B	$01,$55,$00

	ORG	RBMA + $1800

	DC.B	$00,$54,$00

	ORG	RBMA + $1900

	DC.B	$00,$14,$00

	ORG	RBMA + $1A00

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00

	DC.B	$00,$00,$00

	ORG	RBMA + $1C00

	DC.B	$00,$00,$00

	ORG	RBMA + $1D00

	DC.B	$00,$00,$00

	ORG	RBMA + $1E00

	DC.B	$00,$00,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$00

; FRAME # 2  WIZA  /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$10,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$54,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$01,$55,$00

	ORG	RBMA + $1000 + $03

	DC.B	$07,$5D,$00

	ORG	RBMA + $1100 + $03

	DC.B	$01,$55,$00

	ORG	RBMA + $1200 + $03

	DC.B	$05,$55,$40

	ORG	RBMA + $1300 + $03

	DC.B	$05,$55,$40

	ORG	RBMA + $1400 + $03

	DC.B	$01,$55,$40

	ORG	RBMA + $1500 + $03

	DC.B	$15,$55,$50

	ORG	RBMA + $1600 + $03

	DC.B	$15,$55,$D0

	ORG	RBMA + $1700 + $03

	DC.B	$15,$55,$50

	ORG	RBMA + $1800 + $03

	DC.B	$1D,$55,$50

	ORG	RBMA + $1900 + $03

	DC.B	$15,$55,$D0

	ORG	RBMA + $1A00 + $03

	DC.B	$01,$55,$40

	ORG	RBMA + $1B00 + $03

	DC.B	$05,$57,$40

	ORG	RBMA + $1C00 + $03

	DC.B	$01,$55,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$01,$D5,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$54,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  WIZA  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$75,$04

	ORG	RBMA + $0C00 + $06

	DC.B	$14,$57,$15

	ORG	RBMA + $0D00 + $06

	DC.B	$54,$D5,$1D

	ORG	RBMA + $0E00 + $06

	DC.B	$54,$55,$35

	ORG	RBMA + $0F00 + $06

	DC.B	$51,$55,$54

	ORG	RBMA + $1000 + $06

	DC.B	$15,$5D,$54

	ORG	RBMA + $1100 + $06

	DC.B	$1D,$57,$54

	ORG	RBMA + $1200 + $06

	DC.B	$15,$57,$54

	ORG	RBMA + $1300 + $06

	DC.B	$55,$55,$75

	ORG	RBMA + $1400 + $06

	DC.B	$55,$55,$55

	ORG	RBMA + $1500 + $06

	DC.B	$55,$5D,$55

	ORG	RBMA + $1600 + $06

	DC.B	$75,$55,$55

	ORG	RBMA + $1700 + $06

	DC.B	$57,$55,$75

	ORG	RBMA + $1800 + $06

	DC.B	$15,$55,$54

	ORG	RBMA + $1900 + $06

	DC.B	$15,$57,$54

	ORG	RBMA + $1A00 + $06

	DC.B	$05,$D5,$50

	ORG	RBMA + $1B00 + $06

	DC.B	$15,$55,$40

	ORG	RBMA + $1C00 + $06

	DC.B	$51,$55,$04

	ORG	RBMA + $1D00 + $06

	DC.B	$54,$50,$15

	ORG	RBMA + $1E00 + $06

	DC.B	$54,$00,$1D

	ORG	RBMA + $1F00 + $06

	DC.B	$10,$00,$14

; FRAME # 4  WIZA  /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$01,$14,$90

	ORG	RBMA + $0C00 + $09

	DC.B	$11,$82,$94

	ORG	RBMA + $0D00 + $09

	DC.B	$75,$82,$95

	ORG	RBMA + $0E00 + $09

	DC.B	$55,$82,$9D

	ORG	RBMA + $0F00 + $09

	DC.B	$D5,$8A,$85

	ORG	RBMA + $1000 + $09

	DC.B	$11,$6A,$87

	ORG	RBMA + $1100 + $09

	DC.B	$03,$5A,$80

	ORG	RBMA + $1200 + $09

	DC.B	$01,$5A,$80

	ORG	RBMA + $1300 + $09

	DC.B	$01,$D6,$80

	ORG	RBMA + $1400 + $09

	DC.B	$02,$56,$81

	ORG	RBMA + $1500 + $09

	DC.B	$02,$95,$8D

	ORG	RBMA + $1600 + $09

	DC.B	$6A,$97,$54

	ORG	RBMA + $1700 + $09

	DC.B	$6A,$A9,$70

	ORG	RBMA + $1800 + $09

	DC.B	$0A,$AA,$40

	ORG	RBMA + $1900 + $09

	DC.B	$00,$58,$00

	ORG	RBMA + $1A00 + $09

	DC.B	$00,$54,$00

	ORG	RBMA + $1B00 + $09

	DC.B	$10,$54,$01

	ORG	RBMA + $1C00 + $09

	DC.B	$50,$3C,$05

	ORG	RBMA + $1D00 + $09

	DC.B	$54,$0F,$15

	ORG	RBMA + $1E00 + $09

	DC.B	$54,$03,$17

	ORG	RBMA + $1F00 + $09

	DC.B	$10,$00,$C4

; FRAME # 5  WIZA  /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $0C

	DC.B	$05,$01,$40

	ORG	RBMA + $0C00 + $0C

	DC.B	$0A,$02,$80

	ORG	RBMA + $0D00 + $0C

	DC.B	$02,$02,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$03,$82,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$01,$CA,$00

	ORG	RBMA + $1000 + $0C

	DC.B	$03,$4A,$00

	ORG	RBMA + $1100 + $0C

	DC.B	$03,$7A,$00

	ORG	RBMA + $1200 + $0C

	DC.B	$C2,$9A,$00

	ORG	RBMA + $1300 + $0C

	DC.B	$13,$FF,$04

	ORG	RBMA + $1400 + $0C

	DC.B	$32,$AA,$8C

	ORG	RBMA + $1500 + $0C

	DC.B	$3E,$AA,$BC

	ORG	RBMA + $1600 + $0C

	DC.B	$0E,$AA,$B0

	ORG	RBMA + $1700 + $0C

	DC.B	$0E,$AA,$B0

	ORG	RBMA + $1800 + $0C

	DC.B	$02,$AA,$00

	ORG	RBMA + $1900 + $0C

	DC.B	$00,$58,$00

	ORG	RBMA + $1A00 + $0C

	DC.B	$00,$54,$00

	ORG	RBMA + $1B00 + $0C

	DC.B	$00,$54,$00

	ORG	RBMA + $1C00 + $0C

	DC.B	$00,$3C,$00

	ORG	RBMA + $1D00 + $0C

	DC.B	$00,$0F,$00

	ORG	RBMA + $1E00 + $0C

	DC.B	$00,$03,$00

	ORG	RBMA + $1F00 + $0C

	DC.B	$00,$00,$C0

	.END
