; FRAME # 1  WIZB  /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$05,$01,$40

	ORG	RBMA + $0C00

	DC.B	$0A,$02,$80

	ORG	RBMA + $0D00

	DC.B	$02,$02,$00

	ORG	RBMA + $0E00

	DC.B	$02,$82,$00

	ORG	RBMA + $0F00

	DC.B	$02,$8A,$00

	ORG	RBMA + $1000

	DC.B	$02,$8A,$00

	ORG	RBMA + $1100

	DC.B	$02,$AA,$00

	ORG	RBMA + $1200

	DC.B	$C2,$AA,$00

	ORG	RBMA + $1300

	DC.B	$13,$FF,$00

	ORG	RBMA + $1400

	DC.B	$32,$AA,$80

	ORG	RBMA + $1500

	DC.B	$3E,$AA,$80

	ORG	RBMA + $1600

	DC.B	$0E,$AA,$B0

	ORG	RBMA + $1700

	DC.B	$0E,$AA,$B0

	ORG	RBMA + $1800

	DC.B	$02,$AA,$3C

	ORG	RBMA + $1900

	DC.B	$00,$58,$0C

	ORG	RBMA + $1A00

	DC.B	$00,$54,$05

	ORG	RBMA + $1B00

	DC.B	$00,$54,$05

	ORG	RBMA + $1C00

	DC.B	$00,$3C,$00

	ORG	RBMA + $1D00

	DC.B	$00,$0F,$00

	ORG	RBMA + $1E00

	DC.B	$00,$03,$00

	ORG	RBMA + $1F00

	DC.B	$00,$00,$C0

; FRAME # 2  WIZB  /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$05,$01,$40

	ORG	RBMA + $0C00 + $03

	DC.B	$0A,$02,$80

	ORG	RBMA + $0D00 + $03

	DC.B	$02,$02,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$02,$82,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$02,$8A,$00

	ORG	RBMA + $1000 + $03

	DC.B	$02,$8A,$00

	ORG	RBMA + $1100 + $03

	DC.B	$02,$AA,$00

	ORG	RBMA + $1200 + $03

	DC.B	$C2,$AA,$00

	ORG	RBMA + $1300 + $03

	DC.B	$13,$FF,$00

	ORG	RBMA + $1400 + $03

	DC.B	$32,$AA,$00

	ORG	RBMA + $1500 + $03

	DC.B	$3E,$AA,$00

	ORG	RBMA + $1600 + $03

	DC.B	$0E,$AA,$00

	ORG	RBMA + $1700 + $03

	DC.B	$0E,$AA,$C0

	ORG	RBMA + $1800 + $03

	DC.B	$02,$AB,$C0

	ORG	RBMA + $1900 + $03

	DC.B	$00,$5B,$C0

	ORG	RBMA + $1A00 + $03

	DC.B	$00,$57,$C0

	ORG	RBMA + $1B00 + $03

	DC.B	$00,$57,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$00,$3C,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$00,$0F,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$00,$03,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$00,$00,$C0

; FRAME # 3  WIZB  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$05,$01,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$0A,$02,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$02,$02,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$02,$82,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$02,$8A,$00

	ORG	RBMA + $1000 + $06

	DC.B	$02,$8A,$00

	ORG	RBMA + $1100 + $06

	DC.B	$0E,$AA,$00

	ORG	RBMA + $1200 + $06

	DC.B	$32,$AA,$00

	ORG	RBMA + $1300 + $06

	DC.B	$43,$FA,$00

	ORG	RBMA + $1400 + $06

	DC.B	$FA,$AA,$00

	ORG	RBMA + $1500 + $06

	DC.B	$3A,$AA,$00

	ORG	RBMA + $1600 + $06

	DC.B	$3A,$AB,$00

	ORG	RBMA + $1700 + $06

	DC.B	$0A,$AB,$00

	ORG	RBMA + $1800 + $06

	DC.B	$02,$AF,$00

	ORG	RBMA + $1900 + $06

	DC.B	$01,$4F,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$01,$5F,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$01,$7C,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$00,$F0,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$00,$F0,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$00,$30,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$00,$0C,$00

; FRAME # 4  WIZB  /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$05,$01,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$0A,$02,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$02,$02,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$02,$82,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$02,$8A,$00

	ORG	RBMA + $1000 + $09

	DC.B	$02,$8A,$00

	ORG	RBMA + $1100 + $09

	DC.B	$02,$AA,$00

	ORG	RBMA + $1200 + $09

	DC.B	$02,$AA,$00

	ORG	RBMA + $1300 + $09

	DC.B	$03,$FA,$00

	ORG	RBMA + $1400 + $09

	DC.B	$02,$AE,$00

	ORG	RBMA + $1500 + $09

	DC.B	$0E,$AE,$00

	ORG	RBMA + $1600 + $09

	DC.B	$0E,$AC,$00

	ORG	RBMA + $1700 + $09

	DC.B	$0E,$A8,$00

	ORG	RBMA + $1800 + $09

	DC.B	$02,$A0,$00

	ORG	RBMA + $1900 + $09

	DC.B	$01,$40,$00

	ORG	RBMA + $1A00 + $09

	DC.B	$01,$50,$00

	ORG	RBMA + $1B00 + $09

	DC.B	$01,$70,$00

	ORG	RBMA + $1C00 + $09

	DC.B	$00,$F0,$00

	ORG	RBMA + $1D00 + $09

	DC.B	$00,$F0,$00

	ORG	RBMA + $1E00 + $09

	DC.B	$00,$30,$00

	ORG	RBMA + $1F00 + $09

	DC.B	$00,$0C,$00

; FRAME # 5  WIZB  /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $0C

	DC.B	$05,$01,$40

	ORG	RBMA + $0C00 + $0C

	DC.B	$0A,$02,$80

	ORG	RBMA + $0D00 + $0C

	DC.B	$02,$02,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$02,$82,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$02,$8A,$00

	ORG	RBMA + $1000 + $0C

	DC.B	$02,$8A,$00

	ORG	RBMA + $1100 + $0C

	DC.B	$32,$AA,$00

	ORG	RBMA + $1200 + $0C

	DC.B	$32,$AA,$00

	ORG	RBMA + $1300 + $0C

	DC.B	$13,$FF,$00

	ORG	RBMA + $1400 + $0C

	DC.B	$32,$AA,$40

	ORG	RBMA + $1500 + $0C

	DC.B	$3E,$AA,$C0

	ORG	RBMA + $1600 + $0C

	DC.B	$0E,$AA,$C0

	ORG	RBMA + $1700 + $0C

	DC.B	$0E,$AA,$C0

	ORG	RBMA + $1800 + $0C

	DC.B	$02,$A8,$00

	ORG	RBMA + $1900 + $0C

	DC.B	$00,$58,$00

	ORG	RBMA + $1A00 + $0C

	DC.B	$00,$54,$00

	ORG	RBMA + $1B00 + $0C

	DC.B	$00,$54,$00

	ORG	RBMA + $1C00 + $0C

	DC.B	$00,$3C,$00

	ORG	RBMA + $1D00 + $0C

	DC.B	$00,$0F,$00

	ORG	RBMA + $1E00 + $0C

	DC.B	$00,$03,$00

	ORG	RBMA + $1F00 + $0C

	DC.B	$00,$00,$C0

	.END
