; FRAME # 1  WIZC  /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$00,$00

	ORG	RBMA + $0300

	DC.B	$00,$00,$00

	ORG	RBMA + $0400

	DC.B	$00,$00,$00

	ORG	RBMA + $0500

	DC.B	$00,$00,$00

	ORG	RBMA + $0600

	DC.B	$00,$00,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$05,$01,$40

	ORG	RBMA + $0C00

	DC.B	$0A,$02,$80

	ORG	RBMA + $0D00

	DC.B	$02,$02,$00

	ORG	RBMA + $0E00

	DC.B	$02,$82,$00

	ORG	RBMA + $0F00

	DC.B	$02,$8A,$00

	ORG	RBMA + $1000

	DC.B	$02,$8A,$00

	ORG	RBMA + $1100

	DC.B	$02,$AA,$00

	ORG	RBMA + $1200

	DC.B	$02,$AA,$00

	ORG	RBMA + $1300

	DC.B	$03,$FF,$00

	ORG	RBMA + $1400

	DC.B	$02,$A9,$00

	ORG	RBMA + $1500

	DC.B	$02,$AA,$C0

	ORG	RBMA + $1600

	DC.B	$0E,$AA,$C0

	ORG	RBMA + $1700

	DC.B	$0E,$AA,$C0

	ORG	RBMA + $1800

	DC.B	$3E,$A8,$00

	ORG	RBMA + $1900

	DC.B	$30,$10,$00

	ORG	RBMA + $1A00

	DC.B	$10,$54,$00

	ORG	RBMA + $1B00

	DC.B	$30,$54,$00

	ORG	RBMA + $1C00

	DC.B	$30,$FC,$00

	ORG	RBMA + $1D00

	DC.B	$0C,$FC,$00

	ORG	RBMA + $1E00

	DC.B	$0C,$30,$00

	ORG	RBMA + $1F00

	DC.B	$03,$30,$00

; FRAME # 2  WIZC  /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$54,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$01,$55,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$05,$55,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$05,$54,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$01,$56,$00

	ORG	RBMA + $1000 + $03

	DC.B	$02,$56,$00

	ORG	RBMA + $1100 + $03

	DC.B	$02,$9A,$00

	ORG	RBMA + $1200 + $03

	DC.B	$02,$AA,$00

	ORG	RBMA + $1300 + $03

	DC.B	$03,$FF,$00

	ORG	RBMA + $1400 + $03

	DC.B	$02,$A9,$00

	ORG	RBMA + $1500 + $03

	DC.B	$02,$AA,$C0

	ORG	RBMA + $1600 + $03

	DC.B	$0E,$AA,$C0

	ORG	RBMA + $1700 + $03

	DC.B	$0E,$AA,$C0

	ORG	RBMA + $1800 + $03

	DC.B	$3E,$A8,$00

	ORG	RBMA + $1900 + $03

	DC.B	$30,$10,$00

	ORG	RBMA + $1A00 + $03

	DC.B	$10,$54,$00

	ORG	RBMA + $1B00 + $03

	DC.B	$30,$54,$00

	ORG	RBMA + $1C00 + $03

	DC.B	$30,$FC,$00

	ORG	RBMA + $1D00 + $03

	DC.B	$0C,$FC,$00

	ORG	RBMA + $1E00 + $03

	DC.B	$0C,$30,$00

	ORG	RBMA + $1F00 + $03

	DC.B	$03,$30,$00

; FRAME # 3  WIZC  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $06

	DC.B	$00,$54,$00

	ORG	RBMA + $0C00 + $06

	DC.B	$01,$55,$00

	ORG	RBMA + $0D00 + $06

	DC.B	$05,$55,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$15,$55,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$15,$55,$00

	ORG	RBMA + $1000 + $06

	DC.B	$05,$55,$40

	ORG	RBMA + $1100 + $06

	DC.B	$05,$55,$40

	ORG	RBMA + $1200 + $06

	DC.B	$05,$55,$40

	ORG	RBMA + $1300 + $06

	DC.B	$15,$55,$40

	ORG	RBMA + $1400 + $06

	DC.B	$15,$55,$40

	ORG	RBMA + $1500 + $06

	DC.B	$15,$55,$00

	ORG	RBMA + $1600 + $06

	DC.B	$05,$55,$00

	ORG	RBMA + $1700 + $06

	DC.B	$05,$55,$40

	ORG	RBMA + $1800 + $06

	DC.B	$3D,$55,$40

	ORG	RBMA + $1900 + $06

	DC.B	$31,$55,$00

	ORG	RBMA + $1A00 + $06

	DC.B	$10,$54,$00

	ORG	RBMA + $1B00 + $06

	DC.B	$30,$54,$00

	ORG	RBMA + $1C00 + $06

	DC.B	$30,$FC,$00

	ORG	RBMA + $1D00 + $06

	DC.B	$0C,$FC,$00

	ORG	RBMA + $1E00 + $06

	DC.B	$0C,$30,$00

	ORG	RBMA + $1F00 + $06

	DC.B	$03,$30,$00

; FRAME # 4  WIZC  /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $09

	DC.B	$00,$34,$00

	ORG	RBMA + $0C00 + $09

	DC.B	$00,$57,$00

	ORG	RBMA + $0D00 + $09

	DC.B	$03,$D5,$C0

	ORG	RBMA + $0E00 + $09

	DC.B	$03,$54,$C0

	ORG	RBMA + $0F00 + $09

	DC.B	$01,$55,$50

	ORG	RBMA + $1000 + $09

	DC.B	$05,$5D,$54

	ORG	RBMA + $1100 + $09

	DC.B	$1D,$57,$54

	ORG	RBMA + $1200 + $09

	DC.B	$35,$57,$5C

	ORG	RBMA + $1300 + $09

	DC.B	$55,$55,$75

	ORG	RBMA + $1400 + $09

	DC.B	$55,$55,$55

	ORG	RBMA + $1500 + $09

	DC.B	$55,$5D,$55

	ORG	RBMA + $1600 + $09

	DC.B	$75,$55,$55

	ORG	RBMA + $1700 + $09

	DC.B	$57,$55,$75

	ORG	RBMA + $1800 + $09

	DC.B	$15,$55,$54

	ORG	RBMA + $1900 + $09

	DC.B	$15,$57,$54

	ORG	RBMA + $1A00 + $09

	DC.B	$15,$D5,$74

	ORG	RBMA + $1B00 + $09

	DC.B	$0D,$55,$50

	ORG	RBMA + $1C00 + $09

	DC.B	$05,$55,$C0

	ORG	RBMA + $1D00 + $09

	DC.B	$01,$55,$00

	ORG	RBMA + $1E00 + $09

	DC.B	$00,$50,$00

	ORG	RBMA + $1F00 + $09

	DC.B	$00,$00,$00

; FRAME # 5  WIZC  /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0500 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0600 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0700 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0800 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0900 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $0C

	DC.B	$00,$10,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$00,$04,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $1000 + $0C

	DC.B	$00,$11,$00

	ORG	RBMA + $1100 + $0C

	DC.B	$01,$10,$40

	ORG	RBMA + $1200 + $0C

	DC.B	$04,$44,$00

	ORG	RBMA + $1300 + $0C

	DC.B	$11,$11,$44

	ORG	RBMA + $1400 + $0C

	DC.B	$04,$04,$10

	ORG	RBMA + $1500 + $0C

	DC.B	$11,$41,$44

	ORG	RBMA + $1600 + $0C

	DC.B	$04,$10,$10

	ORG	RBMA + $1700 + $0C

	DC.B	$04,$44,$40

	ORG	RBMA + $1800 + $0C

	DC.B	$01,$01,$04

	ORG	RBMA + $1900 + $0C

	DC.B	$04,$14,$40

	ORG	RBMA + $1A00 + $0C

	DC.B	$00,$00,$00

	ORG	RBMA + $1B00 + $0C

	DC.B	$01,$44,$40

	ORG	RBMA + $1C00 + $0C

	DC.B	$00,$10,$00

	ORG	RBMA + $1D00 + $0C

	DC.B	$00,$04,$00

	ORG	RBMA + $1E00 + $0C

	DC.B	$00,$10,$00

	ORG	RBMA + $1F00 + $0C

	DC.B	$00,$00,$00

	.END
