; FRAME # 1  WLFDED/SPR

	ORG	RBMA + $0000

	DC.B	$00,$A8,$00

	ORG	RBMA + $0100

	DC.B	$02,$AA,$00

	ORG	RBMA + $0200

	DC.B	$0A,$AA,$80

	ORG	RBMA + $0300

	DC.B	$0A,$EE,$80

	ORG	RBMA + $0400

	DC.B	$0A,$BA,$80

	ORG	RBMA + $0500

	DC.B	$2B,$AB,$A0

	ORG	RBMA + $0600

	DC.B	$2A,$FE,$A0

	ORG	RBMA + $0700

	DC.B	$2A,$BA,$A0

	ORG	RBMA + $0800

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $0900

	DC.B	$AB,$AB,$A8

	ORG	RBMA + $0A00

	DC.B	$AB,$EF,$A8

	ORG	RBMA + $0B00

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0C00

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0D00

	DC.B	$A2,$AA,$28

	ORG	RBMA + $0E00

	DC.B	$80,$00,$08

	ORG	RBMA + $0F00

	DC.B	$80,$00,$08

	.END
