; FRAME # 1  WOLF  /SPR

	ORG	RBMA + $0000

	DC.B	$02,$AA,$A8

	ORG	RBMA + $0100

	DC.B	$02,$AA,$A8

	ORG	RBMA + $0200

	DC.B	$02,$AA,$A8

	ORG	RBMA + $0300

	DC.B	$00,$AA,$A0

	ORG	RBMA + $0400

	DC.B	$00,$A8,$00

	ORG	RBMA + $0500

	DC.B	$00,$28,$00

	ORG	RBMA + $0600

	DC.B	$00,$20,$00

	ORG	RBMA + $0700

	DC.B	$00,$00,$00

	ORG	RBMA + $0800

	DC.B	$00,$00,$00

	ORG	RBMA + $0900

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00

; FRAME # 2  WOLF  /SPR

	ORG	RBMA + $0000 + $03

	DC.B	$0A,$AA,$68

	ORG	RBMA + $0100 + $03

	DC.B	$0A,$A5,$68

	ORG	RBMA + $0200 + $03

	DC.B	$2A,$A5,$A0

	ORG	RBMA + $0300 + $03

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $0400 + $03

	DC.B	$0A,$AA,$A8

	ORG	RBMA + $0500 + $03

	DC.B	$0A,$AA,$A8

	ORG	RBMA + $0600 + $03

	DC.B	$02,$A8,$A8

	ORG	RBMA + $0700 + $03

	DC.B	$02,$A0,$20

	ORG	RBMA + $0800 + $03

	DC.B	$00,$80,$00

	ORG	RBMA + $0900 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0A00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0B00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0C00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0D00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $03

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $03

	DC.B	$00,$00,$00

; FRAME # 3  WOLF  /SPR

	ORG	RBMA + $0000 + $06

	DC.B	$AA,$BE,$AA

	ORG	RBMA + $0100 + $06

	DC.B	$2A,$EA,$AA

	ORG	RBMA + $0200 + $06

	DC.B	$2A,$EA,$AA

	ORG	RBMA + $0300 + $06

	DC.B	$0A,$AA,$A8

	ORG	RBMA + $0400 + $06

	DC.B	$0A,$A5,$A8

	ORG	RBMA + $0500 + $06

	DC.B	$0A,$A5,$A6

	ORG	RBMA + $0600 + $06

	DC.B	$2A,$95,$A4

	ORG	RBMA + $0700 + $06

	DC.B	$AA,$9A,$A8

	ORG	RBMA + $0800 + $06

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0900 + $06

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0A00 + $06

	DC.B	$2A,$80,$AA

	ORG	RBMA + $0B00 + $06

	DC.B	$0A,$00,$2A

	ORG	RBMA + $0C00 + $06

	DC.B	$08,$00,$08

	ORG	RBMA + $0D00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0E00 + $06

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $06

	DC.B	$00,$00,$00

; FRAME # 4  WOLF  /SPR

	ORG	RBMA + $0000 + $09

	DC.B	$0A,$BA,$00

	ORG	RBMA + $0100 + $09

	DC.B	$0A,$FE,$80

	ORG	RBMA + $0200 + $09

	DC.B	$0B,$FF,$80

	ORG	RBMA + $0300 + $09

	DC.B	$0B,$55,$80

	ORG	RBMA + $0400 + $09

	DC.B	$2B,$66,$A0

	ORG	RBMA + $0500 + $09

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $0600 + $09

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $0700 + $09

	DC.B	$2A,$6A,$60

	ORG	RBMA + $0800 + $09

	DC.B	$A5,$65,$68

	ORG	RBMA + $0900 + $09

	DC.B	$A6,$AA,$A8

	ORG	RBMA + $0A00 + $09

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0B00 + $09

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0C00 + $09

	DC.B	$A2,$AA,$28

	ORG	RBMA + $0D00 + $09

	DC.B	$80,$00,$00

	ORG	RBMA + $0E00 + $09

	DC.B	$00,$00,$00

	ORG	RBMA + $0F00 + $09

	DC.B	$00,$00,$00

; FRAME # 5  WOLF  /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$A8,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$02,$BA,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$0A,$FE,$80

	ORG	RBMA + $0300 + $0C

	DC.B	$0B,$EF,$80

	ORG	RBMA + $0400 + $0C

	DC.B	$09,$65,$80

	ORG	RBMA + $0500 + $0C

	DC.B	$29,$95,$A0

	ORG	RBMA + $0600 + $0C

	DC.B	$2A,$66,$A0

	ORG	RBMA + $0700 + $0C

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $0800 + $0C

	DC.B	$26,$66,$60

	ORG	RBMA + $0900 + $0C

	DC.B	$A5,$65,$68

	ORG	RBMA + $0A00 + $0C

	DC.B	$A5,$A9,$68

	ORG	RBMA + $0B00 + $0C

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0C00 + $0C

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0D00 + $0C

	DC.B	$A2,$AA,$28

	ORG	RBMA + $0E00 + $0C

	DC.B	$80,$00,$08

	ORG	RBMA + $0F00 + $0C

	DC.B	$80,$00,$08

; FRAME # 6  WOLF  /SPR

	ORG	RBMA + $0000 + $0F

	DC.B	$00,$A8,$00

	ORG	RBMA + $0100 + $0F

	DC.B	$02,$AA,$00

	ORG	RBMA + $0200 + $0F

	DC.B	$0A,$EE,$80

	ORG	RBMA + $0300 + $0F

	DC.B	$09,$BD,$80

	ORG	RBMA + $0400 + $0F

	DC.B	$09,$66,$80

	ORG	RBMA + $0500 + $0F

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $0600 + $0F

	DC.B	$2A,$AA,$A0

	ORG	RBMA + $0700 + $0F

	DC.B	$26,$66,$60

	ORG	RBMA + $0800 + $0F

	DC.B	$A6,$66,$68

	ORG	RBMA + $0900 + $0F

	DC.B	$A6,$AA,$68

	ORG	RBMA + $0A00 + $0F

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0B00 + $0F

	DC.B	$AA,$AA,$A8

	ORG	RBMA + $0C00 + $0F

	DC.B	$A2,$AA,$28

	ORG	RBMA + $0D00 + $0F

	DC.B	$80,$00,$08

	ORG	RBMA + $0E00 + $0F

	DC.B	$80,$00,$08

	ORG	RBMA + $0F00 + $0F

	DC.B	$00,$00,$00

	.END
