; FRAME # 1  WTEYE /SPR

	ORG	RBMA + $0000

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0100

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0200

	DC.B	$00,$AA,$80,$00

	ORG	RBMA + $0300

	DC.B	$0A,$AA,$A8,$00

	ORG	RBMA + $0400

	DC.B	$0A,$AA,$AA,$80

	ORG	RBMA + $0500

	DC.B	$2A,$AB,$FA,$A0

	ORG	RBMA + $0600

	DC.B	$2A,$AF,$FE,$A8

	ORG	RBMA + $0700

	DC.B	$AA,$BF,$0F,$AA

	ORG	RBMA + $0800

	DC.B	$AA,$BC,$03,$AA

	ORG	RBMA + $0900

	DC.B	$2A,$BC,$03,$A8

	ORG	RBMA + $0A00

	DC.B	$0A,$BC,$23,$A0

	ORG	RBMA + $0B00

	DC.B	$02,$BF,$2B,$80

	ORG	RBMA + $0C00

	DC.B	$00,$2F,$F8,$00

	ORG	RBMA + $0D00

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0E00

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0F00

	DC.B	$00,$00,$00,$00

; FRAME # 2  WTEYE /SPR

	ORG	RBMA + $0000 + $04

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0100 + $04

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0200 + $04

	DC.B	$00,$AA,$80,$00

	ORG	RBMA + $0300 + $04

	DC.B	$0A,$AA,$A8,$00

	ORG	RBMA + $0400 + $04

	DC.B	$0A,$AA,$AA,$80

	ORG	RBMA + $0500 + $04

	DC.B	$2A,$AB,$FA,$A0

	ORG	RBMA + $0600 + $04

	DC.B	$AA,$AF,$FE,$A8

	ORG	RBMA + $0700 + $04

	DC.B	$6A,$BF,$0F,$AA

	ORG	RBMA + $0800 + $04

	DC.B	$56,$BC,$03,$A5

	ORG	RBMA + $0900 + $04

	DC.B	$15,$7C,$23,$54

	ORG	RBMA + $0A00 + $04

	DC.B	$05,$55,$55,$50

	ORG	RBMA + $0B00 + $04

	DC.B	$01,$55,$55,$40

	ORG	RBMA + $0C00 + $04

	DC.B	$00,$15,$54,$00

	ORG	RBMA + $0D00 + $04

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0E00 + $04

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0F00 + $04

	DC.B	$00,$00,$00,$00

; FRAME # 3  WTEYE /SPR

	ORG	RBMA + $0000 + $08

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0100 + $08

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0200 + $08

	DC.B	$03,$CF,$3C,$00

	ORG	RBMA + $0300 + $08

	DC.B	$0F,$FF,$FF,$00

	ORG	RBMA + $0400 + $08

	DC.B	$3F,$D5,$57,$C0

	ORG	RBMA + $0500 + $08

	DC.B	$3D,$55,$55,$F0

	ORG	RBMA + $0600 + $08

	DC.B	$35,$55,$55,$5C

	ORG	RBMA + $0700 + $08

	DC.B	$55,$55,$55,$57

	ORG	RBMA + $0800 + $08

	DC.B	$55,$55,$55,$57

	ORG	RBMA + $0900 + $08

	DC.B	$15,$55,$55,$54

	ORG	RBMA + $0A00 + $08

	DC.B	$05,$55,$55,$50

	ORG	RBMA + $0B00 + $08

	DC.B	$01,$55,$55,$40

	ORG	RBMA + $0C00 + $08

	DC.B	$00,$15,$54,$00

	ORG	RBMA + $0D00 + $08

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0E00 + $08

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0F00 + $08

	DC.B	$00,$00,$00,$00

; FRAME # 4  WTEYE /SPR

	ORG	RBMA + $0000 + $0C

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0100 + $0C

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0200 + $0C

	DC.B	$00,$FF,$80,$00

	ORG	RBMA + $0300 + $0C

	DC.B	$0F,$0F,$E8,$00

	ORG	RBMA + $0400 + $0C

	DC.B	$0C,$03,$EA,$80

	ORG	RBMA + $0500 + $0C

	DC.B	$3C,$03,$EA,$A0

	ORG	RBMA + $0600 + $0C

	DC.B	$3C,$2B,$EA,$A8

	ORG	RBMA + $0700 + $0C

	DC.B	$AF,$0A,$AA,$AA

	ORG	RBMA + $0800 + $0C

	DC.B	$AF,$FB,$AA,$AA

	ORG	RBMA + $0900 + $0C

	DC.B	$2B,$FE,$AA,$A8

	ORG	RBMA + $0A00 + $0C

	DC.B	$0A,$AA,$AA,$A0

	ORG	RBMA + $0B00 + $0C

	DC.B	$02,$AA,$AA,$80

	ORG	RBMA + $0C00 + $0C

	DC.B	$00,$2A,$A8,$00

	ORG	RBMA + $0D00 + $0C

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0E00 + $0C

	DC.B	$00,$00,$00,$00

	ORG	RBMA + $0F00 + $0C

	DC.B	$00,$00,$00,$00

	.END
